### ISSUE TITLE
Container on Dockerhub

### ISSUE THREAD

**Issue by bdwyertech** [aws/copilot-cli#1110]
Do you have any intentions of having a container artifact for this and putting it on Dockerhub?  Similar to [amazon/aws-cli](https://hub.docker.com/r/amazon/aws-cli)

We are a large customer and I build our cloud platform CLI tooling.  I wrote a container wrapping library that I use to extend our CLI and I would love to add this to our tool.

It would also make it easier to consume this tool in pipelines.

**Comment by efekarakus** [comment]
Hi @bdwyertech, 

Thanks for the request, It makes sense to me! We'll update the issue when we start making progress on this story.

**Comment by iamhopaul123** [comment]
Heya @bdwyertech, we just released [v0.5.0](https://github.com/aws/copilot-cli/releases/tag/v0.5.0) and now you can use existing image rather than building it from dockerfile locally by specifying `image.location` in your manifest as:

```
image:
  location: amazon/aws-cli
  port: 80
```

Alternatively, either answering questions or providing `--image` flag for `svc init` could help do the trick as well.

Close the issue for now as the feature gap is already filled. Feel free to reopen if you have any other question!

**Comment by bdwyertech** [comment]
Awesome, thank you! @iamhopaul123
