### ISSUE TITLE
Env variable with value as "on" is converted to true

### ISSUE THREAD

**Issue by FarmaanElahi** [aws/copilot-cli#1120]
Currently I am deploying a service where there is an requirement for env variable which can take value as `on` or `off`. But when this service is being deployed, the container will have a boolean value `true` for `on` and `false` for `off`

Example:
```yaml
variables:                      
  ENV_KEY: on
```

The resulting container will have env as `ENV_KEY`: `true`

**Comment by FarmaanElahi** [comment]
I tried using ` ENV_KEY`: `"on"` but that also didn't worked.

After digging into generated cloudformation template, I found out, the file is generated properly .
```
- Name: ENV_KEY
   Value: on
```

It looks like it is an issue with ECS

**Comment by kohidave** [comment]
Oh interesting, we'll take a look.

**Comment by git823** [comment]
In YAML 1.1, on/off are recognized as boolean value.
https://yaml.org/type/bool.html

This converting issue occurs generally in CloudFormation. We need to specify the value as string within CloudFormation template by enclosing in quotations.

**Comment by FarmaanElahi** [comment]
I have already tried that and even then it is converting that to a boolean

**Comment by git823** [comment]
Sorry for misleading. Even if we specify the value with quotations in manifest.yml, copilot generates CloudFormation template with removing them. Copilot need to enclose the value in quotations within CloudFormation template.

**Comment by efekarakus** [comment]
The reason why this is happening is that we use Go templates while transforming the manifest to a CloudFormation template:
https://github.com/aws/copilot-cli/blob/1c3209864d3c0497bdfa69b909d19ec8e0782eeb/templates/services/common/cf/envvars.yml#L17-L18

We write the value of the env variable with `{{.Value}}` and in this situation the value is written as just:
```yaml
- Name: ENV_VAR
  Value: on  # not escaped which results in a boolean value.
```
Similarly in #1292, the value is written as just `{}` so the value becomes a "mapping" object instead of a "string".

Instead, we should be able to explicitly mark these values as strings. One possible solution is to use [literal block scalars](http://blogs.perl.org/users/tinita/2018/03/strings-in-yaml---to-quote-or-not-to-quote.html) while writing env vars in our template:
```yaml
- Name: {{$name}}
  Value: |
     {{$value}}
```
