### ISSUE TITLE
Copilot svc deploy failure - endless waiting

### ISSUE THREAD

**Issue by niros1** [aws/copilot-cli#1369]
Hi, I faced several times that re-deploy a service stuck forever, the root cause was that the cloud formation failed cause of ECS service failure, the service is triggered and then failed (e.g. cause of code error) in a loop. 
In that case I found myself deleting manually the CF stack, deleting the Copilot svc (copilot svc delete), and init the service from scratch.

What I am doing wrong? how can I avoid that scenario?

**Comment by efekarakus** [comment]
Heya @niros1 !

Do you have visibility into why the service is failing to come up? Looking at stopped tasks from the Console might help debug the issue.
![Screen Shot 2020-09-09 at 9 03 33 AM](https://user-images.githubusercontent.com/879348/92623682-6f465180-f27b-11ea-87c7-32284f7d2658.png)

To avoid the long wait for CloudFormation  to stabilize, one trick is to update the desired count of your service to 0 (https://github.com/aws/copilot-cli/issues/1180#issuecomment-662573037) so that CloudFormation can move on and then do another deployment after the service code is fixed

**Comment by niros1** [comment]
Thanks for the answer,
Yes, I have the visibility, it is (normally) just normal bugs (e.g. missing directory or something like that) which makes the task failed.

regarding the workaround you suggested, so in case of an issue I should update the task definition to 0, that will make cloud formation to move on, I don't need to deploy twice on every deployment right?

**Comment by iamhopaul123** [comment]
Hi @niros1, we are currently working actively on supporting auto scaling in Copilot https://github.com/aws/copilot-cli/issues/1154. If you decide to use auto scaling with your service, then you could set the task number range to be for example `0-10` then Copilot will set the desired count to 0 when you first deploy your service (setting it to 0 can make CFN move forward creating the stack without being blocked by potential normal task bugs). As more traffic coming in the service will be automatically scaled up and you don't need to do the second deployment!

**Comment by niros1** [comment]
Cool, looking forward to that!!!

**Comment by iamhopaul123** [comment]
Hello @niros1, we already released the auto scaling feature and it is ready for use. Close the PR for now. Feel free to reopen it!

**Comment by niros1** [comment]
Amazing
