### ISSUE TITLE
Load Balanced Webservice - must provide an option to deploy service in private subnets and bind it with public ALB sitting in public subnet

### ISSUE THREAD

**Issue by sanjeevtejyan** [aws/copilot-cli#1489]
There are following issues
- copilot svc deploy, service in public subnets, Ideally it should be deployed in private subnet
- There is no option to choose not to assign public ip. There is no need to assign public ip as service is exposed by public load balancer and thus makes the service vulnerable from security aspect.

This seems to be an urgent issue as this brings security aspect.

**Comment by kohidave** [comment]
Hey there! Thanks so much for reaching out - we appreciate it!

So first off, I really appreciate appreciate your eye for security! We actually originally designed our environments as you described, with tasks launched in private subnets. This ends up forcing customers to set up a NATGateway which is pretty expensive, so we opted to place tasks in public subnets. To ensure that these tasks are secure - the security groups they are placed into only allow traffic from the ALB which effectively isolates them from external access. 

This is a common pattern, and in fact, is one of AWS's [best practices](https://aws.amazon.com/blogs/compute/task-networking-in-aws-fargate/) for Fargate networking:

> Run internet tasks that require internet access in a public subnet
If you have tasks that require internet access and a lot of bandwidth for communication with other services, it is best to run them in a public subnet. Give them public IP addresses so that each task can communicate with other services directly.

Beyond that, rest assured that before we release a pattern, they are pen-tested and vetted for security.

Now, that all being said, we realize that there are times when customers want higher isolation for their tasks and would like to run them in a private subnet. While this increases the cost of running these tasks (requiring either private links or NAT Gateways), it's sometimes a requirement. To help out with this the team is currently designing a way to allow customers to request this environment topology. I don't have the issue link handy - but we've been thinking about this for a while and are trying to come up with the best way to expose this to folks. 

Hope that helps clears things up! Thanks again for reaching out - we'll let you know when we offer the private network feature 😃

**Comment by efekarakus** [comment]
Hello! This is now supported with copilot v1.5.0 😄 https://github.com/aws/copilot-cli/releases/tag/v1.5.0 🚀 

In your manifests:
```yaml
network:
  vpc:
    placement: 'private'
```
