### ISSUE TITLE
ECR Repository existence fails a `copilot init`

### ISSUE THREAD

**Issue by bwarren2** [aws/copilot-cli#1490]
I have been trying to start up a demo project, and an initial build saw the Cloudformation create of the ECS Service hang.  After about 28 minutes I gave up on the stack and deleted it.  Since then, I have tried:

1. Rerunning `copilot deploy`
2. Deleting all the stacks and rerunning `copilot init`
3. Running `copilot app delete` and rerunning `copilot init`

All of these methods have failed, apparently on the ECR repository existing for the project.  

Ideas: maybe there needs to be a `copilot purge` command for deleting everything that could block recreating from scratch?  Maybe this command would need to exist at the `svc` and `app` levels?  Or maybe pipe the output of the cloudformation stack create back to the CLI?  I don't know; I am just deleting objects manually right now.

**Comment by efekarakus** [comment]
Hi @bwarren2 ! I'm sorry to hear about that the deployments didn't work :(

>  ECR repository existing for the project.

Can you elaborate on this? Was there a particular error that highlighted the ECR repository not being able to create?

> Cloudformation create of the ECS Service hang. After about 28 minutes I gave up on the stack and deleted it. 

Usually services will hang because the task's healthcheck will keep failing. One way to validate that is to go to the Amazon ECS console and check for the "Stopped" tasks for your service. 

![Screen Shot 2020-09-09 at 9 03 33 AM](https://user-images.githubusercontent.com/879348/92623682-6f465180-f27b-11ea-87c7-32284f7d2658.png)

>  Or maybe pipe the output of the cloudformation stack create back to the CLI? I don't know; I am just deleting objects manually right now.

Thanks for the suggestion! We've heard similar feedback and added https://github.com/aws/copilot-cli/issues/1421 to our backlog in the sprint, and will work on showing progress of your service deployments

**Comment by bwarren2** [comment]
The healthcheck failure was indeed the problem :) .  I have been trying to delete stacks and any resources I know of to get back to zero, but now have errors like 

```$ copilot app delete oct12
Are you sure you want to delete application oct12? Yes
✔ Cleaned up deployment resources.
✘ Error deleting application resources.
✘ delete app resources: operation 6FDD2817-8833-4F70-A0BD-3F4B1FCF0694 for stack set oct12-infrastructure failed
```

Not really sure what to do with this, but the verbose mode you mention will probably help :)

**Comment by bwarren2** [comment]
Closing this issue because #1421 will probably address it.  Thank you @efekarakus!
