### ISSUE TITLE
Pipeline init requires Connect to GitHub step

### ISSUE THREAD

**Issue by trevorrobertsjr** [aws/copilot-cli#1504]
The pipeline Source step fails unless I edit the stage and click Connect to GitHub.

The existing copilot automation and including the token does not appear to be sufficient to pull the source from GitHub.

**Comment by bvtujo** [comment]
Hi @trevorrobertsjr, so sorry you got bit by this issue. When you create your personal access token for Copilot you need to temporarily grant it the `repo` and `admin:repo_hook` permission scopes here on Github in order to create the webhook which sends pushes and merges to CodeBuild. Once you've created the pipeline, you can remove those scopes if you like. 

This is mentioned in our [documentation](https://aws.github.io/copilot-cli/docs/concepts/pipelines/#step-1-configuring-your-pipeline) but we definitely need to do a better job of communicating this from the CLI itself, as otherwise others will hit the same pothole! 

Thanks so much for bringing this up.

**Comment by huanjani** [comment]
Closing, as Copilot has moved from using tokens to connect to GitHub to using CodeStar Connections.
