### ISSUE TITLE
Spot usage 

### ISSUE THREAD

**Issue by Fodoj** [aws/copilot-cli#1586]
What's the recommended way to enable Spot usage? I saw that provider is there already - https://github.com/aws/copilot-cli/commit/0c20b23325a3515e490accfd232de6d02f06849c, but not in use. Would be great to be able to specify it somewhere.

**Comment by efekarakus** [comment]
Heya @Fodoj !

We'd love to learn more how you'd like to use Fargate Spot. 
Are you looking to use it in your services with autoscaling? Liked described here: https://github.com/aws/copilot-cli/issues/1154 under **Spot Capacity** 
Or were you looking to use `task run` on a spot task?

Let us know if you have a particular usecase in mind!

**Comment by Fodoj** [comment]
I have two services - primary web application and a background worker, both are services without single copilot app.

At least in staging environment I would like to run it 100% on spot. In production may be 50/50, but I don’t new auto scaling right now.

I guess I can also setup “auto scaling” with spot, ranging from 2 tasks to 2 tasks, so that there are always 2 tasks running?

**Comment by Fodoj** [comment]
Just to clarify - did I understand correctly, that in regards to spot functionality, this https://github.com/aws/copilot-cli/issues/1154 is just a proposal, not yet implemented?

**Comment by efekarakus** [comment]
yeah that's right, it's not implemented yet.
Two days ago we added two new fields for autoscaling Load Balanced Web Services: `requests` and `response_time` (#1664) which should go out next release, so we're making progress towards more advanced autoscaling fields over time :)

**Comment by Fodoj** [comment]
Are there any news about this? May be I can help with PR? :-)

**Comment by efekarakus** [comment]
Hi @Fodoj 👋 ! We'd love it if you'd like to contribute to the CLI :) 
If you plan to, would you mind updating us with the manifest changes you are proposing? Is it option 1)
```yaml
count:
  range: 
    dedicated: 1-5
    spot: 5-25
```
I'm not sure if it's possible to actually set `spot: 5-25`, that'd be my only concern.


For visibility, our plan is to work on spot in 2 weeks (after the [current sprint](https://github.com/aws/copilot-cli/projects/1)) so starting 3/8. Currently, we're planning to deliver on the following in the next two weeks:
- Release BitBucket integration for pipelines
- Release bring your own EFS filesystem 
- Add `entrypoint` and `command` support to the manifest
- Allow launching tasks in private subnets if you bring your own VPC
- Design for control over generated DNS names (https://github.com/aws/copilot-cli/issues/1188)

**Comment by efekarakus** [comment]
Hi folks! I just wanted to give an update on this since it's 3/8, we've indeed merged the updates above last sprint, but we won't be starting yet on the spot feature this sprint in favor of `task run` improvements (https://github.com/aws/copilot-cli/issues/1269) to close the loop for that command:
* Adding a `--svc` flag to `task run`
* Emitting IP addresses after using `task run`

Thanks for your patience 🙇 . 

<details>
  <summary> Previous sprint features </summary>  
  
   * ~~Release BitBucket integration for pipelines~~ ([v1.3.0](https://github.com/aws/copilot-cli/releases/tag/v1.3.0))
   * ~~Release bring your own EFS filesystem~~([v1.3.0](https://github.com/aws/copilot-cli/releases/tag/v1.3.0))
   * ~~Add entrypoint and command support to the manifest~~ (#2017 and #1999)
   * ~~Allow launching tasks in private subnets if you bring your own VPC~~ (#1979)
</details>

**Comment by SoManyHs** [comment]
This was addressed in https://github.com/aws/copilot-cli/pull/2188!

**Comment by bvtujo** [comment]
Hi @Fodoj! Fargate Spot support is now available in [Copilot v1.6.0](https://github.com/aws/copilot-cli/releases/tag/v1.6.0)! 🎉🎉  👀 

Check it out and let us know how it works for you!

**Comment by Fodoj** [comment]
Works flawlessly! Thanks a lot, going to save some costs here :-)
