### ISSUE TITLE
Copilot svc delete command does not remove associated dynamodb table and IAM roles

### ISSUE THREAD

**Issue by sundarnarasiman** [aws/copilot-cli#1610]
Generally a Copilot service can be configured with a storage like Amazon DynamoDB. When we configure a Amazon DynamoDB storage using 'storage init' commands it creates Amazon DynamoDB table and bunch of IAM roles. When we try to delete this service (configured with Amazon DynamoDB), it does not delete the associated Amazon DynamoDB table and IAM roles. This is probably due to the absence of delete functionality in storage commands. This needs to be fixed.

**Comment by iamhopaul123** [comment]
Hello @sundarnarasiman, thank you for your suggestion! Addons and services/jobs are considered as separate modules in Copilot. And usually all the addons resources will be deleted when you delete a service/job. However, we [intentionally](https://github.com/aws/copilot-cli/blob/881d7320e42337db1c8a570b4cd9a362d3d471c6/templates/addons/ddb/cf.yml#L14) don't delete any database addons because we think database contains more valuable information, and users might be surprised to see their databases get removed without any prompt.

However, maybe though we won't delete the database by default, we'll make it accessible by providing a flag for `svc delete`, in case some users want to remove the database as well.

**Comment by AndrchiamusI** [comment]
Just to confirm that this is now the case. On recently deleting a service the dynamodb tables that were created as addons were removed without warning.

Is this now the expected behaviour? 

The documentation states the following and does not forewarn you

> copilot svc delete deletes all resources associated with your service in a particular environment.
https://aws.github.io/copilot-cli/docs/commands/svc-delete/
