### ISSUE TITLE
Can't successfully deploy app with copilot

### ISSUE THREAD

**Issue by npb12** [aws/copilot-cli#1615]
I have a docker container for a small django project that I'm trying to deploy. 

After running 

```
copilot init --app ai-int                \
  --name lb-si                             \
  --type 'Load Balanced Web Service'     \
  --dockerfile './Dockerfile'            \
  --deploy
```

Everything builds correctly, but the deploy seems to get stuck and doesn't complete (hangs indefinitely).
No targets are registered to the target group and the url for the load balancer returns a 503.
Here's the final output

```
Login Succeeded
The push refers to repository [374153183614.dkr.ecr.us-east-1.amazonaws.com/ai-int/lb-si]
8397b626743a: Pushed 
0f0b8cefc3de: Pushed 
a4f395fb894d: Pushed 
90df760355a7: Pushed 
574ea6c52bdd: Pushed 
d1573fad78d1: Pushed 
14c1ff636882: Pushed 
48ebd1638acd: Pushed 
31f78d833a92: Pushed 
2ea751c0f96c: Pushed 
7a435d49206f: Pushed 
9674e3075904: Pushed 
831b66a484dc: Pushed 
init-img: digest: sha256:2c5a3c6895e897bb3f73b78421b3b5e6d1ae1e6b268d513b1e229692f7572dc0 size: 3052
⠹ Deploying lb-si:init-img to test. ^C
```

My Dockerfile

```
FROM python:3.7.4
ENV PYTHONUNBUFFERED=1
RUN mkdir /code
WORKDIR /code
COPY requirements.txt /code/
RUN pip install -r requirements.txt
EXPOSE 80
COPY . /code/
```

The cloudformation showing where it ultimately gets stuck:
<img width="792" alt="Screen Shot 2020-11-01 at 10 48 42 PM" src="https://user-images.githubusercontent.com/6107456/97828434-156b7200-1c95-11eb-991f-1a68ea9d2e01.png">

**Comment by kohidave** [comment]
Hey hey! So sorry about this! Usually this means the task is failing to start in ECS. If you open up the ECS console, select your service and take a look at the logs, it'll tell you why it's failing to start your container. 

You can look at all the stopped tasks in your service and it'll show you why it's failing. Select your service, open the tasks tab, and select "stopped". 

To stop the CloudFormation deployment you can set the desired count of your service to zero. 

We hope to expose a lot more of this information through copilot in the future to help folks debug - but for now, poking around through the console should have the info to help you figure out what's up. If you need more help let me know and I can try and help you debug!

**Comment by npb12** [comment]
Thanks for the quick response @kohidave!

The errors all come to this:
 "Essential container in task exited -- Network bindings - not configured"

Does that mean anything significant to you?

Sorry if this is a clear issue I'm missing, I'm new to the aws ecosystem, hence my choice of using copilot :)

**Comment by kohidave** [comment]
Oh that makes total sense!!

One thing I noticed - your Dockerfile doesn't look like it's actually starting your Django app. Try adding the following to the end of your Dockerfile: 

```
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
```

To the end of your Dockerfile. (Replace `manage.py` with your main python file - often manage.py is the default, and change the port to match whatever your django process is listening on - 8000 is the default for django, though).

Then, update your Copilot manifest file `copilot/lb-si/manifest.yaml` and change the port to '8000'. Then, once your previous stuck deployment is finished (you can set the count of the service to 0 or just cancel the deployment in CloudFormation) run `copilot deploy` again. 

One note - this is a bit of a shot in the dark, but if you're setting up your Dockerfile based on the Docker [quickstart](https://docs.docker.com/compose/django/) - the Dockerfile they show at the top is incomplete. They leave out the command because their compose file (further down) specifies it.

Hope that helps, and sorry about this friction again!

**Comment by npb12** [comment]
Thank you so much for the help, that worked!

**Comment by npb12** [comment]
So it looks like everything is building correctly, the cli returns a URL and cloudformation completes. However, the target fails to register. 

<img width="995" alt="Screen Shot 2020-11-02 at 9 23 59 AM" src="https://user-images.githubusercontent.com/6107456/97878919-44adcd80-1ced-11eb-9d19-b4b832281f21.png">

<img width="1002" alt="Screen Shot 2020-11-02 at 9 25 06 AM" src="https://user-images.githubusercontent.com/6107456/97878964-568f7080-1ced-11eb-8915-e9106720b47d.png">

**Comment by kohidave** [comment]
By default Copilot pings the "/" endpoint to make sure your service is up (health check). That endpoint probably isn't returning a 200. 

You can either add a handler fir "/" or change the health check endpoint in your manifest: https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck

Let me know if updating the health check works!

**Comment by npb12** [comment]
Getting close, but still getting that error. Should I be changing my Dockerfile EXPOSE statement to 8000? As opposed to 80.

**Comment by kohidave** [comment]
You should - but that's just informative (it only helps Copilot understand what port it should route traffic to but doesn't do anything at runtime). What error are you getting now?

**Comment by npb12** [comment]
Still the same issue unfortunately. I added a library django_health_check, thinking maybe it was an issue specific to how django constructs its urls -- to no avail. Not sure what the issue might be. Anything I can be checking to narrow it down?

**Comment by kohidave** [comment]
So when copilot created a URL for you, what happens when you click it or `curl` against it? Do you get a 200? 

Here's what I would do - in your django app, I'd create a really simple route that just returns a `200` at the `/` endpoint. 

If you're using the [django_health_check](https://pypi.org/project/django-health-check/) library, you have to specify a route for your health check. Typically this looks to be `/hc`. If you want to go with that, uncomment the [healthcheck](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/) field and set the value to `/hc`.

A health check is just a curl against a particular endpoint in your service that has to return a HTTP 2xx response.

**Comment by npb12** [comment]
I get a 503 on curl.

It looks like the culprit at this point could be tied to my postres db not connecting correctly. That's what I see when I run 
```copilot svc logs --follow```
Showing 
```django.db.utils.OperationalError: could not translate host name "db" to address: Name or service not known```

I think I'll need to clear that up so I can rule that out as the culprit?

**Comment by kohidave** [comment]
Yea - if that's causing your "/" route handler from accepting requests that'll do it.

**Comment by npb12** [comment]
is docker-compose.yml supported in copilot? That's where I'm setting all of my DB related credentials.

**Comment by bvtujo** [comment]
Docker Compose configuration isn't recognized by Copilot--for secret configurations, we recommend you use the [`secrets` section of the manifest](https://aws.github.io/copilot-cli/docs/developing/secrets/) to let Copilot fetch your DB credentials from SSM secure parameters so they never show up in plaintext anywhere.

If you have environment variables that don't contain sensitive info, you can specify them in the [`variables` section](https://aws.github.io/copilot-cli/docs/developing/environment-variables/#how-do-i-add-my-own-environment-variables) or inject them at build time via [Docker build args in the manifest](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build). We don't recommend the build args approach for variables, though, as Copilot won't know about them and they won't show up in the output of `copilot svc show`. We ESPECIALLY don't recommend doing this with sensitive data, as your container image will then contain secrets which will be accessible to anyone who runs `docker inspect` on it.

**Comment by efekarakus** [comment]
Heya @npb12 did the deployment work for you? can we help in any other way?

**Comment by efekarakus** [comment]
@bvtujo replied also here: https://stackoverflow.com/a/64774855/1201381

Closing the issue, feel free to re-open if you encounter a problem!
