### ISSUE TITLE
Integration with route53

### ISSUE THREAD

**Issue by vikasgoel76** [aws/copilot-cli#1698]
Copilot does not support automated integration between ECS and Route53

**Comment by efekarakus** [comment]
@vikasgoel76 What sort of integration were you looking for?

Copilot applications can support an HTTPS endpoint by providing a domain name in Route53: https://aws.github.io/copilot-cli/docs/commands/app-init/
```
copilot app init my-amazing-app --domain my-amazing-app.com
```

Or did you have something else in mind?

**Comment by sundarnarasiman** [comment]
Hi Vikas,

Could you elaborate more on your requirement ?

**Comment by sirbully** [comment]
> @vikasgoel76 What sort of integration were you looking for?
> 
> Copilot applications can support an HTTPS endpoint by providing a domain name in Route53: https://aws.github.io/copilot-cli/docs/commands/app-init/
> 
> ```
> copilot app init my-amazing-app --domain my-amazing-app.com
> ```
> 
> Or did you have something else in mind?

Newbie here, what command should be used if I already have an existing app and want to use the domain in Route 53? What I tried to do was set up an https listener in the load balancer and then attach an SSL certificate (ACM) for my domain in Route 53 via console. I didn't proceed with this idea because I thought that if I tried to mess up the resources created by copilot, I'd have an issue later.

I'm not sure if this is how the listener is set up?

https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http

Is there one for https?
