### ISSUE TITLE
Load Balanced Web Service Keeps Restarting

### ISSUE THREAD

**Issue by rohit8** [aws/copilot-cli#1726]
Hi,
I'm trying to run Hasura, a GraphQL API with a password protected console, via a load balanced web service (Docker Image: hasura/graphql-engine:v1.3.3). 

It is able to deploy and give me a URL. I'm able to use the deployed web service for about 30 seconds. But then the URL returns a 503 status code. The service eventually comes back. After checking the svc logs, it just says that the container is gracefully shutting down.

I don't see this issue locally using docker-compose with the same image. 

Why could this be happening? Any tips on how to debug this?

**Comment by kohidave** [comment]
This usually happens because the Heath check is failing so ECS is restarting your tasks. By default ECS/Loadbalancer will ping the `/` path periodically and needs it to return a `200`. You can change the health check path https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-healthcheck

Update that and let me know if that helps fix your problem!

**Comment by rohit8** [comment]
That was it! I also found the error in the Service's Events tab in the AWS ECS Console:
`Health checks failed with these codes: [302]).`

Since the default route `/` was redirecting somewhere else, I changed the healthcheck URL in the manifest file to the redirect destination (`/console` for the Hasura service).

Thanks!
