### ISSUE TITLE
Getting Started example app init fails with ResourceNotReady

### ISSUE THREAD

**Issue by sbeam** [aws/copilot-cli#1767]
Following exactly the [Getting Started guide](https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/), copilot init fails with a ResourceNotReady:

```
copilot-test$ git clone https://github.com/aws-samples/aws-copilot-sample-service example
...
copilot-test$ cd example/
example [master|✔]❯❯❯ copilot init
Welcome to the Copilot CLI! We're going to walk you through some questions
to help you get set up with an application on ECS. An application is a collection of
containerized services that operate together.

Application name: copilot-test
Workload type: Load Balanced Web Service
Service name: front-end
Dockerfile: ./Dockerfile
Ok great, we'll set up a Load Balanced Web Service named front-end in application copilot-test listening on port 80.

✘ Failed to create the infrastructure to manage services and jobs under application copilot-test.

✘ execute app init: wait until stack copilot-test-infrastructure-roles create is complete: ResourceNotReady: failed waiting for successful resource state
example [master|✔]❯❯❯ copilot --version
copilot version: v1.0.0
example [master|✔]❯❯❯ uname -v
Darwin Kernel Version 18.7.0: Fri Oct 30 12:37:06 PDT 2020; root:xnu-4903.278.44.0.2~1/RELEASE_X86_64
```

Logged-in AWS user has PowerUserAccess.

**Comment by kohidave** [comment]
Hi there! I'm so sorry you've run into this problem and that we don't have very good error messaging at the moment. 

This typically happens because the application name you're trying to use has already been used by another copilot app in the same account. 

If you try changing the app name (or omitting the app name from the command) - that should resolve this issue. 

Again - super sorry you've run into this! Let me know if you try the above advice and can get it going!

**Comment by sbeam** [comment]
hmm, I did try that with a fresh copy of the example repo, created a new directory (no existing `copilot` dir), re-downloaded copilot binary from github (not homebrew). Unfortunately exactly the same result. This is the first time using copilot and the account does not have any ECS clusters running.

```
example [master|✔]❯❯❯ copilot init
Welcome to the Copilot CLI! We're going to walk you through some questions
to help you get set up with an application on ECS. An application is a collection of
containerized services that operate together.

Application name: xyzzy
Workload type: Load Balanced Web Service
Service name: xyzzy-front-end
Dockerfile: ./Dockerfile
Ok great, we'll set up a Load Balanced Web Service named xyzzy-front-end in application xyzzy listening on port 80.

✘ Failed to create the infrastructure to manage services and jobs under application xyzzy.

✘ execute app init: wait until stack xyzzy-infrastructure-roles create is complete: ResourceNotReady: failed waiting for successful resource state
example [master|✔]❯❯❯ pwd
/Users/sbeam/tmp/xyzzy/example
```

**Comment by bvtujo** [comment]
Hey @sbeam, I'm sorry to send you log diving but could you look for the underlying CF error in the console for us? (We're working on a better story for making these failures transparent right now but this is the quickest way for the time being, so sorry)

If you head to CloudFormation -> Stacks -> `xyzzy-infrastructure-roles` -> Events, then scroll down the page until the earliest event with status `CREATE_FAILED`, you should find a "Status Reason" next to the Status column. Can you post that here? That will give us some insight into what exactly went wrong in your case. My suspicion is that it's a permissions issue but knowing the status reason will help us understand for sure.

**Comment by sbeam** [comment]
Ah, no problem, happy to look. I did not know where to find the logs. You are right, it's a permissions issue. I thought PowerUserAccess would give me enough but it seems not

```
API: iam:GetRole User: arn:aws:iam::033889051231:user/sbeam is not authorized to perform: iam:GetRole on resource: role xyzzy-adminrole
```

Now that I know how to debug I'll adjust until it works (not sure if the exact policy needed is documented?). Thanks for your help!

**Comment by kohidave** [comment]
Sweet! So glad that you got this working.

**Comment by bvtujo** [comment]
@sbeam https://github.com/aws/copilot-cli/issues/1345 is an issue we're tracking where some other customers have posted their minimal policies for creating an app.

**Comment by amarmashruwala** [comment]
Hi Guys, 
I am having a very similiar issue 

I was trying to deploy an application to ECS using copilot in the ap-southeast-1 region. i have previously deployed in ap-southeast-2 region and that is working.
When running copilot init or copilot app init i got the following error. What would this error be due to? thank you!
wait until stack chime-to-rtmp-infrastructure-roles create is complete: ResourceNotReady: failed waiting for successful resource state
It seems when i try to deploy in a different region i get this error. It works when deploying to ap-southeast-2.
Is this something to do with IAM permissions for a specific region, as i looked at the regions and they are enabled by default.
I had a look at cloudformation stack event log -
 AdministrationRole
CREATE_FAILED
chime-to-rtmp-adminrole already exists
not sure how to fix this.
