### ISSUE TITLE
How to you stop and/or restart a service?

### ISSUE THREAD

**Issue by pointtoken** [aws/copilot-cli#1800]
Loving copilot! 

Once a service is deployed, how does one stop and/or restart a service without full on deleting it? It isn't clear from the docs.

**Comment by efekarakus** [comment]
Hi @pointtoken !

To stop a service you can change the [`count`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#count) in the `manifest.yml` file to `count: 0` and deploy your service again with `copilot deploy`.  
If you'd like to restart a service, I believe you can run `copilot deploy --tag <restart tag>` by providing your own tag it should push the same container image to the ECR repository and trigger a new deployment that's identical.

**Comment by MasaGon** [comment]
I think that like `copilot svc restart` or `copilot svc redeploy` command is convenient to me if it exists. The same behaviour as `aws ecs update-service --force-new-deployment` would be perfect.

**Comment by iamhopaul123** [comment]
Hello @MasaGon. Have you tried [`svc deploy --force`](https://aws.github.io/copilot-cli/docs/commands/svc-deploy/)? It would allow you to do exactly the same thing as `--force-new-deployment` would do.

**Comment by rinogo** [comment]
(First off, forgive me - I'm new to copilot and Fargate, so I don't have the nomenclature down yet)

Hey, all! @MasaGon recommended `svc deploy --force`. This seems to ultimately have the desired effect, but it seems heavy-handed.

Using this command, it looks like copilot runs a full "deploy" operation - the container is pushed to Amazon again, an infrastructure proposal is made, etc.

What is preventing copilot from having a command to just start a new container to replace the existing one? I'm assuming that's the infrastructure proposal and update steps, right?

I'm primarily concerned because 1) I'm sometimes on mobile and uploading our container again takes a lot of time and bandwidth and 2) if there is a bug in production that "restarting" the container would fix, it would be ideal to minimize the number of steps required to have a fresh container available.

Is there a technical reason why copilot can't provide such a behavior? Or, is it simply a matter of implementing it?

**Perhaps a more valuable question in the short term - is there a way to perform an action like this directly in the AWS console?** (For an edge case like this, I think it's fine to perform the action manually in the console)

**Comment by JICA98** [comment]
I have a suggestion, Can't we just stop the task associated with copilot service? Since by doing this, it will automatically start the desired no. of tasks. 
In my case, the desired task count was `1`, so after stopping the task, it was started automatically. This was faster than re-deploying the service forcefully.
I used this command `aws ecs stop-task --cluster <cluster-arn> --task <task-id>`
to stop the task which I got from [here](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ecs/stop-task.html).
There is apparantly a timeout of 30 seconds which can be configured. It can also be done through the aws console. Please tell me if this was the right way of doing it or not.

**Comment by iamhopaul123** [comment]
Hello @JICA98. Your suggestion totally makes sense to me and it is a right approach if downtime is acceptable. However, `--force` is helpful when you don't want to experience any downtime for your services.

**Comment by JICA98** [comment]
Hey @iamhopaul123, thanks for the clarifcation. I didn't really consider the downtime back then, thanks for pointing it out.
