### ISSUE TITLE
`env upgrade --all` may cause pipeline builds to fail

### ISSUE THREAD

**Issue by huanjani** [aws/copilot-cli#1805]
We currently have the command `env upgrade --all` in the buildspec.
This may prevent the pipeline build stage from reaching completion if the user does not add all app envs as pipeline stages.

A possible solution may be doing something like:
```
...
for env in $envs; do
  ./copilot-linux env upgrade -n $env
...
```

**Comment by anish-dcruz** [comment]
We are facing this issue right now. 
The build is failing as its try to upgrade prod env which doesnt exisit.
We tried the for loop and still got error.
Thanks.

**Comment by huanjani** [comment]
Hi @anish-dcruz! 

So sorry about this. For now,  a workaround is to change `./copilot-linux env upgrade --all` in the buildspec to `./copilot-linux env upgrade -n name-of-env-in-pipeline`. Let me know how that works!

**Comment by efekarakus** [comment]
+1 to @huanjani 's recommendation, for another way to mitigate you can also remove that line from the buildspec, commit and push it and that should get the pipeline unblocked.   
Until we provide a fix for it, you can run the command `copilot env upgrade --all` whenever a new version of Copilot is released so that the latest templates are always synced to your environments. Apologies for the inconvenience 🙇

**Comment by huanjani** [comment]
@anish-dcruz: We now have a fix for our buildspec forthcoming. Thanks for your feedback!

**Comment by tsingh2k15** [comment]
I am noticing a potentially related issue on `copilot version: v1.11.0`.  Somehow `copilot svc deploy` triggers `execute "env upgrade --app some-app--name some-name"` which then fails with error - `get template summary: AccessDenied: User: arn:aws:sts::accountnum:assumed-role/some-role/some-DI is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::some-account:role/somename-EnvManagerRole`. Any thoughts?
