### ISSUE TITLE
Recommendation on internet access for private subnet

### ISSUE THREAD

**Issue by bpottier** [aws/copilot-cli#1889]
I have a couple load balanced services deployed and I want to have one of them talk to an RDS instance. I've put the RDS instance in one of the private subnets created by copilot. 

We use direct connect with a transit gateway for accessing resources in private subnets. That all works fine. But I noticed that the private subnets have no NAT Gateway. Is this because I don't yet have any backend services deployed or is this a design choice? Am I able to add a NAT Gateway to the route table without fear of it getting removed?

What is the best approach here?

**Comment by efekarakus** [comment]
Heya @bpottier, for now all service types (Backend and Load Balanced Web Services) are launched into public subnets. See @kohidave's answer for our reasoning for not creating NATGateways by default:
https://github.com/aws/copilot-cli/issues/1489#issuecomment-706590834

We're planning to add support to launch your tasks in private subnets in the future. It should be fine to add a NAT Gateway to the route table without fear of having it removed, I can't think of a scenario where we would remove it. The one issue might be when you want to delete your environment. In that situation `env delete` will fail because of the NAT gateway, and you'll have to manually remove it before trying the command again.

If you'd like to completely own the networking resources on your end, you can also create an environment where you import an existing VPC when running `copilot env init`

**Comment by efekarakus** [comment]
Hi @bpottier ! With Copilot v1.5.0 we do have the option now to create NAT Gateways in your subnets: https://github.com/aws/copilot-cli/releases/tag/v1.5.0 🚀 Resolving the issue :)
