### ISSUE TITLE
Too slow?

### ISSUE THREAD

**Issue by thepandaguitar** [aws/copilot-cli#1948]
Hi all,

First time Copilot user. I am seeing deployment times of > 16 minutes and counting - I had to interrupt the service.

- What should I expect in terms of deployment times? 
- Is this expected of first deployments only, i.e does it get faster on subsequent deployments?
- Perhaps a problem with my setup?

FYI - My AWS test account is bare-bones, and my test of Copilot consisted of just an html file on nginx:alpine as follows:

<img width="1390" alt="setup" src="https://user-images.githubusercontent.com/3105613/108613214-34079b80-7433-11eb-91bd-323dc60dcd64.png">

**Comment by kohidave** [comment]
Howdy! Yea - the first deployment takes much longer than subsequent deployments because it's provisioning all the infrastructure for your service and environment. Typically the ALB, KMS key, and the VPC take the longest time to set up - but after the first deployment, the only change is to the actual service. 

Hope that helps clear things up! Your next deployment will be way faster. 🙏

**Comment by thepandaguitar** [comment]
Hi @kohidave and thank you very much for the quick response. 

Please correct me if I am wrong - does this mean that Copilot is not suitable for creating many apps on demand?

I have given it another chance and tried running the [Github example](https://github.com/aws/copilot-cli#getting-started-), unfortunately even after waiting for a long time, it fails while some `[create in progress]` keep going on forever.

<img width="957" alt="commands" src="https://user-images.githubusercontent.com/3105613/108615333-4b9c4f80-7446-11eb-94fc-933f5f7313fc.png">

<img width="1313" alt="Screen Shot 2021-02-21 at 13 08 13" src="https://user-images.githubusercontent.com/3105613/108615343-5ce55c00-7446-11eb-8be3-515a79800fdd.png">

As stated above, this is a new AWS account without any existing configuration.

Thank you for helping out.

**Comment by kohidave** [comment]
Hi hi! So the organization is one app has many services so if you add new services, deployments to those services (and deployments to subsequent services) will be fast. 

The reason your current stack is failing is because your container is failing to start - I'm not sure why but you can try check running `copilot svc logs` to see if there are any errors in the logs.

**Comment by thepandaguitar** [comment]
@kohidave  - could this be related to the fact that I am running the CLI on Apple M1?

<img width="914" alt="Screen Shot 2021-02-21 at 20 39 52" src="https://user-images.githubusercontent.com/3105613/108623935-1b27d600-7485-11eb-8ca5-492d583b3ef7.png">

**Comment by kohidave** [comment]
That's right. The image was built for the ARM architecture but Fargate is an x86 architecture. We're working on forcing x86 architecture builds but for now you can try a few things:

1. Adding a platform to the `from` in your dockerfule https://docs.docker.com/engine/reference/builder/#from
2. Build and push the image yourself https://jaimyn.com.au/how-to-build-multi-architecture-docker-images-on-an-m1-mac/
3. Set up a Copilot pipeline (`copilot pipeline init`) and copilot will build your image in CodeBuild which is x86

I'm really sorry about this - it's not a great experience :(

**Comment by efekarakus** [comment]
Hi folks, I'll close this issue in favor of #1949. We'll track support to make the UX better for M1 machines there.
