### ISSUE TITLE
Support Private Registries for images

### ISSUE THREAD

**Issue by kohidave** [aws/copilot-cli#2101]
Right now, customers who are using the `location` field in the manifest have no way to specify credentials. This forces them to use a workaround that involves storing images in ECR.

We should support the image `credential field` in the container definition. 

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/private-auth.html

It'd be nice if we could also just prompt you for the secrets.

**Comment by huanjani** [comment]
Related: #2061

**Comment by kohidave** [comment]
Related: https://stackoverflow.com/questions/66803450/authenticate-aws-copilot-app-with-private-docker-hub-repo

**Comment by efekarakus** [comment]
Related https://github.com/aws/copilot-cli/issues/1177#issuecomment-819095801

**Comment by galer7** [comment]
Does anyone know where I can find (or how I can create) the credentials ARN value for this [field](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#image-credential)?

Context: A private ECR was created for my ECS service after running the `copilot init` command. I've uploaded the image to this private ECR (since the `build: path/to/Dockerfile` was taking too long, but I already had the image built locally).

```
image:
  location: <private_ecr_url>/<copilot_app_name>/<service_name>:latest
  credentials: <???>
```
