### ISSUE TITLE
Secrets Manager Secrets support or update on documentation

### ISSUE THREAD

**Issue by yannickvr** [aws/copilot-cli#2132]
As a user, i want to use the `secrets` property to inject environment variables into the task from AWS Secrets Manager. The documentation only mentions the use of the Systems Manager Parameter store, while ECS/Fargate supports Secrets Manager, as well as the task execution policy that is created for the service.

Ideally, specific keys in a secret can be used. I found out by trial and error that the current syntax is the following:

`secrets:`
`     VARIABLENAME: "'arn:aws:secretsmanager:region:accountid:secret:secretname:keyname::'"`

Note the double and single quotes that need to be used. Should this be documented as such or properly handled by copilot?

**Comment by iamhopaul123** [comment]
Hello @yannickvr. Thank you for finding out this workaround. The reason why we didn't put it on our website is because we were planning to provide a better experience for supporting Secret Manager (see https://github.com/aws/copilot-cli/issues/1920). You could give an thumb-up to the issue so as to help us prioritize the feature. Thank you!

**Comment by efekarakus** [comment]
Hi ! 

This feature is implemented and now pending release. You'll be able to refer to secretsmanager secrets by name like this:
```
secrets:
   VARIABLE_NAME:
       secretsmanager: 'secretname'
```
See #2898

**Comment by huanjani** [comment]
Hi all!
AWS Copilot v1.15.0 is now released with this feature! https://github.com/aws/copilot-cli/releases/tag/v1.15.0 🎉🚀
