### ISSUE TITLE
Can't upgrade environment with newest copilot

### ISSUE THREAD

**Issue by sekamaneka** [aws/copilot-cli#2133]
Copilot version old: 1.2.0
Copilot version new: 1.4.0
Environment version old: 1.1.0
Environment version new: 1.2.0

Export `<app>-<env>-ServiceDiscoveryNamespaceID" cannot be updated as it is in use by "<app>-<env>-<svc>`

Is there any option to solve this besides reinstalling everything?

**Comment by efekarakus** [comment]
Hi @swilso793 ! This is very strange 🤔 it shouldn't need to update it in the first place `ServiceDiscoveryNamespaceID` should be kept the same between 1.1.0 and 1.2.0.

While tackling https://github.com/aws/copilot-cli/issues/1929 did you update the CFN stack template so that the value:
```
         Name: !Sub ${AppName}.local 
```
is  now?
```
         Name: !Sub ${Env}.${AppName}.local 
```

If so I think that might be the root cause, where copilot is trying to change it back to `Name: !Sub ${AppName}.local`.

-------
Mmm this is super tricky :/ The only thing that I can think of is managing the namespace outside of copilot so that copilot doesn't try to override it

**Comment by sekamaneka** [comment]
Hey. Yeah you are right. I didn't even think of that. I will have to patch copilot again. Thank you

**Comment by sekamaneka** [comment]
It worked after patching the 1.3 template. Thanks for your help!
