### ISSUE TITLE
How to pass in AWS credentials for docker build?

### ISSUE THREAD

**Issue by gtamas** [aws/copilot-cli#2155]
My service needs AWS CLI because we use CodeArtifact as private NPM registry and I need to login.

```
aws codeartifact login --tool npm --repository some --domain some.com --region some-region
npm install
```

However, this command required AWS credentials. How can I use this with copilot?

I know I can use the "secrets" and the "variables" sections for such things, but those are used at runtime. I need AWS credentials at build time. How can I solve this?

**Comment by iamhopaul123** [comment]
Hello @gtamas. You can
1. try copying your AWS config and credential files to the dockerfile
2. build and push your image to either ECR or dockerhub. Then refer to that in `location` (https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-location) in your manifest.
3. set `args` in the manifest file (https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build):
``` yaml
args:
  AWS_DEFAULT_REGION: 'us-west-2'
  AWS_ACCESS_KEY_ID: '<copy>'
  AWS_SECRET_ACCESS_KEY: '<copy>'
```
and have in the Dockerfile:
```
ARG AWS_DEFAULT_REGION 
ARG AWS_ACCESS_KEY_ID 
ARG AWS_SECRET_ACCESS_KEY 
```
But you will need to delete these `args` in the manifest afterwards so that it doesn't appear in your git history :)

**Comment by RobinVds** [comment]
I'm facing the same problem but then for a private NPM registry that needs an authentication token. 
@iamhopaul123 Are there maybe plans to include this in the future? I'm a bit surprised not more people need secrets at build time.

**Comment by zackdotcomputer** [comment]
Presumably if you do 1, you will also wind up with your credentials in your git history.

For AWS credentials for Docker build, I think [this PR](https://github.com/aws/copilot-cli/pull/2582) might now solve the issue.
