### ISSUE TITLE
Confusing mismatch between ECS defaults and copilot default for bind mount read_only

### ISSUE THREAD

**Issue by miketheman** [aws/copilot-cli#2213]
Hello! I was trying to share a non-persistent storage volume between two containers today for the purpose of UNIX socket communication, which requires both sides to be able to read and write to the socket.

Being aware of the ECS default of `readOnly: false` ([reference](https://docs.aws.amazon.com/AmazonECS/latest/userguide/bind-mounts.html#specify-volume-config)) I had figure out why things weren't working the way I was expecting them to.

I found the copilot documentation describing the defaults in [storage](https://aws.github.io/copilot-cli/docs/developing/storage/#manifest-syntax) and [sidecars](https://aws.github.io/copilot-cli/docs/developing/sidecars/#general-sidecars), I was able to resolve, but was curious to understand the choice of diverging from the ECS defaults here?

**Comment by bvtujo** [comment]
We diverged here because initially, we only enabled the use of EFS volumes. Empty bind mounts are a later addition. 

For EFS, we deemed it safer to default to `readOnly: true` when mounting your externally managed filesystem. This would be a way of forcing you to take a positive action to allow write-level access to your EFS filesystem to avoid data loss from a buggy container.

I agree it doesn't make a lot of sense for empty scratch volumes, however, and I appreciate you surfacing this confusion!

**Comment by miketheman** [comment]
Thanks, bot, for reminding us that this never saw conclusion.

Unless there was something done as a result?

**Comment by iamhopaul123** [comment]
Hello @miketheman sorry for the confusion that the bot was trying to close the issue automatically. Like Austin had explained before, we set the default value because empty bind mounts are a later addition and we can't really change our default value as it'll be a breaking change. At this stage we can't really make default value consistent with ECS's default. Do you have any recommendation?

**Comment by miketheman** [comment]
@iamhopaul123 The issue was pointing out the confusing, undocumented difference in behaviors.
From the timeline, this https://github.com/aws/copilot-cli/pull/2234 was added a couple of days after Austin responded, and I never knew until now.

It would have been awesome to link these two together, so I would have known that the documentationw as updated swiftly, and we could have closed this two years ago 😆
