### ISSUE TITLE
Runtime Nodejs10 deprecated

### ISSUE THREAD

**Issue by mebibou** [aws/copilot-cli#2235]
Today I received an email from AWS warning me that some of my lambda functions were not going to work anymore after April 30, 2021. Checking my lambdas, the only ones using NodeJs 10 are all created by copilot

Would it be possible to use NodeJS 12 by default? these are:
- the `RulePriorityFunction` functions
- the `EnableLongARNFormatFunction` functions

**Comment by tnijboer** [comment]
Node.js 14.x seems the recommended version

**Comment by efekarakus** [comment]
Hi folks, we just merged a fix to upgrade the runtimes to `nodejs12.x`, we couldn't upgrade yet to 14.x because the [`ZipFile` attribute is not yet supported by Lambda with nodejs14.x](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/80#issuecomment-777194191).

The fix should be out soon part of Copilot v1.6. No action items are needed from your end, the next time you run `copilot deploy` the functions will automatically upgrade to use nodejs12.

>  some of my lambda functions were not going to work anymore after April 30, 2021. 

Just to clarify the existing Lambda functions would still work: https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html but doing an update or creating a new function wouldn't (when we create new environments for example).
