### ISSUE TITLE
Where/when are SSM parameters created?

### ISSUE THREAD

**Issue by mikelhamer** [aws/copilot-cli#2280]
I have been doing some experimenting with copilot to see how it handles stacks being manually deleted. I noticed that when I manually delete all of the stacks that `copilot init` and `copilot deploy` create, the SSM parameters still exist. After manaully deleting the stacks `copilot app delete` fails, so the SSM parameters are left hanging. The only way I found to get rid of the parameters using copilot at this point was to `copilot init` the app again and then `copilot app delete` again.

So I am wondering, where/when are these SSM parameters actually created and deleted? I'm guessing it's not done through the CF stacks.

Bonus question: Are there any other "hidden" resources `copilot init` creates that require `copilot app delete` to clean up?

**Comment by efekarakus** [comment]
Hi @mikelhamer!

Your experimentation is exactly right, Copilot stores metadata about your application in SSM parameter store. They are created outside of CloudFormation when running the init commands (`copilot app init`, `copilot env init`, `copilot svc init`), and then deleted with the respective delete commands. They are used so that you can run data commands (like `copilot svc status`, `copilot app show`) outside of your repository. Essentially the SSM parameters are Copilot resources, and everything else is resources for your application and is managed through CloudFormation.  
There are no other resources created with Copilot outside of CloudFormation.

**Comment by mikelhamer** [comment]
Thanks for the explanation!
