### ISSUE TITLE
How to migrate resources created with the old copilot version

### ISSUE THREAD

**Issue by rhoboro** [aws/copilot-cli#2364]
I am running an application and pipeline that I created with copilot-1.0.0.
I need to upgrade the Node.js version of lambda from v10 to v12, how do I do that?
I couldn't find any documentation on migration and found this issue #2235 , but I'm not using copilot deploy because I don't do manual operations.

copilot is a great tool and I want to use it in the future.  It would be nice to have some documentation for migration.

**Comment by efekarakus** [comment]
Hi @rhoboro !

Sorry this is not well documented 🙇 We need to update your `buildspec.yml` so that you can migrate your Lambda runtimes to nodejsv12.
1. Can you download the latest version of copilot
2. Back up the old buildspec just in case `mv copilot/buildspec.yml copilot/buildspec.bkup.yml`
3. Run  `copilot pipeline init` again, this will only create a new `buildspec.yml` file and skip updating the `pipeline.yml` file.
4. Delete the backup `rm copilot/buildspec.bkup.yml`
5. Commit and push the changes: `git add copilot/buildspec.yml && git commit -m "update buildspec to v1.7.0" && git push`

The pipeline should be able to now update your Lambda functions to Nodejsv12

**Comment by rhoboro** [comment]
@efekarakus 
Thank you for the quick reply.
The steps you wrote worked well for me!!
Thanks to you, I can continue to use copilot  in the future 😄 

I would appreciate it if you could document this procedure, or you can close this issue.

**Comment by h5aaimtron** [comment]
@efekarakus it seems these steps don't necessarily work on all the resources generated. In my case, the CertificateValidationFunction, CustomDomainFunction, and DNSDelegationFunction were not upgraded to the latest node version. All other functions were successfully upgraded.

**Comment by iamhopaul123** [comment]
Hello @h5aaimtron. Those custom resources are in the environment stack. Are you using pipeline for environment deployment? If not you can update Copilot CLI to the latest version and then do `env deploy` to deploy the environment again.
