### ISSUE TITLE
construct DB URLs from DB Secrets

### ISSUE THREAD

**Issue by nhajratw** [aws/copilot-cli#2483]
When trying to deploy a [hydra](https://www.ory.sh/hydra/docs/configure-deploy/) service, you need to specify the DSN environment variable like so:

    DSN=postgres://<username>:<password>@<hostname>:<port>/<dbname>?sslmode=disable

All of those values are in the `XXXX_SECRET` environment variable as a JSON string. However, there is no good way to use that to construct the DSN above in the manifest file.

Current workaround is:
* spin up a dummy service
* use secrets manager to get the credentials
* save the credentials in the desired DSN format using `copilot secret init`
* add secret DSN to manifest
* change manifest to point to *real* service

**Comment by bvtujo** [comment]
possibly related: #1992

This is a really annoying bootstrapping problem you're running into! We might be able to mitigate some of the recurring deployment issues by implementing the environment interpolation above (this would mesh nicely with CI/CD to keep the DSN up to date if the password ever changes), for instance, but the bootstrapping process will require some careful thought and design to get right.

**Comment by iamhopaul123** [comment]
Hello friends! We have a proposal for supporting manifest env vars in #2912. Feel free to check it out and leave your thought on it. Appreciate for your input on this features 🙇

**Comment by efekarakus** [comment]
Hi all! The feature is now out: https://github.com/aws/copilot-cli/releases/tag/v1.12.0 🥳

To learn more: https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/

**Comment by vdods** [comment]
Is it possible to do a string interpolation within the manifest file using two secrets values?  For example, constructing the string `postgres://<db-username>:<db-password>@<db-host>/<db-name>` from four separate values DB_USERNAME, DB_PASSWORD, DB_HOST, DB_NAME, from the secrets store?  Because the secrets are referred to by path, and there is this colon-based subvalue querying syntax, it's not clear what the syntax to do this would be.

**Comment by efekarakus** [comment]
@vdods that's a really cool idea 🤔 

I think fundamentally today the underling infrastructure (ECS task def) doesn't allow constructing an env var value from interpolated strings. I've relayed your feedback to the product team at ECS.

**Comment by hirokihokari** [comment]
@efekarakus You said "The feature is now out", but the referenced pages seem to show no solution to this original post. Or maybe the OP meant something else?

Sure, I can expand the environment variable, which is great, but the aurora credentials are still provided in `<cluster name>CLUSTER_SECRET` all in **json format** when `init storage -t aurora`.

I could modify my source code to accomodation to parse like suggested on CLI output:
```
const {username, host, dbname, password, port} = JSON.parse(process.env.<cluster name>CLUSTER_SECRET)
```

But this way, my code bepends on copilot. I'd like to avoid that for interoperability. 
My code expects env vars `DB_HOST` and `DB_PASSWORD` and such, and I'd like to keep it that way.

Am I reading this wrong? Is there a proper way already out?

<Edit 1>
I've discovered 2 things:
1. `<cluster name>CLUSTER_SECRET` is not available in manifest.
2. If I run deploy once, aurora instanciates(?) and put credentials in secret manager

2 is a great news, but it requires me to go and get the secret name since the secret name includes a random suffix, which is far better than changing the source code, but not the best

**Comment by waveozhangli** [comment]
hi @vdods have your problem solved? I got the similar requirement and did not find related information in the doc
I have tried:
 "${DB_PASSWORD}", got error message `DB_PASSWORD not defined`
 "${/path/to/my/parameter/store/key}", it is not replaced

hi @efekarakus you mentioned that you have relayed the feedback to the product team at ECS, can you please let us know is there any related updated? 

Thank you very much!

**Comment by vdods** [comment]
@waveozhangli No, I had done the string interpolation of the two env vars in my program, and hadn't revisited this issue, sorry.

**Comment by efekarakus** [comment]
Hii @waveozhangli !

Sadly, there is no workaround yet 😢 the only method that I can think that won't affect the application code is possibly modifying the [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint)
of the container image by first parsing the `XXXX_SECRET` environment variable and then passing down the parsed environment variables (username, password, host, ...)  to the application

**Comment by waveozhangli** [comment]
Thank you very much for your reply @vdods and @efekarakus 
For now, as a workaround, I just store the whole DB connection string into parameter store.
But I think entrypoint is a good idea, I will try it.
Thanks again for your help! 😄
