### ISSUE TITLE
allowed_source_ips not turning back on.

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#2539]
When initially deploying my service, I had allowed_source_ips setup and working. I commented out the line in the manifest while debugging other issues which worked fine. Now I want to turn it back on, but it doesn't seem to be applied during deployment. I'm doing all deployments via a copilot pipeline that works in all other instances of deployment needs.

**Comment by Lou1415926** [comment]
Hi @h5aaimtron !

Is your `allowed_source_ips` specified as an environment configuration in manifest? There was a bug in v1.8.0 that was later fixed in v1.8.1 last week. The bug prevented environment overrides to be applied in manifest. It existed for commands such as `svc package`, which is used by pipeline under the hood.

**Comment by h5aaimtron** [comment]
@Lou1415926 It's in the manifest, added under http section with the values being passed in an array [ ]. When I commit the change and let the pipeline run, nothing appears to change, but I recently updated my buildspec file with a reference to the latest copilot image (1.8.1).

**Comment by Lou1415926** [comment]
Have you pushed the code to remote? The pipeline picks up changes from your GitHub remote, including manifest changes.

**Comment by h5aaimtron** [comment]
@Lou1415926 yes as I have triggered the pipeline and everything works except the allowed_source_ips.

**Comment by Lou1415926** [comment]
I see! Thanks for the information!!

One quick question to help me locate the issue: are you using HTTPS?

**Comment by h5aaimtron** [comment]
@Lou1415926 Yes I am. I'm also doing https redirect on port 80.

**Comment by Lou1415926** [comment]
Gotcha!

Before v1.7.1, the `HTTPSListenerRule` doesn't enable `allowed_source_ips`. That'd mean when you are using https, even if you've specified `allowed_source_ips`, it won't get passed through the CFN template.

Meanwhile, I also found out that the generated buildspec downloads the copilot v1.6.0 by default (instead of the latest), which is a version before v1.7.1.

Here is something I did when I tried to reproduce the error:
1. I deployed a service via pipeline, without `allowed_source_ips`
2. Update the service's manifest to include `allowed_source_ips`, commit & push
Then pipeline picks up the changes and updates the template. When I was looking at the template from the CloudFormation console, I found that the source ips are only added to the `HTTPListenerRule`, but not `HTTPSListenerRule`.
3. Then I updated the buildspec by explicitly telling it to download v1.8.0, commit & push. 
```YAML
      # Download the copilot linux binary.
      - wget https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.8.2
      - mv ./copilot-linux-v1.8.2 ./copilot-linux
```
4. The source ips are then successfully enabled for both `HTTPListenrRule` and `HTTPSListenerRule` in the CFN template.

You've mentioned that you changed your buildspec to download the latest copilot. Could you try explicitly setting the version, if that's not how you did it?

**Comment by h5aaimtron** [comment]
Mine is pointing to copilot-linux-v1.8.1 but you're using 1.8.2 so maybe that's the issue?

**Comment by Lou1415926** [comment]
I tried v1.8.0 too, and it was fine.

Would you be able to check your CFN template? You can look for the resource named `HTTPSListenerRule`. Under the "Condition" field of that resource, is there a field that look like this?
```yaml
- Field: 'source-ip'
          SourceIpConfig:
            Values:
            - 10.24.34.0/23
```

**Comment by h5aaimtron** [comment]
Yeah the values are there under the HTTPSListenerRule in the CFN template. Under the HTTPS listener rules, the first rule is generic, but has the restricted IP addresses, but a 2nd rule (default rule) exists that doesn't have those restricted IPs and its also passing through to the same target group.

**Comment by h5aaimtron** [comment]
@Lou1415926 looking further into this, I may have caused this issue. I previously deployed with cli 1.8.0 but the buildpsec still referenced 1.4.x the other day. When I updated it, I was getting a 503 whether within the ip range or not, so I adjusted the default rule to point to the necessary target group. It turns out that at the time, the rule generated by copilot (older buildspec) was missing the proper target group and source ip restrictions. After I updated the buildspec it must have corrected the original rule, however; I had let the default rule pass through not realizing it. That all being said, is there a plan to better manage the buildspec files in the future? It's not clear that even though I updated the cli, I have to manually update the buildspec each time there's a new release as well.

**Comment by toshitanian** [comment]
I'm not sure it's related to this issue but `allowed_source_ips` is not applied to our service with version of `v1.8.2`. `copilot svc package` did not show the given IPs as well. The lines in the templates looks [here](https://github.com/aws/copilot-cli/blob/77983421537d9f34575655ab8cba309f30610f33/templates/workloads/services/lb-web/cf.yml#L313-L319).


Update:
I'm not sure why this working but adding `allowed_source_ips` to environment section worked.
```yaml
# Distribute traffic to your service.
http:
  path: '/'
  healthcheck:
    path: '/health'
  allowed_source_ips: ["x.x.x.x/32"]

# You can override any of the values defined above by environment.
environments:
  test:
    http:
      allowed_source_ips: ["x.x.x.x/32"]
```

**Comment by Lou1415926** [comment]
> @Lou1415926 looking further into this, I may have caused this issue. I previously deployed with cli 1.8.0 but the buildpsec still referenced 1.4.x the other day. When I updated it, I was getting a 503 whether within the ip range or not, so I adjusted the default rule to point to the necessary target group. It turns out that at the time, the rule generated by copilot (older buildspec) was missing the proper target group and source ip restrictions. After I updated the buildspec it must have corrected the original rule, however; I had let the default rule pass through not realizing it. 

@h5aaimtron Glad it's all figured out! Thanks for digging into this! Were you able to resolve the issue? 

> That all being said, is there a plan to better manage the buildspec files in the future? It's not clear that even though I updated the cli, I have to manually update the buildspec each time there's a new release as well.

This s a great find. Although we generate a buildspec that downloads the latest Copilot, we don’t retrospectively modify existing buildspec. 

We should figure out a way so that the buildspec always point to the latest binary, whether it exists before the update or not.

**Comment by Lou1415926** [comment]
> I'm not sure it's related to this issue but `allowed_source_ips` is not applied to our service with version of `v1.8.2`. `copilot svc package` did not show the given IPs as well. The lines in the templates looks [here](https://github.com/aws/copilot-cli/blob/77983421537d9f34575655ab8cba309f30610f33/templates/workloads/services/lb-web/cf.yml#L313-L319).
> 
> Update:
> I'm not sure why this working but adding `allowed_source_ips` to environment section worked.
> 
> ```yaml
> # Distribute traffic to your service.
> http:
>   path: '/'
>   healthcheck:
>     path: '/health'
>   allowed_source_ips: ["x.x.x.x/32"]
> 
> # You can override any of the values defined above by environment.
> environments:
>   test:
>     http:
>       allowed_source_ips: ["x.x.x.x/32"]
> ```

Hi @toshitanian! 

This is unrelated to the issue, but it indeed is a bug on our manifest. Thanks for reporting the issue, and I am sorry for the trouble it's caused you 🙇🏼‍♀️  Could you stick with your current workaround while we work on the fix? Thank you!!

**Comment by efekarakus** [comment]
> That all being said, is there a plan to better manage the buildspec files in the future? It's not clear that even though I updated the cli, I have to manually update the buildspec each time there's a new release as well.

Related https://github.com/aws/copilot-cli/issues/1583 
The plan for this is to have a separate `build` section in the pipeline manifest where under the hood we generate the  buildspec. This way we can always ship the latest version of the CLI part of the buildspec.  
However, we still need to think of a way of enforcing `pipeline update` so that the buildspec changes get picked up

**Comment by h5aaimtron** [comment]
@efekarakus My first impression upon installing a new cli version would be to run a copilot app upgrade type of command which I would think would read everything in the app and upgrade/update where necessary.

**Comment by iamhopaul123** [comment]
Hello @toshitanian this is now fixed in our [latest release](https://github.com/aws/copilot-cli/releases/tag/v1.8.3) 🎉

**Comment by toshitanian** [comment]
@iamhopaul123 Thanks!
