### ISSUE TITLE
copilot-windows-v1.10.0.exe  Error setting up load balancer

### ISSUE THREAD

**Issue by rolance** [aws/copilot-cli#2803]
While trying to set up load balancer:

X Failed to create the infrastructure to manage services and jobs under application my-app.  
X execute app init: read template app/app.yml: open templates\app\app.yml: file does not exist

**Comment by huanjani** [comment]
Hi @rolance! 

Sorry about that. We switched to Go 1.16 in Copilot v1.10; there was a change in Go 1.16's go:embed functionality that introduced this bug. We have a fix at the ready, but need to incorporate it. Are there features in v1.10 that you need immediately, or are you okay using v1.9 until we are able to merge that fix in?

Thanks and again, sorry for the inconvenience!

**Comment by rolance** [comment]
Thanks for the speedy reply. I am hoping to override a task definition to increase the nopage ulimit. My understanding is that v1.10 is the first version to include this ability, yes? It is not a make-or-break feature for any of my projects, but it is going to come in very handy.

**Comment by huanjani** [comment]
Yes, the task definition override feature came out in v1.10, unfortunately. I have reproduced your error and am seeing if I can figure out a workaround for you.... 🤞🏼

**Comment by huanjani** [comment]
Hi again. 

So...we'll have a fix out as soon as possible.

The issue is related to this: https://github.com/golang/go/issues/45230, where `filepath` is OS-specific (and separates paths appropriately), but `go:embed` uses a forward slash, even for Windows. 
So https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/template.go#L241 could be changed to `dat, err := t.fs.ReadFile(filepath.ToSlash(filepath.Join("templates", path)))` to get around this new limitation.

Hope that helps! Thanks for using Copilot and for trying out the new task definition override feature!

**Comment by huanjani** [comment]
@rolance, the fix has been merged into the mainline branch of this repo, but won't be released immediately; in the meantime, you could pull the latest commit and build the binary locally! Hope this helps.

**Comment by efekarakus** [comment]
Hi  @rolance! The fix is now out with a patch release: https://github.com/aws/copilot-cli/releases/tag/v1.10.1 apologies for the delay 🙇
