### ISSUE TITLE
If initial deploy fails, log group deleted, so can't inspect why deploy failed

### ISSUE THREAD

**Issue by zackdotcomputer** [aws/copilot-cli#2811]
I'm trying to deploy a service to a new environment.

`copilot deploy --env newenv`

The deploy is hanging at service create, and then eventually fails with `Error occurred during operation 'ECS Deployment Circuit Breaker was triggered'`.

This triggers a rollback, however since it is the initial deploy to the environment the rollback cleans up many of the resources created in the CloudFormation stack. Most critically, I assume, it deletes the `LogGroup` resource, meaning that I cannot view the logs for the attempted deploy to debug why the deploy is failing.

**Comment by zackdotcomputer** [comment]
I didn't run into this with my previous `env` because I started by deploying a "hello world" docker there. That allowed there to be a valid-ish fallback state that the CloudFormation could revert to without destroying all resources. Possibly this is what needs to be done with copilot - the equivalent of a basic hello-world should get deployed when the service is first initialized so that reversions of the user's custom code don't cause all the resources and associated debugging information to be destroyed.

**Comment by toricls** [comment]
Disabling CloudFormation's automatic rollback and preserving successfully provisioned (or failed) resources is now supported in CloudFormation.
refs: https://aws.amazon.com/about-aws/whats-new/2021/08/aws-cloudformation-troubleshoot-errors/

I think this is the best timing to support that feature in Copilot to make debugging easy especially for initial deployment. Cc: @efekarakus

**Comment by efekarakus** [comment]
That make sense! 

We should consider a similar flag to the cdk cli for consistency: `copilot deploy --no-rollback` (https://github.com/aws/aws-cdk/pull/16293)

**Comment by matthewford** [comment]
Is there any updates with this? We have an app crashing which is running fine locally and within ECS using another tool, however with co-pilot it's crashing and we can't check the logs to see the issue.

**Comment by Lou1415926** [comment]
Hello @matthewford !

Sorry for the inconvenience!  We’d like to support this feature and make the debugging process easier for initial deployment! We will update this issue to let you know when it’s in the design phase.

For the time being, if your log is being deleted because your service is failing at the initial deployment - one workaround would be to first deploy a vanilla hello-world app, such that the service has a successful initial deployment. After this, you can deploy your original code. If the second deployment fails, it will rollback to the last successful deployment instead of deleting all resources, which preserves the logs. 

If your app is running fine otherwise, it is also possible that some resources, other than your ECS instance, fail to create for some reason. If you don’t mind sharing the error message that Copilot gives you, or the streaming report logs that you see during `copilot svc deploy`, feel free to do so!

**Comment by efekarakus** [comment]
Hi folks! The feature is now released https://github.com/aws/copilot-cli/releases/tag/v1.16.0 🥳  with `--no-rollback`

See announcement: https://aws.github.io/copilot-cli/blogs/release-v116/
