### ISSUE TITLE
[Request] "Worker Service" without SQS queues

### ISSUE THREAD

**Issue by toshitanian** [aws/copilot-cli#2853]
I understand that current "Worker Service" is designed for SQS queue integration. In my use case, my app is a worker service that do polling to other external API and do not need the SQS queues. There's no big issue even if a SQS queue is created, but it's easy to manage for us if extra resources are not created.
https://aws.github.io/copilot-cli/docs/concepts/services/#worker-service

So, I propose that add option to the manifest that disable making SQS queue.

**Comment by efekarakus** [comment]
Hi @toshitanian ! Would the [backend service](https://aws.github.io/copilot-cli/docs/concepts/services/#backend-service) pattern solve your usecase?

It will create an ECS on Fargate service but without the SQS queue

**Comment by toshitanian** [comment]
@efekarakus Thank you for your information!
I've thought that the backend service is for http service inside the VPC. Does it work without http interface on it?
I guess it makes internal ALB in the process of building the backend service.

**Comment by efekarakus** [comment]
@toshitanian 

>  I've thought that the backend service is for http service inside the VPC. Does it work without http interface on it?

Yes! 😄  the [`port` field](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#image-port) is completely optional for backend services. 
If omitted from the `manifest.yml` file then the service won't be accessible over the network. Otherwise, Copilot will make the service accessible via [service discovery](https://aws.github.io/copilot-cli/docs/developing/service-discovery/).

**Comment by toshitanian** [comment]
@efekarakus Thank you for the kind explanation!
That seems to fit to my use case! Will use the backend service for my worker service 👍
