### ISSUE TITLE
Failed to deploy 1st svc with ECS Deployment Circuit Breaker was triggered error

### ISSUE THREAD

**Issue by dang-hoang-hieu** [aws/copilot-cli#2874]
Hello, I am new to copilot
I used this demo https://github.com/aws-containers/ecsdemo-frontend
to deploy for the 1st time but it kept failing with 
```
- An IAM Role for the Fargate agent to make AWS API calls on your behalf           [delete complete]    [0.0s]
  - A CloudWatch log group to hold your service logs                                 [delete complete]    [0.0s]
  - An ECS service to run and maintain your tasks in the environment cluster         [delete complete]    [88.4s]
    Resource handler returned message: "Error occurred during operation 'E
    CS Deployment Circuit Breaker was triggered'." (RequestToken: 3363df6b
    -208e-6840-ccc7-2c5f745b9468, HandlerErrorCode: GeneralServiceExceptio
    n)
    Deployments
               Revision  Rollout   Desired  Running  Failed  Pending
      PRIMARY  7         [failed]  1        0        10      1
```

How can I debug this?
I also tried to use the image hello-world from docker official but same problem

thank you!

**Comment by huanjani** [comment]
Hello, @dang-hoang-hieu! 

I'm so sorry your deployment is failing. Do you happen to be on an M1 Mac?

**Comment by dang-hoang-hieu** [comment]
@huanjani hello, no, I am using Macbook pro 2020 ver 11.5.2

**Comment by huanjani** [comment]
Thanks, @dang-hoang-hieu. 
I tried to replicate your error but couldn't-- the deployment succeeded. 
Did you change anything in your generated workload manifest? 
Hmm...can we maybe try increasing the timeout value of your healthcheck?

**Comment by iamhopaul123** [comment]
Hello @dang-hoang-hieu. I wonder if you created the service with the name to be `ecsdemo-frontend`, since otherwise the additional [task role](https://github.com/aws-containers/ecsdemo-frontend/blob/main/copilot/ecsdemo-frontend/addons/task-role.yaml) can't be applied.

**Comment by dang-hoang-hieu** [comment]
@huanjani hello, I only changed the manifest to use the built image of ecsdemo-frontend (I built it so that if copilot failed, it doesnt have to build image again). I will try increasing timeout!
thank you

@iamhopaul123 hello, I used other name!

btw, do you guys have ways to debug or check logs? I tried to print logs while the copilot do the initial deploy but no log streams... 😭 
If no more info I think I have to try k8s LOL even though the learning curve of k8s is huge

**Comment by iamhopaul123** [comment]
Hello @dang-hoang-hieu. The reason is because this particular example requires specific task role defined [here](https://github.com/aws-containers/ecsdemo-frontend/blob/main/copilot/ecsdemo-frontend/addons/task-role.yaml) to run (task role is the role that your task will have. in this example it allows the task to describe subnets). And any role that's exported in your [addons](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/) will be [injected to your task role automatically by Copilot](https://github.com/aws-containers/ecsdemo-frontend/blob/main/copilot/ecsdemo-frontend/addons/task-role.yaml#L27-L30).

By default if your service does not have the name to be `ecsdemo-frontend`, Copilot creates a different workspace to store the service manifest. For example, if your service is named as `frontend` then the manifest will be placed in `ecsdemo-frontend/copilot/frontend` rather than `ecsdemo-frontend/copilot/ecsdemo-frontend`, and the addons with additional task role will not be picked up, unless you copy the addons file and paste it under `ecsdemo-frontend/copilot/frontend/addons/task-role.yaml`.

Hopefully you can get your first application work by using a different service name or move the addons file to the right place! Also feel free to check this [example](https://aws.github.io/copilot-cli/docs/getting-started/first-app-tutorial/) on our website as a ramp-up project that requires minimum configuration. Please let me know if you have any issue!
