### ISSUE TITLE
Unable to deploy existing or new jobs

### ISSUE THREAD

**Issue by slaughtr** [aws/copilot-cli#2880]
We have two scheduled jobs deployed to our environments (staging, production) via copilot - `JobA` and `JobB`. As of sometime last week, we are unable to deploy `JobB` due to the following error:

```
The push refers to repository [1234567890.dkr.ecr.us-west-2.amazonaws.com/our-app/JobB]
1fc38fed3e67: Preparing
....more preparing/waiting....
3e207b409db3: Waiting
b6eb9fce359e: Pushed
1fc38fed3e67: Pushed
6be4f4658087: Pushed
03edd48566ad: Pushed
9b9f23013122: Pushed
2d7b189be53f: Layer already exists
ca45630a0e49: Layer already exists
b2b222e5b623: Layer already exists
6f9d3d2bf332: Pushed
3e207b409db3: Layer already exists
4ae80a939a2a: Pushed
5a54ff35e4df: Pushed
d9c889a: digest: sha256:786d57e6e86e0374d26c1ae901ced96eca1ba6d9a968eab0fd63b9953f9e3fbc size: 2841
latest: digest: sha256:ffd8b2b9ad52d7c444eb8a63dd859df17976990c75feb8110bf9aaf2f56f756a size: 2842
✘ ECR repository not found for service JobB in region us-west-2 and account 12346567890
```

Images appeared to still be pushed/show up in the ECR UI, though many were `<untagged>`. 

Amongst attempts to debug this issue, the job was deleted via `copilot job delete`, and now re-init via `copilot job init` fails when using a cron expression of any kind. Trying to provide a cron expression results in:

```
⠋ Creating ECR repositories for JobB
✘ Failed to create ECR repositories for job JobB.

✘ add job JobB to application our-app: adding job JobB resources to application our-app: operation 25 for stack set our-app-infrastructure failed
```

However, using a fixed schedule allows the job to init, so we went with that to get our job re-deployed. When running `copilot job deploy` for the job, we again get `ECR repository not found for service JobB in region us-west-2 and account 1234567890`. Manually creating the ECR repository and trying `copilot job deploy` again results in the same error, however a new image `latest` does appear in ECR. Subsequent commands continue to fail with `ECR repository not found` and no new images appear in ECR.

Interestingly, `JobA` has had no issues. It was created a considerable time and several versions before `JobB`.

This all happens from a variety of developer machines and via CI systems, so does not appear to be related to any specific environment/architecture/dependencies. We have tried init/deploy combos with and without existing `manifest.yml` files and related directories, and found that any new job is giving us these errors, not specifically `JobB`.

Any and all advice or troubleshooting steps appreciated!

**Comment by huanjani** [comment]
Hi @slaughtr! 

Thanks for the detailed explanation. Let me dig into this. In the meantime, which version of Copilot are you using?

**Comment by slaughtr** [comment]
```
❯ copilot --version
copilot version: v1.10.1
```

@huanjani It's safe to assume this is the same version on all tested machines/systems as well.

**Comment by huanjani** [comment]
@slaughtr, if you go to the CloudFormation console's Events tab for that stack, can you get any more information? 
Or if you go to the StackSet and look at operation 25, what does it show?
(screen shots of what you're looking for in the console: https://github.com/aws/copilot-cli/issues/2863#issuecomment-925079988)

Could this be related to an IAM permissions change that is affecting CloudWatch or StepFunctions/StateMachine?

I tried to replicate what you're experiencing, but my job is deploying normally. 🤔

**Comment by slaughtr** [comment]
Interestingly it doesn't seem that any of these changes have caused any events for the stack. This smells like a clue to me... And the StackSet just says `FAILED` with no other information.

We haven't (intentionally) changed any IAM permissions, however I did dig through CloudTrail and all IAM "changes" for this job and related resources (presumably from deploying the app) resulted in no diff.

**Comment by huanjani** [comment]
Is JobA also on a cron schedule? And you can redeploy it with something like `copilot job deploy --name JobA` no problem?

**Comment by iamhopaul123** [comment]
Hello @slaughtr. Besides @huanjani's questions, I have some questions for triaging as well:

> Interestingly, JobA has had no issues. It was created a considerable time and several versions before JobB.

1. I assume JobA and JobB are in the same application. Are they in the same root repository locally or they have different `/copilot` folder for their manifests?
2. Do they get deployed to the same region?

**Comment by slaughtr** [comment]
> Is JobA also on a cron schedule? And you can redeploy it with something like `copilot job deploy --name JobA` no problem?

Yes to both here. JobA has had no issues deploying whatsoever. 



> Hello @slaughtr. Besides @huanjani's questions, I have some questions for triaging as well:
> 
> > Interestingly, JobA has had no issues. It was created a considerable time and several versions before JobB.
> 
> 1. I assume JobA and JobB are in the same application. Are they in the same root repository locally or they have different `/copilot` folder for their manifests?
> 2. Do they get deployed to the same region?

1. Yes, same application. Both in the same copilot dir, though under their own respective directorires/manifests:

```
copilot
├── ContainerA
│   ├── addons
│   │   └── cognitoPolicy.yml
│   └── manifest.yml
├── JobA
│   └── manifest.yml
├── JobB
    └── manifest.yml
```

2. Yes - both to `us-west-2` in both production and staging environments.

Edit: unasked, but maybe relevant - both JobA and JobB use the same Dockerfile as their base image.

**Comment by iamhopaul123** [comment]
@slaughtr That seems strange to me! Could you please go to the CFN stackset template and see if it is in version `v1.0.2` and i guess only `JobA` appears in the metadata service field?

Also if one stackset operation failed, you could see more detail if you go to the CFN console for stack -> look at the event for `StackSet-our-app-infrastructure-xxxx`

**Comment by slaughtr** [comment]
It is indeed version 1.0.2 - `TemplateVersion: 'v1.0.2'`

I do see `JobB` listed, though that's from attempts to deploy yesterday. Creating and deleting a `JobC` (which fails exactly like `JobB`) does make it appear/disappear from the template as expected. The configuration for `JobA` and `JobB` in the template is effectively the same, the only changes are differences in names.

I don't see anything out of the ordinary in the events tab, even after re-init'ing and attempting to deploy a job and having that fail. 

**That got me to notice, though, that the stack that is failing - called out above as `our-app-infrastructure` - does not actually exist.** We have many many things in Cloudformation and _do_ have a `our-app-infrastructure-roles` and I guess I glossed over that a bit.

```
✘ Failed to delete resources of job JobC from application our-app.
✘ removing JobC job resources from application: operation 28 for stack set our-app-infrastructure failed
❯ aws-vault exec production -- aws cloudformation describe-stacks --stack-name our-app-infrastructure

An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id our-app-infrastructure does not exist

❯ aws-vault exec production -- aws cloudformation describe-stacks --stack-name our-app-production

# outputs as expected
```

**Comment by iamhopaul123** [comment]
OK so ideally should have both `our-app-infrastructure-roles` and `Stackset-our-app-infrastructure`. The latter one creates the ECR repo I think that's why when you deploy the job, it cannot find the repo. And it seems like the stackset itself is in a abnormal state that it is out of sync with its stackset instances. Could you try to delete the stack within the failing region from stackset and try to create and deploy the job again?

<img width="1108" alt="Screen Shot 2021-09-29 at 3 09 19 PM" src="https://user-images.githubusercontent.com/51377557/135355596-df7459cf-8084-4040-807a-eeabad0ff213.png">
<img width="820" alt="Screen Shot 2021-09-29 at 3 09 32 PM" src="https://user-images.githubusercontent.com/51377557/135355598-6053e915-3798-4ad0-b4ab-2eb71c317274.png">

**Comment by slaughtr** [comment]
This is a single region deployment at the moment, that seems like a destructive change. Both staging and prod are managed via the prod account. 

What ramifications should I expect when deleting the stack? Apologies, I'm not incredibly experienced with CloudFormation.

**Comment by iamhopaul123** [comment]
Hello @slaughtr. I think I am able to reproduce this issue. I created an application with one environment in `us-west-1`, then manually deleted the stackset instance. After deletion, I tried to create a service and actually the service creation will trigger the stackset instance creation again, which seems to be fine.

Then I tried to put the stackset instance in the `delete failed` status. It seems to be in a weird state where you can't create a new service or deploy an existing service to any environment in that region. This is expected since stackset can't do anything if one of the stack instance is in a `delete failed` status.

Could you look at the CFN console to check for the stackset instance status? That should tell you the current status for all of your stackset instance as below:
<img width="979" alt="Screen Shot 2021-09-29 at 5 19 10 PM" src="https://user-images.githubusercontent.com/51377557/135366077-bbb27c25-3279-488b-91f6-65adad3d2dbf.png">

To get your application recovered without causing any destructive outcome. I cleaned the pipeline bucket (which caused the manual stackset instance deletion failed) then deleted the broken stackset instance completely. After that, the service/job init should be able to get the stackset instance recovered.

Sorry again for the churn you'd experienced and please let me know if this helps!

**Comment by slaughtr** [comment]
@iamhopaul123 we will test this in the morning and report back. Thank you very much for the detailed response!

**Comment by jtwyble** [comment]
@iamhopaul123 can you elaborate on what we need to do to get the stackset instance recovered. @slaughtr and i have removed the problematic stackset instance but are little bit lost on steps to get it recreated without accidently creating a whole bunch of new copilot resources.

![image](https://user-images.githubusercontent.com/990663/135670138-c99f4899-a092-4912-b262-196e6a13366e.png)

We see this trying to init/deploy a service

✘ upload custom resources to bucket stackset-x-x-x : upload scripts/dns-cert-validator: upload scripts/dns-cert-validator/fb4f90fff4e5606cded32d9d512a8bc5ccec8097a2bbb41e6da145c67f2e9495 to bucket stackset-x-x-x : NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: H87KFB1SVADHJ1AC, host id: yrVU2IWquciXLtro/NeiR2owY3URmXNXSKK53N/qMOW4+gB3FSxzRkepmtmK6BK+tXiBBtOcY5Q=

**Comment by iamhopaul123** [comment]
Hello @jtwyble. Sorry for the confusion. After removing the problematic stackset instance that failed to get deleted before, can you try to run `job delete` to delete the job that failed to deploy as well and then `job init` again to create the job? Alternatively you can create a new job/service as well. Once you see the stackset gets created successfully again, and the jobs are written to the stackset template, `job deploy` should work.

Under the hood, the ultimate goal after deleting the problematic stackset instance is just to trigger an operation to recover the instance. However, the job that failed to deploy still exist in the stackset template, so if you do `job init` again to create that job there might not be any operation for the stackset, since there would be no changes to the stackset template.

Overall I think we could do a better job on diagnosing problems and helping users to recover their apps when some stacks are unexpectedly removed or damaged.

**Comment by slaughtr** [comment]
We were able to recover everything, though it required some manual intervention with Cloudformation. Our pipelines did fail for a moment due to `no changes` though after some local init/deploy we got everything going.

Thank you very much for the help. I would definitely agree on the diagnosis comment :)
