### ISSUE TITLE
Getting Started example fails in codepipeline CodeBuild step with la -lah ./infrastructure exit status 2

### ISSUE THREAD

**Issue by mark-brooks-roostify** [aws/copilot-cli#2943]
Here's the error from the tail of my Build log:

```

[Container] 2021/10/22 16:10:23 Running command ls -lah ./infrastructure
--
879 | ls: cannot access ./infrastructure: No such file or directory
880 |  
881 | [Container] 2021/10/22 16:10:23 Command did not exit successfully ls -lah ./infrastructure exit status 2
882 | [Container] 2021/10/22 16:10:23 Phase complete: POST_BUILD State: FAILED
883 | [Container] 2021/10/22 16:10:23 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ls -lah ./infrastructure. Reason: exit status 2
884 | [Container] 2021/10/22 16:10:23 Expanding base directory path: .
885 | [Container] 2021/10/22 16:10:23 Assembling file list
886 | [Container] 2021/10/22 16:10:23 Expanding .
887 | [Container] 2021/10/22 16:10:23 Expanding file paths for base directory .
888 | [Container] 2021/10/22 16:10:23 Assembling file list
889 | [Container] 2021/10/22 16:10:23 Expanding infrastructure/*
890 | [Container] 2021/10/22 16:10:23 Phase complete: UPLOAD_ARTIFACTS State: FAILED
891 | [Container] 2021/10/22 16:10:23 Phase context status code: CLIENT_ERROR Message: no matching artifact paths found

```

I'm following this [demo](https://aws.amazon.com/blogs/containers/enabling-continuous-workflows-for-aws-app-runner-service-with-persistency-using-aws-copilot-cli/)

**Comment by mark-brooks-roostify** [comment]
Here's some additional, earlier log output:

```
[Container] 2021/10/22 16:10:20 Phase complete: BUILD State: SUCCEEDED
830 | [Container] 2021/10/22 16:10:20 Phase context status code:  Message:
831 | [Container] 2021/10/22 16:10:20 Entering phase POST_BUILD
832 | [Container] 2021/10/22 16:10:20 Running command ls -l
833 | total 38712
834 | -rwxrwxr-x 1 root root     3158 Oct 22 15:47 CONTRIBUTING.md
835 | -rwxrwxr-x 1 root root      814 Oct 22 15:47 Dockerfile
836 | -rwxrwxr-x 1 root root      926 Oct 22 15:47 LICENSE
837 | -rwxrwxr-x 1 root root    25609 Oct 22 15:47 README.md
838 | drwxr-xr-x 2 root root     4096 Oct 22 16:10 components
839 | drwxr-xr-x 2 root root     4096 Oct 22 16:10 copilot
840 | -rwxr-xr-x 1 root root 39452672 Oct  4 15:17 copilot-linux
841 | drwxr-xr-x 2 root root     4096 Oct 22 16:10 docs
842 | drwxr-xr-x 2 root root     4096 Oct 22 16:10 lib
843 | -rwxrwxr-x 1 root root   108744 Oct 22 15:47 package-lock.json
844 | -rwxrwxr-x 1 root root      794 Oct 22 15:47 package.json
845 | drwxr-xr-x 4 root root     4096 Oct 22 16:10 pages
846 | drwxr-xr-x 3 root root     4096 Oct 22 16:10 public
847 | drwxr-xr-x 2 root root     4096 Oct 22 16:10 seed
848 | drwxr-xr-x 2 root root     4096 Oct 22 16:10 styles
849 |  
850 | [Container] 2021/10/22 16:10:20 Running command export COLOR="false"
851 |  
852 | [Container] 2021/10/22 16:10:20 Running command pipeline=$(cat $CODEBUILD_SRC_DIR/copilot/pipeline.yml \| ruby -ryaml -rjson -e 'puts JSON.pretty_generate(YAML.load(ARGF))')
853 |  
854 | [Container] 2021/10/22 16:10:22 Running command pl_envs=$(echo $pipeline \| jq '.stages[].name' \| sed 's/"//g')
855 |  
856 | [Container] 2021/10/22 16:10:22 Running command for pl_env in $pl_envs; do ./copilot-linux env upgrade -n $pl_env; done;
857 |  
858 | Environment test is already on the latest version v1.6.1, skip upgrade.
859 |  
860 | [Container] 2021/10/22 16:10:23 Running command svcs=$(./copilot-linux svc ls --local --json \| jq '.services[].name' \| sed 's/"//g')
861 | jq: error (at <stdin>:1): Cannot iterate over null (null)
862 |  
863 | [Container] 2021/10/22 16:10:23 Running command jobs=$(./copilot-linux job ls --local --json \| jq '.jobs[].name' \| sed 's/"//g')
864 | jq: error (at <stdin>:1): Cannot iterate over null (null)
865 |  
866 | [Container] 2021/10/22 16:10:23 Running command tag=$(sed 's/:/-/g' <<<"$CODEBUILD_BUILD_ID" \| rev \| cut -c 1-128 \| rev)
867 |  
868 | [Container] 2021/10/22 16:10:23 Running command for env in $pl_envs; do
869 | for svc in $svcs; do
870 | ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag;
871 | done;
872 | for job in $jobs; do
873 | ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag;
874 | done;
875 | done;
```

**Comment by iamhopaul123** [comment]
Hey @mark-brooks-roostify. It seems like it is because it doesn't have any local workloads (services/jobs) or environments in your pipeline. Since Copilot does require you to put an environment when creating the manifest file (unless all environment are manually removed from the pipeline manifest file), **most likely it could be the fact that Copilot can't detect any workload locally** (aka no `copilot/` or no workload manifest under `copilot/`).

For better triaging the issue, is it possible for you to provide us the source of your pipeline (like the GitHub repo you are using for the pipeline) if it is public? It could be possible that you didn't push the created workload manifest files to the remote.

However, I do agree we might need to have a better error message than this (https://github.com/aws/copilot-cli/issues/2944). Thank you for reporting this issue!

**Comment by mark-brooks-roostify** [comment]
@iamhopaul123 Adding the local ./copilot/svc directory seemed to fix the problem, but that wasn't referenced in the demo instructions.

The source of the pipeline is a fork of the default, per the demo instructions.  It is located here: https://github.com/mark-brooks-roostify/hello-app-runner-nodejs.git

**Comment by iamhopaul123** [comment]
Hey @mark-brooks-roostify glad the problem got fixed!

> but that wasn't referenced in the demo instructions.

Sorry about that! I'll contact the author to see if it can get updated. Thanks again for reporting the issue.

**Comment by mark-brooks-roostify** [comment]
Now I'm seeing this after updating the javascript code:

![Screen Shot 2021-10-22 at 2 37 03 PM](https://user-images.githubusercontent.com/52720844/138506205-b60d77a2-39ad-4658-ae80-52354db4689b.png)

Odd.  Admittedly this is a different error, but I can't understand why it would have lost the ability to contact the DynamoDB URL.

**Comment by kevinjruffe** [comment]
I wasn't following the same example as @mark-brooks-roostify, but I was experiencing his same error while trying to get my own pipelines set up. Eventually I came across this in the documentation: https://aws.github.io/copilot-cli/docs/commands/svc-package/. Running `copilot svc package --env <MY_ENV_NAME> --name <MY_SVC_NAME> --output-dir ./infrastructure` built the needed files. I could then merge into my main branch and have the pipeline complete a deployment as expected.

Hopefully this comment helps a person or two running into the same issue.

**Comment by toricls** [comment]
@mark-brooks-roostify Thanks for letting us know! The pipeline error you saw is actually an expected behavior in the demo app scenario (because the first pipeline execution doesn't have the `copilot` directory as @iamhopaul123 pointed out above).
So the pipeline must turns to green once you finished the final step `4. Try “push-to-deploy”`. It pushes all the required files including the `copilot` directory to your Git repository and now the pipeline can see the files within its build stage.

Regarding the second error you've seen "Error: getaddrinfo", I'm still not sure why that would happened but I think it can be resolved by just redeploying the App Runner service.
