### ISSUE TITLE
Service minimum health percentage always get reset

### ISSUE THREAD

**Issue by bradiksventures** [aws/copilot-cli#2958]
I set my service's `minimum health percentage` to 50% but it always get reset when I deploy. Is there an undocumented manifest property to change this behavior or is this intended?

**Comment by huanjani** [comment]
Hi @bradiksventures! I saw your question over on Gitter, so I replied there, just fyi. Thanks!

**Comment by huanjani** [comment]
Hello again, @bradiksventures. 

Sorry to keep popping back and forth between here and Gitter, but I think you are more likely to see this two-months-elapsed reply here.

As it turns out, the minimum and maximum percent values are irrelevant when using Fargate (as Copilot does). "If the tasks in the service use the Fargate launch type, the minimum healthy percent value is not used, although it is returned when describing your service." (See https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html.) Hopefully this behavior is improved in the future! 

Thanks!
