### ISSUE TITLE
Storage init - Regular RDS Addon

### ISSUE THREAD

**Issue by ErickGHo** [aws/copilot-cli#2984]
Aurora Serverless V1 use cases include: [Development & Test Databases, and infrequently used databases.](https://aws.amazon.com/rds/aurora/serverless/)

Can we get native support for regular RDS addon for Storage?

**Comment by Lou1415926** [comment]
Hello @ErickGHo !

Thanks for the feature request! 

You are looking for databases that are suitable for your production need, is my understanding correct?

Would you mind telling us if there's a specific type of RDS storage that you are looking for? Would the provisioned-[Aurora](https://aws.amazon.com/rds/aurora/?aurora-whats-new.sort-by=item.additionalFields.postDateTime&aurora-whats-new.sort-order=desc) (i.e. not the Serverless one) work for you?

Just in case you haven't found this - Although the other storage options are not supported by `copilot storage init` yet, you can still [create your own addon](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/) and deploy it with your services through `copilot svc deploy`.

**Comment by ErickGHo** [comment]
Aurora or normal RDS are both fine options. Aurora Serverless V1 doesn't seem to fit a lot of workloads in today's architecture, but future is looking bright for V2. Was there specific reason why Aurora serverless was the native option and is there any room to add the provisioned version / normal rds into copilot storage init?

**Comment by Lou1415926** [comment]
Thank you very much for your feedback!

> Was there specific reason why Aurora serverless was the native option

Aurora serverless has on-demand autoscaling and requires less operations/maintenance on users end comparing to the other options. This is beneficial for users that wants a more of a hands-off experience. In addition, we were expecting databases with spotty usage to be a more popular use case. This includes use cases where there's extended periods of time where the database could be scaled to zero with autoscaling, which user wouldn't have to pay for. The idea is that we want to provide native support for the databases that are the easiest to operate with, while making it totally possible for users to integrate with the other options - e.g. the provisioned Aurora, normal RDS - using addons. Meanwhile, we are also looking forward to v2 and will see how we could integrate that as well once it's available.

At this moment, there is no immediate plan to add the provisioned / normal RDS into `storage init`. However, we are looking to provide an example addon template for some of the other RDS options in the form of GitHub gist, so that we can better support more users. Please stay tuned!

**Comment by ErickGHo** [comment]
How can we contribute to the RDS template addons?

**Comment by Lou1415926** [comment]
Just to clarify, you'd like to share your addon template, is that right? If so, then this [show-and-tell discussion category](https://github.com/aws/copilot-cli/discussions/categories/show-and-tell) is a great place to do so. You could open up a discussion [here](https://github.com/aws/copilot-cli/discussions/new?category=show-and-tell).

**Comment by huanjani** [comment]
Aurora Serverless v2 by default is now released in v1.23.0: https://github.com/aws/copilot-cli/releases/tag/v1.23.0! 🎉
