### ISSUE TITLE
Desired count = 0 / Auto-Scale to 0

### ISSUE THREAD

**Issue by sve-odoo** [aws/copilot-cli#3054]
I have a very small load-balanced service.

I would like it to scale from 0 to 1, ie it should be running only when someone is trying to access it, in order to avoid paying when nobody is using it.

I have tried the following:

`
count:
  range:
    min: 0
    max: 1
  cpu_percentage: 70
`

But the desired count remains 1.

How to set the desired count to 0, in order to have a service that is "offline" by default, just like we have with serverless lambda functions ( called only when an event occurs, like an API Gateway call )

I don't mind cold starts.

**Comment by efekarakus** [comment]
Hi @sve-odoo !

> How to set the desired count to 0, in order to have a service that is "offline" by default, just like we have with serverless lambda functions ( called only when an event occurs, like an API Gateway call )

I believe the count remains at 1 with `cpu_percentage` because of:
> If you want your task count to scale to zero when there is no work to be done, set a minimum capacity of 0. With target tracking scaling policies, **when actual capacity is 0 and the metric indicates that there is workload demand, Service Auto Scaling waits for one data point to be sent before scaling out.** In this case, it scales out by the minimum possible amount as a starting point and then resumes scaling based on the actual running task count. 
> https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-autoscaling-stepscaling.html

Since the CPU is always above 0 %, then auto scaling retains the 1 task.

I've changed the configuration like this and I can see that scaling down to zero happens successfully:
```yaml
count:
  range: 0-1
  requests: 100
```

> I don't mind cold starts.

However, container cold starts are significantly longer than Lambda. If that's still okay for you, then the config above should work. Otherwise, there are few other alternatives:
1. Leveraging **Fargate Spot**, this will ensure that your test environment always has low cost:
   ```yaml
   count:
      spot: 1
   ```
2. Alternatively, have you considered [AWS App Runner](https://aws.amazon.com/apprunner/)? In Copilot, you can create them by running `copilot svc init` and choosing a ["Request-Driven Web Service"](https://aws.github.io/copilot-cli/docs/manifest/rd-web-service/) type. 
  The cool thing with app runner is that you can always run `copilot svc pause` and `copilot svc resume` to quickly spin up and down your service. However, today there are some limitations like not being able to connect to a VPC. I know that the team is working actively towards closing that gap.

**Comment by sve-odoo** [comment]
Many thanks for your help.

I've tried the configuration and my cluster does scale down to zero. However it doesn't scale back up when I do send requests. Am I doing something wrong? :)

Regarding App Runner, it could be a solution but I'm waiting for VPC support indeed.

**Comment by efekarakus** [comment]
🙈 you're right it won't scale up because the `RequestCountPerTarget` never gets any data points as there is no target (0 tasks) where requests get forwarded to.

I was hoping that ALB would populate this metric when a request comes in but it makes sense why it wouldn't. Unfortunately, there isn't a way that I can think of that will make it scale back up to 1 task 😥 
In this situation, I think our best bet would be fargate spot for now that can have up to 70% cost savings. The App Runner VPC feature got moved to "coming soon" earlier today: https://github.com/aws/apprunner-roadmap/issues/1#issuecomment-974261150 so stay tuned!

**Comment by efekarakus** [comment]
For anyone else stumbling onto this issue: scale to zero works fine with [Worker Services](https://aws.github.io/copilot-cli/docs/manifest/worker-service/) 🚀 

Here is an example manifest:
```yaml
type: Worker Service
count:
  range: 0-2 # Note that range starts at 0
  queue_delay:
    acceptable_latency: 1m
    msg_processing_time: 250ms
```

Once messages arrive to the SQS queue, it takes ~3mins for the ECS task to react and scale up to process messages.
Once the messages are all consumed and the SQS queue depth is back to 0, 15 mins later ECS tasks are stopped.
Here is a sample screenshot of CloudWatch metrics demonstrating the sequence of events:
![Screenshot 2023-03-03 at 10 06 04 AM](https://user-images.githubusercontent.com/879348/222796080-2a3ff54f-8c37-44a6-92e1-8ef58eb555f3.png)

**Comment by nandubatchu** [comment]
> 🙈 you're right it won't scale up because the `RequestCountPerTarget` never gets any data points as there is no target (0 tasks) where requests get forwarded to.
> 
> I was hoping that ALB would populate this metric when a request comes in but it makes sense why it wouldn't. Unfortunately, there isn't a way that I can think of that will make it scale back up to 1 task 😥 In this situation, I think our best bet would be fargate spot for now that can have up to 70% cost savings. The App Runner VPC feature got moved to "coming soon" earlier today: [aws/apprunner-roadmap#1 (comment)](https://github.com/aws/apprunner-roadmap/issues/1#issuecomment-974261150) so stay tuned!

Does this mean that we cannot set min as 0 for Load Balanced Web Services?
