### ISSUE TITLE
Override circuitbreaker retry count

### ISSUE THREAD

**Issue by chriskuech** [aws/copilot-cli#3061]
I'm trying to deploy my service for the first time and it's failing to startup correctly.  This issue takes a long time to troubleshoot because the deployment retries for 10 times.  I would like to set the retry count to 1 so that I can get the startup error quickly and let it immediately rollback, rather than wait half hour for the service to retry 10 times.

**Comment by efekarakus** [comment]
Hi @chriskuech !

Unfortunately circuit breaker's don't support yet a mechanism to update the number of failures, related containers-roadmap issue for ECS: https://github.com/aws/containers-roadmap/issues/1247

In the mean time, I believe when this happens you can go to the ECS console, update the service to have a desired count of 0 so that the deployment stops, and then you can run `copilot deploy` again after making the code changes

**Comment by efekarakus** [comment]
If you don't mind giving a 👍 to [aws/containers-roadmap#1247](https://github.com/aws/containers-roadmap/issues/1247)  that would help us prioritize features!

**Comment by chriskuech** [comment]
Thanks.  Would it be possible for copilot to have a `copilot svc cancel` command for canceling the deployment, implemented by setting the ECS desired count to 0 via SDK instead of console?

**Comment by efekarakus** [comment]
I think that makes sense! but it also feels somewhat of a bandaid fix 🤔, it'd be great if we could support your original proposal where copilot provides a way of configuring rollback details in the manifest file.

I'll close the issue for now, let me know if you'd like me to re-open it! Once ECS supports this functionality, we'll make sure to change our defaults and surface the config in the manifest file!
