### ISSUE TITLE
Does service discovery not work with React?

### ISSUE THREAD

**Issue by sirbully** [aws/copilot-cli#3076]
Hello! I tried creating a load-balanced service for a React app and then a backend service for an Express API. The React app errors out saying that it cannot resolve `http://api.{env}.{app}.local:3000`.

Is it not supposed to work with React?

**Comment by Lou1415926** [comment]
Hello @sirbully !

<strike>I believe service discovery should work with React! Would you mind giving me more context to help - for example, the error logs that you were seeing, the commands that you ran to deploy the services? Thank you!</strike>

Sorry @sirbully! It shouldn't work if the request to `http://api.{env}.{app}.local:3000` originates from the client side. The service discovery endpoint is only reachable within the VPC, whereas the client browser, where the request originates from isn't in the VPC. 

One alternative is to create a new LBWS that acts as a "apigateway" between your React app and the backend API. You can send HTTP requests from the React app to the new LBWS, which will then distribute the requests to the backend API, and send whatever response it receives back to the client. [Here](https://microservices.io/patterns/apigateway.html) is a reading about this sort of pattern that you may find helpful!

For example, with Copilot, you can create a new LBWS named `apigateway`. If your application is already associated with a domain, you could take advantage of [`alias`](https://aws.github.io/copilot-cli/docs/developing/domain/) to use a custom domain such as `apigateway.domain.com` for the service. After that, your React app can send request to `apigateway.domain.com`, instead of `http://api.{env}.{app}.local:3000`. This way, you can keep your API as a backend service, and able to send server-side request to it.

Let me know if this helps!

**Comment by sirbully** [comment]
Thanks for this! And for suggesting the pattern! I'm closing the thread since this is the perfect answer ✨
