### ISSUE TITLE
Working with Scheduled Jobs

### ISSUE THREAD

**Issue by dmathewwws** [aws/copilot-cli#3077]
Hey, 

Adding a cron job to my project and discovered the Scheduled Jobs service 👌🏾.

I had 1 question:
Is the idea of this service that it runs until the timeout ends? Just wanted to make sure I understood that, because that would mean I would have to know approximately how long the task would need to run for.

And 1 suggestion:
Instead of having a different task for every cronjob, I was thinking of having one cronjobs task, and my suggestion to have a way for me to know which job is being run. (FYI: The reason for wanting one cronjobs task for all my cronjobs is because I have made the architectural decision that all my code for my cronjob is in the same repo. so for my use case, it would be easier for me, when I make changes to my code to only have to deploy those changes to this task once and have all my cronjob tasks have the update code)

for instance
```
on:
  schedule: "@daily"
  schedule: "@daily"
```

could become
```
on:
  schedule: "@daily", name: "generate-report-1"
  schedule: "@daily", name: "generate-report-2"
```  

Thanks!

Danny

**Comment by Lou1415926** [comment]
Hello @dmathewwws !

> Is the idea of this service that it runs until the timeout ends? Just wanted to make sure I understood that, because that would mean I would have to know approximately how long the task would need to run for.

Your understanding is partially correct! The `timeout` field specifies the maximum duration that the execution can run. So if it runs longer than the specified time, the execution will fail. 

 However it is an optional field. You could leave it blank so that there is no cap on how long your job can run.

> And 1 suggestion:

To help me understand your use case better...
- Are you currently using pipeline to deploy your code changes?
- If so, are you using a single pipeline for these jobs?
- Is this similar to your current situation:

1. I have two jobs, namely  `generate-report-1` and `generate-report-2`. They share the same code (maybe partially).
2. I make some code changes to the shared code. 
3. I run  `copilot job deploy --name generate-report-1` and `copilot job deploy --name generate-report-2` to update those two jobs individually, so that both picks up the updated code.

Whereas ideally, you'd like to only run `copilot job deploy` (once, instead of twice), and then both `generate-report-1` and `generate-report-2` should have the updated shared code.

Please let me know if this is right!

**Comment by dmathewwws** [comment]
hey @Lou1415926.

for 1) I have two jobs, namely generate-report-1 and generate-report-2. They share the same code (maybe partially).

Yes. I guess the big picture I was trying to get at is instead of having a new manifest file for each cronjob, If I thinking of having one manifest file for all my cronjobs, but I would then have to know when which cronjob it was supposed to run I could write code to deal run the appropriate function.

And I am not using pipelines for this, I am using a pipeline for my backend server service.

**Comment by Lou1415926** [comment]
Thanks for the elaboration!

Sorry I am not sure I completely follow 🙇🏼‍♀️! Does this mean `generate-report-1` and `generate-report-2` would be using the same image, built from the same code? Is the only difference the `schedule` frequency they need to be triggered by? 

---
I noticed that our documentation is not explaining Scheduled Job well enough. Therefore, there could also be some misunderstanding of the concept 🙇🏼‍♀️  I am putting the following also for future reference - 

Different from a service, a scheduled job's task is expected to be one-off, instead of long running.

When you deploy a scheduled job, Copilot creates a task definition, as well as an event rule. Periodically - say once every week - an ECS task is kicked off, using that task definition. This is a one-off ECS task that will stop and clean up after it finishes running.

Next week, a brand new ECS task will be kicked off. This is not the same ECS task that was running in the last week.

If you have two jobs, `generate-report-1` and `generate-report-2`, they will each have their own task definition. Daily (given your example), two ECS tasks will be kicked off. One is an ECS task using `generate-report-1`'s task definition, the other is using `generate-report-2`'s task definition.

You shouldn't need to determine which function to run, because `generate-report-1` and `generate-report-2` are not handle in the same task.

**Comment by dmathewwws** [comment]
that make sense. thanks for the clarification.

I was trying to get all my cronjobs inside one manifest file, but having them all in separate files works too.

**Comment by rickychew77** [comment]
hi @Lou1415926, it's been a old thread but wanted to understand that after i did `copilot job deploy`, in my aws console i do not see it under `Scheduled tasks` tab, however the job indeed kicks in based on the cron i set.

My manifest was generated when i do `copilot job init`, unsure if this is intended way of doing.

**Comment by Lou1415926** [comment]
@rickychew77 It seems that only tasks managed by [EventBridge Scheduler](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-scheduler-schedule.html) show up in this tab. The scheduled jobs in Copilot were implemented using [EventBridge Rule](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-rules.html) - likely why they are not showing up on ECS console.
