### ISSUE TITLE
Upgrading from v.1.12 to v1.13 removes any public subnets defined in the env exports

### ISSUE THREAD

**Issue by brogers-propstream** [aws/copilot-cli#3085]
After upgrading from v1.12 to v.1.13 I was left with a broken environment and could not deploy without destroying it and recreating it. 

Breakage was due to the Public Subnets export being removed when being upgraded.

Resolution for me was to tear it all down and recreate the environment with the proper imports. However, this solution isn't sustainable.

**Comment by Lou1415926** [comment]
Hi @brogers-propstream. I am so sorry that this happened to you and that you had to go through so much churn. 

I am actively working on identifying the cause and am trying to reproduce the experience that you've encountered. 

May I ask if you are importing public subnets when you created the environment?

Thank you very much for reporting this issue!

**Comment by brogers-propstream** [comment]
Yes, I import both public and private subnets.

Essentially we have a bunch of terraform generated infrastructure I want to use with Copilot. 

Something to add - when doing the default `env init` command I'm never prompted for public subnets, only private.

The only way to import public subnets is to specify it with `--import-public-subnets`.

**Comment by Lou1415926** [comment]
Thank you so much for your response! This is very helpful!

I'd like to share my thoughts so far:

Information on customized VPC resources (such as VPC ID, subnet IDs) are store in SSM parameter store, under the name `/copilot/applications/<app>/environments/<env>`.

When upgrading the environment template, Copilot reads from this SSM parameter and finds out its customized VPC configuration, including the subnet IDs. This information is then passed down to the stack.

My hunch is that Copilot somehow didn't capture the imported subnet IDs information in the SSM parameter. Therefore, when Copilot upgrades the environment, it doesn't know there was already imported subnets; in this case, it'll attempt to create default VPC and subnets.

This could be wrong - just to share my thoughts here and keep you updated! Meanwhile, I'm still investigating on the issue in order to reach a conclusion.

Thank you again for reporting the issue and providing the details!

**Comment by Lou1415926** [comment]
Hey thank you for your patience! A quick follow-up question - 

When you initially created the environment, do you remember by any chance that the environment stack was manually deleted, followed by another `copilot env init` using the same environment name again?

---
Here is some explanation of why I asked:

When `copilot env init` is run, two things happen:
1. It creates a new CloudFormation stack
2. It creates an SSM parameter that records information: environment name, custom configuration such as imported public subnets, etc.

`copilot env init` expects the environment to be newly created, and it does not perform update to the environment if invoked more than once. 

This means that if `copilot env init --name test` command is invoked twice - even with a different configuration at the second time, for example, imported public subnets  - only the first invocation counts. The second invocation will not update the stack, nor the SSM parameter.

If in between these two invocations, the environment stack is manually deleted, however - Copilot will create the stack, but it does not update the SSM parameter.

This introduces a discrepancy between the stack resource and the SSM parameter. The newly created stack uses the imported public subnet, but the SSM parameter doesn't have records for the customization. 

Since the SSM parameter doesn't have information recorded for the customized VPC, during environment upgrade, Copilot doesn't know that there has been a customization to the environment.

This is definitely an enhancement that needs to be made - for example, perhaps Copilot should error out when `copilot env init --name test` is invoked when `test` already exists in the SSM parameter. Otherwise, it confuses users when they see the second invocation going through, however without resources being updated.

---
Please let me know if this may be what's happened to your application. We definitely want to fix the issue that you've encountered!

Thank you very much!
