### ISSUE TITLE
Deploy --force is not working when auto scaling set. 

### ISSUE THREAD

**Issue by kaworu1112** [aws/copilot-cli#3092]
Hi,

We had set the location in manifest to pull from the static image url (with the latest tag), eg. repo.example/staging/helloworld:latest
While we use the manifest without auto scaling, copilot svc deploy --force it work perfectly.
After that we try to add auto scaling eg.
 
environments:
  staging:
    http:
      api : api.example.com
    count:
      range:
        min: 2
        max: 3
        spot_from: 2
      cpu_percentage: 50

copilot svc deploy --force will be deploy successfully at the first time, but the second time it wont recreate the tasks.

This is the old manifest.yml
environments:
  staging:
    http:
      api : api.example.com

Thanks for you assistance.

**Comment by Lou1415926** [comment]
Hi @kaworu1112 ! Thank you very much for reporting this issue.

This seems like a bug to me. We will work on a fix as soon as possible!

For now, would you be able to work around it, for example, by using different tags during each deployment? This could be made less painful by taking advantage of [manifest interpretation](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/#shell-environment-variables). This way you could just run `copilot svc deploy` without the force flag, since the tag is changing.

Thank you!

**Comment by Lou1415926** [comment]
## Summary of the bug

Previously, in CloudFormation the `DesiredCount` is always required. This doesn't cause issues for Copilot when autoscaling is not enabled, because it could just use the exact count specified in manifest for this field. However, it becomes ambiguous what the `DesiredCount` should be when autoscaling is enabled.

Copilot's answer was this: the `DesiredCount` should be set to whatever the actual running count was at the time of deployment. This could minimize the disturbance to the number of running tasks in the service.

In order to know the actual running count, Copilot needed to invoke a lambda custom resource. Naturally, the lambda needed to get triggered at every single deployment when autoscaling is enabled. Therefore, the CloudFormation would always trigger an UPDATE. When a normal CloudFormation update could happen, a force update wouldn't get triggered.

This is essentially the bug that's reported by this issue. The lambda that calculates the desired count is always triggered when autoscaling is enabled, which prevented a force update to happen.

---
## Proposal

Nowadays, CloudFormation no longer requires `DesiredCount` per[ this document](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-desiredcount). 
> For new services, if a desired count is not specified, a default value of 1 is used. When using the DAEMON scheduling strategy, the desired count is not required.
> For existing services, if a desired count is not specified, it is omitted from the operation.

This means that we can remove the lambda now. However, we can't just leave `DesiredCount` field blank altogether.

This is because, as the document says, CloudFormation uses a default value of 1 for new services if it is left blank. However, starting with only one running task before autoscaling kicks in isn't necessarily a desired situation for customers. Therefore, Copilot still needs to give it a specific value at service creation.

So the proposal is:
1. Remove the lambda.
2. Before rendering the template, Copilot checks if the stack already exists (and not in a CREATE_FAILED state).
3. If it does, Copilot omits the DesiredCount field.
4. If it doesn't, the service is being first created. Copilot should use the min count as the `DesiredCount`.

If autoscaling is disabled, then Copilot will just use the exact count specified in manifest.

**Comment by kaworu1112** [comment]
Coool, thanks for your investigation. We use differenet tag as the workround your suggested.

**Comment by Lou1415926** [comment]
The fix is now released 🎉 in v1.14.0 https://github.com/aws/copilot-cli/releases/tag/v1.14.0 !
