### ISSUE TITLE
Discover my Public IP for whitelist purposes

### ISSUE THREAD

**Issue by doneumark** [aws/copilot-cli#3105]
Hey,
Im using a third-party service, that need to whitelist my IP for requests I send from my "Copilot Load Balanced Web Service".
For that, I need my IP to be static (would not change) and discoverable for me (aka - I don't know where to find it!).

How can I achieve that?

**Comment by iamhopaul123** [comment]
Hello @doneumark. <s>If you are using a load balanced web service, since all the traffics are emitted from the LB, you would need to whitelist the IP of the LB. To find out the IP of the LB, you would need to follow [this guideline](https://aws.amazon.com/premiumsupport/knowledge-center/elb-find-load-balancer-IP/)

TLDR: simply
```
aws elbv2 describe-load-balancers --names load-balancer-name
```
then the `load-balancer-id` is the last field of characters that follows the trailing slash after the load balancer's name in the ARN. For example, `arn:aws:elasticloadbalancing:us-west-2:xxxxxxxxxx:loadbalancer/app/demo-Publi-1JE4G2DZ1IW6Y/e6f5a0a514efa2e8` would be `e6f5a0a514efa2e8`.</s>

Actually, it has nothing to do with ALB. So if you place the task in public subnet, each task would get a different public IP address. In this scenario you would need to either manually look them up and add them whenever a new task is up, or through a script. I would recommend to specify [the placement in your manifest](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-placement) to be `private` like
```
network:
  vpc:
    placement: private
```
so as to place the tasks in private subnets. Then you'll have Elastic IPs (you could navigate them by Copilot tags) of the tasks for you to whitelist their requests.

Let me know if you have any other questions.

**Comment by doneumark** [comment]
thanks @iamhopaul123 !
Will adding this placement as private will have any other effects on my app?
Or will it add any difficulties for any other future things I would like the app to do in the future? (for example, maybe if I would like to to connect my tasks to any other 3rd party service)

**Comment by iamhopaul123** [comment]
> Will adding this placement as private will have any other effects on my app?

I don't think so but NAT gateway does cause some additional cost compared with internet gateway.

> Or will it add any difficulties for any other future things I would like the app to do in the future? (for example, maybe if I would like to to connect my tasks to any other 3rd party service)

I don't think so. This [doc](https://docs.aws.amazon.com/AmazonECS/latest/bestpracticesguide/networking-outbound.html) explains a lot about the difference between these two approaches.

**Comment by efekarakus** [comment]
Hello! I'll close the issue as @iamhopaul123 pointed out NAT gateways shouldn't cause an issue (in fact it'll make the application more scalable), but it comes at the following cost: https://aws.amazon.com/vpc/pricing/

Please let me know if you'd like to re-open the issue!

**Comment by sodhi1981** [comment]
Hello,

I have added network.vpc.placement = private to my test environment
```
environments:
  test:
    variables:
      ENV: test # env is test
    http:
      alias: apitest.xyz.com
    cpu: 1024
    memory: 2048
    network:
      vpc:
        placement: private
  ```
After deploying the service, I don't see any NAT gateway in the VPC. 
Please advise.
