### ISSUE TITLE
Check whether AppRunner is available in the region

### ISSUE THREAD

**Issue by adonig** [aws/copilot-cli#3172]
I ran into a strange error message when trying to deploy a request driven web service in the Frankfurt (eu-central-1) region.

`Template format error: Unrecognized resource types: [AWS::AppRunner::Service]`

After some digging I found out that AppRunner isn't available in this region yet. It would be nice if copilot-cli could check whether a template is valid for the region and issue a warning.

**Comment by efekarakus** [comment]
Hi @adonig !

Thanks for the enhancement request, it totally makes sense. This is also doable with the AWS SDK by calling the [`endpoints.RegionsForService` function](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/#RegionsForService). 

One concern is that the list is hard-coded in the SDK: https://github.com/aws/aws-sdk-go/blob/v1.42.29/aws/endpoints/defaults.go#L2092-L2109 so that means that if app runner becomes available in a new region we would need to update the SDK version and then do a new Copilot binary release to pick up the latest data.

Like you mentioned, instead of erroring we can write a warning saying it might not be available in the region yet

**Comment by efekarakus** [comment]
The proposed internal programming model:

1. Update `internal/aws/` packages with:
```go
package regions // 🆕 package

// ServiceID represents the name of a service.
type ServiceID string

const (
   ECSServiceID = "ecs"
   AppRunnerServiceID = "apprunner"
)

// IsServiceAvailable returns true if the service ID is available in the given region.
func IsServiceAvailable(sid ServiceID, region string) bool 
```


2. Update the `manifest` pkg by adding `IsAvailableInRegion` method to all manifest types.
```go
package manifest

// IsAvailableInRegion returns true if it's possible to create a LBWS in the given region.
func (mft *LoadBalancedWebService) IsAvailableInRegion(region string) bool

func (mft *BackendService) IsAvailableInRegion(region string) bool
func (mft *WorkerService) IsAvailableInRegion(region string) bool
func (mft *ScheduledJob) IsAvailableInRegion(region string) bool
```

3. Update `cli/svc_deploy.go`, `cli/job_deploy.go` so that:
```go
if !mft.IsAvailableInRegion(o.targetEnvironment.Region) {
     log.Warningf("%s might not be available in region %s, proceed with caution", o.targetSvc.Type, o.targetEnvironment.Region)
}
```

**Comment by hown3d** [comment]
Hey @efekarakus, I'd like to work on this one.

**Comment by iamhopaul123** [comment]
Hello @hown3d. Thank you for taking initiative at this! Feel free to let us know if you need any help!
