### ISSUE TITLE
Feature Request: An option to adjust the amount of output messages for CI/CD workflow

### ISSUE THREAD

**Issue by enm10k** [aws/copilot-cli#3204]
I'm running `copilot svc deploy` on my GitHub Actions workflow and it outputs too much messages.
For example, I see messages like the following every 0.1 second.

It's nice to have an option to adjust the amount of messages for CI/CD workflow.

```
...
- Updating the infrastructure for stack my-copilot-service  [update in progress]  [4.7s]
  - An ECS service to run and maintain your tasks in the environment cluster         [not started]         
  - An ECS task definition to group your containers and run them on ECS              [not started]         
- Updating the infrastructure for stack my-copilot-service  [update in progress]  [4.8s]
  - An ECS service to run and maintain your tasks in the environment cluster         [not started]         
  - An ECS task definition to group your containers and run them on ECS              [not started]               
...
```

**Comment by efekarakus** [comment]
Hi @enm10k !

That's surprising normally GitHub Actions should set the environment variable `CI=true` by default: https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables

which Copilot detects and then sets the render interval to be 30s instead of 0.1s:
https://github.com/aws/copilot-cli/blob/4e5e14d9a05178a739cc620745da112cae698c69/internal/pkg/term/progress/render_interval.go#L20-L21

What happens if you set `export CI=true` explicitly in your workflow?

**Comment by enm10k** [comment]
Thanks for letting me know.

I noticed the version I'm using doesn't contain the following change you mentioned.
https://github.com/aws/copilot-cli/commit/b680c8068ca129ce15d98534e4be265aab52c327

I'll update `copilot-cli` command in my environment.
Thanks again.

**Comment by efekarakus** [comment]
Thank you! I'll close the issue, but please let me know if the problem doesn't go away after upgrading copilot
