### ISSUE TITLE
Minimum number of Route53 Hosted zones?

### ISSUE THREAD

**Issue by rinogo** [aws/copilot-cli#3211]
I successfully deployed a "Load Balanced Web Service" with a domain alias using copilot.

The domain alias provided (for the sake of discussion) was `alias.com`. The service was deployed to `api.alias.com`.

From inspecting our AWS account, it looks like three "Hosted Zones" were created by copilot. The Hosted Zones present on our AWS account are as follows:

```
alias.com //Created by Route53 Registrar
app-name.alias.com
environment-name.app-name.alias.com
environment-name.app-name.local
```

Are all four of these hosted zones required for the operation of our service?

`alias.com` makes sense to me as it is required for the `api.alias.com` record. `api.alias.com` points directly to the AWS load balancer; it's not relying upon any other zone files (i.e. `api.alias.com` is not a CNAME record that points to a record in one of these other hosted zones).

I'm new to copilot, so I'm not sure if the other Hosted Zones are strictly necessary. Can any of them be deleted? Does copilot/AWS require these zones to be present for internal operations, or are these Hosted Zones only included as a "default convenience"?

I'm assuming that they are all required, which is unfortunate since [Hosted Zones are $0.50/month](https://aws.amazon.com/route53/pricing/) and we intend on only referencing our service using the load-balanced `api.alias.com`, never something like `api.environment-name.app-name.alias.com`.

The number of Hosted Zones created by copilot may not be a big deal for a single application with a single environment, but as more applications and environments are added, costs will multiply.

Again, I'm assuming they're all required, just hoping to get some insight so that we can plan our applications and environments deliberately, especially since there's no Free Tier on Route53. Thanks in advance! :)

**Comment by Lou1415926** [comment]
Hello @rinogo ! Thank you for the inquiry! The short answer is that all four hosted zone should be considered required and it's not recommended to delete them. 

The environment hosted zone (`env.app.domain.com`) and app-level hosted zone (`app.domain.com`) are assumed to exist during many of Copilot's operations, for example, the ACM certificate that Copilot creates for you uses the domain name `svc.env.app.domain.com`, and to validate this certificate, it needs to put validation records into the environment hosted zone. Also, when you create an environment, the application hosted zone automatically add a delegation record to the environment hosted zone - if the application hosted zone is manually deleted, and you want to create an environment afterwards, this operation may fail. 

Deleting a hosted zone may introduce irreversible issue to your application (i.e. you would probably unfortunately need to start over from `copilot app init`), since Copilot identifies hosted zone by hosted zone ID around, and it's (almost) impossible to create a new hosted zone with the same ID.

Perhaps in the future Copilot can explore the possibility to structure things so that people could remove some hosted zones if they are 100% sure they don't need it, and whether it's an ideal user experience. But for now, it is not recommended to delete those hosted zones 🙇🏼‍♀️ .

To add explanation for the last hosted zone - the `.local` hosted zone provides [service discovery endpoints](https://aws.github.io/copilot-cli/docs/developing/service-discovery/) for your services to communicate with each other privately. 

Hope this helps!!

**Comment by rinogo** [comment]
Thank you very much, @Lou1415926 ! This is exactly what I needed to know. A short, high-level answer along with background details. Thanks again!
