### ISSUE TITLE
Am I able to call ${EnvName}.${AppName}.${DomainName}/path... when using a custom domain?

### ISSUE THREAD

**Issue by mdeliadi** [aws/copilot-cli#3264]
I've set up some services of type "Load Balanced Web Service" with a custom domain.

I've set two A records for each public IP of the load balancer for each searvice, resulting in
- A record, name: service1.env.app.domain.com value: IP1
- A record, name: service1.env.app.domain.com value: IP2
- A record, name: service2.env.app.domain.com value: IP1
- A record, name: service2.env.app.domain.com value: IP2

And I'm able to call ${SvcName}.${EnvName}.${AppName}.${DomainName}/path...

Since all those records are pointing to the same couple of IPs, I've tought it would be enough to have only two A records:
- A record, name: env.app.domain.com value: IP1
- A record, name: env.app.domain.com value: IP2

The problem is, ${EnvName}.${AppName}.${DomainName}/path... is not working.
Could You please let me know me if it's actually possible to have it working in that way, and how?
Thank You! :D

**Comment by efekarakus** [comment]
Hi @mdeliadi !

My hypothesis is that it's not working because of the listener rules associated with the load balancer:
The requests get routed to the appropriate service based on the host header:
https://github.com/aws/copilot-cli/blob/3e3abbb93a47dcaa7523ad4dbf0d23ee0a00db25/internal/pkg/template/templates/workloads/services/lb-web/cf.yml#L322-L329

which must conform to `${SvcName}.${EnvName}.${AppName}.${DomainName}`

Out of curiosity why did you have to create the A-records? If the application was created with a custom domain (i.e. `copilot app init --domain example.com` copilot should already create the appropriate alias records.

-----

Perhaps one way of satisfying the request is by changing the application architecture like this:

![copilot-issue-3264](https://user-images.githubusercontent.com/879348/153462388-11583783-bcdb-423b-834f-0c7fdb64aeb8.png)

Where there is a single load balanced web service that acts like a proxy that then routes requests to other "Backend Services" in your application

Hope this helps!

**Comment by mdeliadi** [comment]
Hi @efekarakus !

Thanks for your explanation! I've created the A records because the domain is not managed by Route 53 but by Cloudflare, I've seen this solution explained [here](https://github.com/aws/copilot-cli/issues/3113#issuecomment-991452499)!
