### ISSUE TITLE
Why NLB is dropped supporting UDP?

### ISSUE THREAD

**Issue by rluisr** [aws/copilot-cli#3281]
In this [commit](https://github.com/aws/copilot-cli/commit/060b8d11bb30a67277b184b73188ecd64dc21e1c), Copilot stop supporting UDP on NLB.

I was just thinking that I want to manage my VPN server with Fargate.
I would like to know the background of the dropping support this, and why?

**Comment by Lou1415926** [comment]
Hello @rluisr !

That's a great question. Thank you for asking! We removed the support because we didn't think we had enough information of its use case, say in an internet-facing service like Load-Balanced Web Service, vs. its use case in an internal-facing service like Backend Service. We wanted to gather more datapoint to better understand its place in different Copilot service patterns before jumping into a conclusion.

It's great that you reached out! You mentioned you wanted to use it for your VPN server. Would you mind sharing more details? For example, how do you expect to control your incoming traffic? Do your instances accept only traffic from certain IPs?

**Comment by rluisr** [comment]
Thanks, @Lou1415926 

I see now that I understand.
It's true that it's very costly to keep running unnecessary code forever.

My use case is that manage the OpenVPN server onto Fargate for engineers.
The container(OpenVPN) listens 1194/UDP for communication with OpenVPN Client. 1194/UDP is fully open because many engineers work from home.

The files for the OpenVPN server are served from EFS.

I know that the AWS Client VPN service exists. However, for various reasons, I cannot use it.

**Comment by Lou1415926** [comment]
Thank you for sharing the information!

Given that your task is publicly accessible (i.e. it's also reachable through public IP), would you view it as a security concern in your use case?
