### ISSUE TITLE
feat(env): allow VPCs with no private subnets

### ISSUE THREAD

**Issue by huanjani** [aws/copilot-cli#3282]
Just as we allow users to use existing VPCs that don't have public subnets, we should allow the same with private subnets. We currently log a warning re: the limitations of no public subnets (load balancing), and should do the same for the limitations of no private subnets (future use of internal load balancers).

This change enables users to use default VPCs, as they come with default public subnets.

**Comment by innix** [comment]
Nice! Thanks for accepting my suggestion from Gitter. Funnily enough, I actually reported a bug a few days ago on Gitter that I think affects your last sentence about using the default VPC. The bug has been raised as #3266, but basically Copilot mistakenly categorizes public subnets as private if the subnet only has an implicit association to a route table with an `igw-`/Internet Gateway route. The default VPC and it's public subnets are set up that way so they would be affected by that bug. Luckily @efekarakus managed to find and write a solution really quickly.

Just thought I'd mention that bug because it might cause issues if you try to implement this feature and test it on a default VPC without the bug fix being applied first.

**Comment by huanjani** [comment]
Ah, thank you, @innix, for your thoughtfulness-- for finding that bug, making this suggestion, and considering the two together!
