### ISSUE TITLE
Cannot deploy service due to error "Response object is too long"

### ISSUE THREAD

**Issue by khageshsaini** [aws/copilot-cli#3298]
Hi,

We have close to 100 services in an application. We are using copilot to deploy these in an environment. We are not able to deploy new services and recieve the error "Response object is too long" in **Resources** section with **Logical ID - EnvControllerAction**. 

I am suspecting this is due to this [Cloudformation restriction ](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/crpg-ref-responses.html) on size of custom resource response objects.

Few Observations:
 - EnabledFeatures Key in the Output section for env stack is a very long string when deploying large number of services. The string even contains duplicates. Not sure if we can get rid of it.
- We can shorten the size of each service name but we may eventually hit the size restrictions.

Please let us know the resolution or a workaround for the time being.

**Comment by efekarakus** [comment]
Hi @khageshsaini !

Apologies that you ran into the CloudFormation (CFN) size limits 🙇  
I'll provide an explanation first for the `EnabledFeatures` output and other CFN parameters in the environment stack in order to explain the workarounds.

## Background
Today, Copilot environments have the following CFN Parameters:
* `ALBWorkloads`: comma-separated service names that require a load balancer
* `EFSWorkloads`: comma-separated service names that require a file system
* `NATWorkloads`: comma-separated service names that are placed in private subnets

When a service is deployed, Copilot will populate these parameters in order to create the resource. For example, if a "Load Balanced Web Service" named "frontend" is deployed, then the `ALBWorkloads` parameter has the value `frontend`. If another "Load Balanced Web Service" named "api" is deployed, then the `ALBWorkloads` has the value `frontend,api`.
 This method ensures that when "frontend" is deleted the load balancer is not removed. Only when both services are deleted, the `ALBWorkloads` parameter becomes the empty string resulting in the load balancer to be deleted in order to save cost and not pay for idle resources.

Finally, the `EnabledFeatures` output is just a concatenation of `${ALBWorkloads},${EFSWorkloads},${NATWorkloads}`. This is why you're seeing duplicates, it's expected if you have a service that requires both a load balancer and NAT gateways for example. The output `EnabledFeatures` is necessary because CloudFormation won't update a stack unless a resource or output is modified, this is our little hack to ensure that even if a shared resource already exists we can keep updating the Parameters.

## Mitigations

### ⭐️ [preferred] Option 1: Update environment parameters with a single value

1. Navigate to the CloudFormation console and click on `Update` for your environment stack:
![update-stack](https://user-images.githubusercontent.com/879348/154727445-4717aacb-167e-43a4-af91-429de56a4341.png)
  Your environment stack name should be `${appName}-${envName}`

2. Use the current template, and update the `ALBWorkloads`, `EFSWorkloads`, and `NATWorkloads` parameters with a single value (for example: "donotdeleteme")

![env-params](https://user-images.githubusercontent.com/879348/154727714-c5b661ca-8073-4da5-88fd-26e8d3aeb7cf.png)

3. Keep pressing on "Next" and then "Update stack"

**What did we do?**  
We essentially created a fake service called "donotdeleteme" that has all copilot features enabled, this should result in the `EnabledFeatures` output to also drastically reduce to only "donotdeleteme,donotdeleteme,donotdeleteme".   

With this mitigation, the copilot CLI will continue behaving correctly and you shouldn't experience any problems with initializing new services, deleting services, or upgrading the CLI. However, if you run into the limit again, you'll have to delete the parameters again and just keep "donotdeleteme".

### Option 2: Create new applications

An alternative option would be splitting your application into multiple sub-applications. For example, you can split up all Load Balanced Web Services into separate applications and have them talk to each other through the load balancer endpoint.

-----

Hopefully the reply makes sense, please let us know if the proposed solution helped!

**Comment by khageshsaini** [comment]
Thanks @efekarakus for the great explanation around the usage of `EnabledFeatures` key. We have made the changes as suggested and the services are being correctly deployed now. Hopefully, we won't be running into this issue again.
