### ISSUE TITLE
app init with custom domain: The account does not seem to own the domain that you entered

### ISSUE THREAD

**Issue by gcstr** [aws/copilot-cli#3462]
I'm not quite sure why I'm seeing this warning. The domain I'm trying to use, although it was not registered via Route53, has a hosted zone in the same account.

If I try to initialize the app with any other domain in my account that was registered via Route53, the init process works fine.

Are there any additional steps to be able to use domains not registered via AWS?
Can it be related with the fact that `.dev` TLD isn't supported by AWS?

```
$ copilot app init --domain mydomain.dev
Note: The account does not seem to own the domain that you entered.
Please make sure that mydomain.dev is registered with Route53 in your account, or that your hosted zone has the appropriate NS records.
To transfer domain registration in Route53, see:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-transfer-to-route-53.html
To update the NS records in your hosted zone, see:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/SOA-NSrecords.html#NSrecords
```

**Comment by iamhopaul123** [comment]
Hello @gcstr.

> Are there any additional steps to be able to use domains not registered via AWS?

Yes it is possible and it is also a Copilot feature that is actively worked on right now (see #2694) (hopefully included in our next release so please stay tuned)!

After #2694, you would need to [request an ACM certificate](https://docs.aws.amazon.com/acm/latest/userguide/gs-acm-request-public.html) on your own for whatever domain and subject alternative names you'd like to use for your environment, and then follow the prompt on the console to validate the certificate on your own (since it is not registered on Route 53 unfortunately we can't help on this). Then create an environment with this certificate imported. After that you can deploy your service to the environment and specify the [custom domain](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) you'd like to use and add A-record on your own to wherever you registered your domain.

Let me know if anything is not clear to you!

**Comment by gcstr** [comment]
@iamhopaul123 thanks a lot for submitting this new feature to copilot 1.18, I'll give it a try this week!

The docs are clear that to use a custom cert, one should pass the ARN with the `env init` command:

```
copilot env init --import-cert-arns [cert-arn]
```

Does it mean that there is no way to change or update the certificates without recreating the environment?

**Comment by iamhopaul123** [comment]
Hello @gcstr. Thank you for your support for Copilot! As for v1.18, unfortunately there's no way to do `env init` for an existing environment. However, we are working on the ["env manifest"](https://github.com/aws/copilot-cli/issues/3522) feature which will allow users to config and apply changes to their environments. Please stay tuned for that and feel free to comment!
