### ISSUE TITLE
Try once for Scheduled Jobs 

### ISSUE THREAD

**Issue by dmathewwws** [aws/copilot-cli#3469]
Hi,

Working with scheduled jobs (and really enjoying it) and appreciate the new easy turn off feature for scheduling a job.

One thing that I run into when I have a new scheduled job is that I want to deploy it and run it right away to test it works (and then I go in and change the schedule to the actual longterm schedule, once I've tested it runs as expected).

I would love an option to test a scheduled job once immediately after its deployed.

**Comment by efekarakus** [comment]
Related https://github.com/aws/copilot-cli/issues/2429#issuecomment-1067394185

Thanks @dmathewwws for the feature request, it totally makes sense. I agree it would be super nice to have a command like this:
```
copilot job run
```
Similar to `task run` to invoke the step function!

**Comment by kangere** [comment]
@efekarakus I would like to work on this issue, will you be taking PRs for this particular issue?

**Comment by Lou1415926** [comment]
Hi, @kangere! Thank you very much! That would be awesome ❤️ 

Feel free to look at the guide [here](https://github.com/aws/copilot-cli/blob/mainline/CONTRIBUTING.md) and comment in this Issue with your design / additional thoughts. If you have any blueprint implementation plan feel free to post it here as well!

**Comment by kangere** [comment]
Hi, @Lou1415926 , I propose creating a `job invoke` command that would take a name and environment, for example

`copilot job invoke --name jobname --env envronment`

This command would have to be called after a call to `job deploy` since the job infrastructure needs to have been provisioned first

**Comment by Lou1415926** [comment]
@kangere Thank you very much for the proposal!

> This command would have to be called after a call to job deploy since the job infrastructure needs to have been provisioned first

This totally makes sense to me!

A similar example would be `copilot svc log --name api --env test`. To see the log, `api` and `test` must have been an existing service/environment, respectively.  We validate these assumptions [here](https://github.com/aws/copilot-cli/blob/5cd9981a26c0a0eb1b1aa02c4f9f3ac6bfe3ee21/internal/pkg/cli/svc_logs.go#L210) and [here](https://github.com/aws/copilot-cli/blob/5cd9981a26c0a0eb1b1aa02c4f9f3ac6bfe3ee21/internal/pkg/cli/svc_logs.go#L216).

We might want to do the same for this command!

---

>  I propose creating a `job invoke` command

The flags `--name` and `--env` sounds great to me. I'd say we can also add the app flag `--app`. 

The `--app` flag will take precedence over workspace app. If it's absent, we assume that users want to invoke the job that is deployed in the app of current workspace. Example: https://github.com/aws/copilot-cli/blob/5cd9981a26c0a0eb1b1aa02c4f9f3ac6bfe3ee21/internal/pkg/cli/svc_logs.go#L288

If the command has neither an app flag nor executed under a workspace, we prompt to ask for an app: https://github.com/aws/copilot-cli/blob/5cd9981a26c0a0eb1b1aa02c4f9f3ac6bfe3ee21/internal/pkg/cli/svc_logs.go#L196

What do you think of this workflow?


---

Finally, what do you think of `job run` that's similar to `task run`?

**Comment by kangere** [comment]
@Lou1415926  Thank you for your response

>  A similar example would be copilot svc log --name api --env test. To see the log, api and test must have been an existing service/environment, respectively. We validate these assumptions [here](https://github.com/aws/copilot-cli/blob/5cd9981a26c0a0eb1b1aa02c4f9f3ac6bfe3ee21/internal/pkg/cli/svc_logs.go#L210) and [here](https://github.com/aws/copilot-cli/blob/5cd9981a26c0a0eb1b1aa02c4f9f3ac6bfe3ee21/internal/pkg/cli/svc_logs.go#L216).
> 
> We might want to do the same for this command!

This makes sense, the validation would be the safeguard that the job infrastructure already exists!

> The --app flag will take precedence over workspace app. If it's absent, we assume that users want to invoke the job that is deployed in the app of current workspace

I also agree with adding the `--app` flag and a prompt if the app name is not provided via the flag or found in the current workspace.

> Finally, what do you think of job run that's similar to task run?

I agree with using `job run` rather than `job invoke` , It is  easier to understand and also for consistency purposes

**Comment by Lou1415926** [comment]
@kangere Awesome! Thank you very much for your response🙇🏼‍♀️!! It's great that we're on the same page!

I have some rough thoughts on the implementation, and I will post them here. Let me know what you think!

### New Package - `runner`

We can have a new package called `runner`, and under which a sub package `job`, so that the path is `internal/pkg/runner/job/`. The `runner` package will contain clients for one-off tasks/jobs. The Copilot core team will later refactor the codebase such that `copilot task run` depends on this package as well. So instead of 
```
internal/pkg
├─ task/         # The existing package that `copilot task run` depends on.
│    └─  config_runner.go
└─ runner/    # The new package you might be adding.
      └─ job/
          └─ job_runner.go
```
We will later refactor it to
```
internal/pkg
└─ runner/    # The new package you might be adding.
      └─ job/
      │   └─ job_runner.go
      └─ task/
          └─ config_runner.go
```

This way we can eventually have a unified interface for running a job once and running a one-off task.


---

### Code Skeleton 

Working with the `runner` package ⬆️ , I have the code skeleton below as an example how `runner` would play with the code base. The skeleton should serve as an example to demonstrate my idea above ⬆️ , as well as hopefully an easier start for you!

```go
/**
    In `internal/pkg/aws/stepfunctions/stepfunctions.go`
 */
func (s *StepFunctions) Execute(stateMachineARN string) error {
    // Call aws-sdk: s.client.StartExectuion()
}


/**
    In `internal/pkg/runner/job/job.go`
 */
type JobExecutor interface {
    Execute(stateMachineARN string) error
}

type JobRunner struct {
    executor JobExecutor // Instantiated as StepFunctions (see internal/pkg/aws/stepfunctions/stepfunctions.go)
}

func (r *JobRunner) Run() error {
    // 1. Get state machine ARN.
    // 2. Call r.executor.Execute() with the ARN
}


/**
    In `internal/pkg/cli/job_run.go`
 */
type Runner interface {
    Run() err
}

type runJobOpts struct {
    /* ~Omit~ */
    runner Runner // Instantiated as JobRunner
}

// Validate is a no-op for this command. 
// [Explanation] it's a no-op because all 3 flags are required, and `Validate` only validate optional flags.
func (o *runJobOpts) Validate() error {
    return nil
}

// Ask prompts for and validates any required flags.
func (o *runJobOpts) Ask() error{
    // Similar to `copilot svc logs`:
    // 1. ValidateOrAskForApp
    // 2. ValidateOrAskForSvcEnvName
}


func (o *runJobOpts) Execute() error {
    // err := o.runner.Run()
}


```

Let me know if you have different thoughts and concerns, or if the above doesn't make sense to you !

**Comment by kangere** [comment]
@Lou1415926 , sorry for the late response. This implementation makes sense to me, I haven't had the time to dig too deep into the code but it looks pretty straightforward, I will let you know if I have concerns or different thoughts

**Comment by kangere** [comment]
@Lou1415926 , after looking into this a bit more. I propose the following change

```go

// internal/pkg/cli/job_run.go
type Runner interface {
    Run(statemachineARN string) err
}

// internal/pkg/runner/job/job_runner.go
func (r *JobRunner) Run(statemachineArn string) error {
    // 1. Call r.executor.Execute() with the ARN
}
```
This because the statemachine arn can only be obtained from querying the cloudformation stack resources. The Cloudformation stack name can only be inferred after obtaining the appname, environment and job name since the cloudformation stack uses the following notation `appname-environment-jobname` (correct me if I'm wrong).

Does this make sense or is there something I am missing ?

**Comment by iamhopaul123** [comment]
Hello @kangere. Yes you are correct: the statemachine arn requires the app, env, job name info. However, maybe they could be member variables as parts of `JobRunner`, so that in `Run()` the stack name can be constructed accordingly. Similar to what we have for `EnvRunner` (pkg/task/env_runner.go):

```golang
// EnvRunner can run an Amazon ECS task in the VPC and the cluster of an environment.
type EnvRunner struct {
        ...
	// App and Env in which the tasks will be launched.
	App string
	Env string
        ...
	// Interfaces to interact with dependencies. Must not be nil.
	...
}

**Comment by kangere** [comment]
Hi @iamhopaul123, that implementation makes sense. Thanks for answering my concerns

**Comment by kangere** [comment]
@efekarakus I thought PR [3692](https://github.com/aws/copilot-cli/pull/3692) should have closed this issue ?

**Comment by efekarakus** [comment]
Yup @kangere, your PR resolves this issue. Closing now, we'll comment here again once the new version of copilot is out and folks can test out `copilot job run`

**Comment by efekarakus** [comment]
This feature is now out in v1.20 🚀 
Release notes: https://github.com/aws/copilot-cli/releases/tag/v1.20.0 !
Blog post: https://aws.github.io/copilot-cli/blogs/release-v120/
