### ISSUE TITLE
Container is killed (OutOfMemoryError)

### ISSUE THREAD

**Issue by doneumark** [aws/copilot-cli#3470]
I have a pretty long function that runs in the background (about 5-10 minutes), in a load balanced web service (it's an "import data from integration" call).
Locally I wait for it to finish and then everything is fine.

But on AWS, after few minutes the task is killed, and at the task page, I get:

```
OutOfMemoryError: Container killed due to memory usage
--
Exit code: 137
```

What can I change in the manifest or how can I debug exactly what causes the problem?
Currently, in the manifest, I have:
```
name: node
type: Load Balanced Web Service
...
cpu: 256       # Number of CPU units for the task.
memory: 512    # Amount of memory in MiB used by the task.
```

How can I tackle this issue?

**Comment by Lou1415926** [comment]
Hello @doneumark !

Would you be able to check the memory usage of your container by [`docker stats`](https://docs.docker.com/engine/reference/commandline/stats/)? You can then try increasing `memory` field given the information that you've obtained from `docker stats`. Let's see if that solves it for you!

**Comment by doneumark** [comment]
thank you!

**Comment by h5aaimtron** [comment]
@Lou1415926 

OOM errors can also happen depending on the underlying app not respecting cgroup hierarchy per:
https://aws.amazon.com/blogs/developer/configuring-net-garbage-collection-for-amazon-ecs-and-aws-lambda/

The suggested fix is to set the hard limit on the container so that the underlying runtime can recognize the actual limit and not the host systems' limit such that GC will run appropriately. I've been looking through the documentation and can't figure out how to set the hard limit via manifest. Any thoughts?

**Comment by Lou1415926** [comment]
@h5aaimtron Great find! You are right that the container size isn't surfaced in the manifest. However, you can try our [YAML patch override](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) to set the size on your container!
