### ISSUE TITLE
Cleaner pipeline name on AWS Console

### ISSUE THREAD

**Issue by raxityo** [aws/copilot-cli#3494]
For one of my services, I have a pipeline that was created using an older version of copilot cli (some version older than [v1.16.0](https://github.com/aws/copilot-cli/releases/tag/v1.16.0)). The name of the pipeline on AWS console is the same as what I specified in the manifest.

I recently created another pipeline for my service using the latest version of copilot cli but now its name is `${APPLICATION_NAME}-${SERVICE_NAME}-${PIPELINE_NAME}-${SOME_SALT}` on the console.
Is there a way to specify the pipeline name that shows up in the console?

**Comment by Lou1415926** [comment]
Hello @raxityo ! Thank you for noticing and asking! The change of name you see is the result of two updates on Copilot's end:

1. The pipeline name is now prepended`${APPLICATION_NAME}-`. Other Copilot entities such as services and environments are also namespaced, and with this change, pipeline will no longer be the exception. Also, it's easier for folks to tell which application the pipeline belongs to - and it makes it possible to have `pipeline1` in application A, and `pipeline1` in application B because the actual resource name won't collide. 

2. The suffix `-${SOME_SALT}` is because now Copilot lets CloudFormation generate a name for the pipeline based on the app name and the pipeline name - unlike previously when Copilot hardcodes it with the name in manifest. This is also similar to today's services - the ECS service's actual resource name is generated by CFN and has the salt suffix. Hardcoding resource name in CFN could lead to major issues during updates that require resource replacement. Although this is not a concern with today's CodePipeline, but in the future, if CodePipeline has new properties that require resource replacement action from CFN's end, it'd be an issue that might be too late to deal with. 

Hope these make sense to you!! Please let me know if you have other concerns. It is possible for you to retrieve your pipeline's actual resource name using `copilot pipeline show --json` if that helps.

**Comment by raxityo** [comment]
Gotcha, that makes sense, thank you so much for the detailed background, @Lou1415926!
