### ISSUE TITLE
Large bill from AWS Config (ConfigurationItemRecorded)

### ISSUE THREAD

**Issue by SimonBerens** [aws/copilot-cli#3516]
I recently looked at my aws cost explorer, and found that almost 95% of my cost was coming from `ConfigurationItemRecorded`. Is this desired behavior? I only have ~5 services running with `count: 1` for each. Scaling the services seems questionable after seeing this in my bill.

Is there any way I can look into the details of what exactly was causing this to happen?

**Comment by efekarakus** [comment]
Hi @SimonBerens !

> found that almost 95% of my cost was coming from ConfigurationItemRecorded. Is this desired behavior?

I'm so sorry to hear about the large bill 😞 Copilot doesn't create any AWS config rules. I assume this was setup separately?
Apologies - I'm not familiar with AWS config, but I'd be happy to dive deeper to see how we can reduce the cost.
From the billing, I see:
> You pay $0.003 per configuration item recorded in your AWS account per AWS Region. A configuration item is recorded whenever a resource undergoes a configuration change or a relationship change.

I assume this means that anytime a deployment happens due to an image change then a configuration item gets recorded and you get charged $0.003 💭 
I found this blog post pretty illuminating: https://serebrov.github.io/html/2019-10-08-aws-config-charges.html so maybe the large cost is due to a service(s) that's misbehaving and causing tasks to constantly get re-created due to failing health checks.

One possibility to stop the large bill is to "stop recording configuration items" according to the AWS config documentation if that's at all a possibility.

**Comment by SimonBerens** [comment]
That would make sense because a few of my services were stuck in a constant restart state for a while. I stopped the recording, hopefully that should reduce the bill. Thanks!

**Comment by efekarakus** [comment]
I'll close the issue for now, but please feel free to post additional follow-ups here and we can re-open the thread!

**Comment by SimonBerens** [comment]
happy to report costs have been reduced 90% :)
