### ISSUE TITLE
Environment upgrade from 1.8.0 -> 1.9.0 failed: AccessDenied when upload template to bucket

### ISSUE THREAD

**Issue by TillaTheHun0** [aws/copilot-cli#3556]
On a recent service deploy, `copilot` CLI attempted to transitively upgrade the Copilot environment from `1.8.0` to `1.9.0`. For past environment upgrades, this has gone off without a hitch. Though this time, an error was received when attempting to upload the new service template to the s3 bucket in the App AWS account:

```
✘ execute "env upgrade --app foo-app --name preview": upgrade environment preview from version v1.8.0 to version v1.9.0: upload manual/templates/***/18918392bc70edd***.yml to bucket stackset-foo-app-inf-pipelinebuiltartifactbuc-1sgrupkj5d4eq****: AccessDenied: Access Denied
	status code: 403, request id: MMDRNV2Y90MTNHH3, host id: rERY8wMubiJ+VpU8I7hd+z/8l1BSCwnwe2uePw5pPwtBflXDkL1TiLSDw2D3b3jeKhxAIE8+vpc=
```

I've obfuscated some of the error above with `****`

I'm using the App AWS credentials, so not sure why i'd be getting an access denied on the s3. Thanks for you help!

**Comment by huanjani** [comment]
Hello, @TillaTheHun0!
I'm so sorry about this. 

Have you by chance made any modifications to your `EnvironmentManagerRole`? Would you mind checking if you have the `PutObjectsToArtifactBucket` [policy](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/environment/partials/environment-manager-role.yml#L221) in your CFN template for your environment stack? 

Thanks!

**Comment by efekarakus** [comment]
Hi @TillaTheHun0 !

To add onto Janice's comment, we're currently in the process of trying to reproduce the issue.

In the mean time to get you unblocked, our hypothesis is that it's because the following permission is missing in the `EnvironmentManagerRole`:
https://github.com/aws/copilot-cli/blob/0a2bd5ac31948ceb9e8f7e8bff67480dc1623c47/internal/pkg/template/templates/environment/partials/environment-manager-role.yml#L225
I think if you make a modification to the EnvironmentManagerRole's policy to add the permission above, it should get you unblocked.

### Hypothesis

Between version `v1.8.0` and `v1.9.0`, we started uploading the environment template to the S3 bucket (`stackset-foo-app-inf-pipelinebuiltartifactbuc-1sgrupkj5d4eq****`) but with the `ObjectCannedACLBucketOwnerFullControl` ACL as it's a recommended practice.

However, since in `v1.8.0` the role doesn't have the `PutObjectAcl` permission then the template upload fails.

**Comment by TillaTheHun0** [comment]
@huanjani @efekarakus thanks for your help with this 🙏 

I checked the `EnvironmentManagerRole` for the environment being upgraded. The `PutObjectsToArtifactBucket` policy is like:

```json
      {
          "Action": [
              "s3:PutObject"
          ],
          "Resource": [
              "arn:aws:s3:::stackset-foo-app-inf-pipelinebuiltartifactbuc-1sgrupkj5d4eq",
              "arn:aws:s3:::stackset-foo-app-inf-pipelinebuiltartifactbuc-1sgrupkj5d4eq/*"
          ],
          "Effect": "Allow",
          "Sid": "PutObjectsToArtifactBucket"
      },
```

so no `s3:PutObjectAcl` there. 

There is another policy, `BuiltArtifactAccess`, that contains more s3 permissions, but still no `s3:PutObjectAcl` there either.

> Between version v1.8.0 and v1.9.0, we started uploading the environment template to the S3 bucket... with the ObjectCannedACLBucketOwnerFullControl ACL as it's a recommended practice.

If that's the case, and with the lack of the `s3:PutObjectAcl` permission on any of the existing policies, then your hypothesis seems like it could the issue I am seeing. I will add that permission to the `PutObjectsToArtifactBucket` policy, and retry the upgrade and see what we get, and report back here.

**Comment by efekarakus** [comment]
Thanks @TillaTheHun0 , did this issue happen when running `copilot svc deploy` or another command?

**Comment by TillaTheHun0** [comment]
Eureka! Looks like adding that permission to the `PutObjectsToArtifactBucket` did the trick for upgrading the environment:
```
✔ Upgraded environment preview's template to version v1.9.0.
```

I am assuming I'll need to do this for each environment, for now?

**Comment by TillaTheHun0** [comment]
> did this issue happen when running copilot svc deploy or another command?

@efekarakus, looks like this happened when running `copilot secret init ... --overwrite`. We set some secrets on each deploy, and it looks like that is what triggered the environment upgrade.

**Comment by efekarakus** [comment]
That's great to hear! 

> I am assuming I'll need to do this for each environment, for now?

That's correct :) until we have a patch for the fix, adding the permission will get you unblocked

**Comment by TillaTheHun0** [comment]
Thank you both for your help! Feel free to close when you're comfortable. That workaround got me what I needed for now, but will upgrade the CLI when the patch is released.

**Comment by efekarakus** [comment]
OK I could re-produce the issue! 
> Only found one environment, defaulting to: issue-3556
✘ Failed to upgrade environment issue-3556's template to version v1.9.0.
✘ upgrade environment issue-3556 from version v1.8.0 to version v1.9.0: upload manual/templates/demo-issue-3556/8aecebe8cb2ea170cd84da0db319acbb448788f1fb7ea833797e39ceef741426.yml to bucket stackset-demo-infrastruc-pipelinebuiltartifactbuc-igralpvd2hls: AccessDenied: Access Denied
	status code: 403, request id: 6W6Z0E1Z14AWJQ08, host id: H05ydtRUZ3TG+bDnLeaJ+7KGphPfWvwd2O1oXTMj8GVa5ar8Isi3e3qw8peAx6FBaKNUxLf7Sb4=

The issue only happens if the account for `app init` - i.e. the account where the `stackset-demo-infrastruc-pipelinebuiltartifactbuc-igralpvd2hls` S3 bucket - is different than the environment account.

If the application and environments are in the same account, then the issue doesn't happen. That's why our tests didn't catch it. 
We'll think of a fix and post an update here to resolve the issue 💭 . Sorry for the inconvenience @TillaTheHun0

**Comment by TillaTheHun0** [comment]
@efekarakus good catch. 

Yep, we have separate a AWS account for the App and then each of our environments.

**Comment by efekarakus** [comment]
We have a fix for the issue here: https://github.com/aws/copilot-cli/pull/3559/, #3562

**Comment by codekitchen** [comment]
I was just coming here to report the same issue. Thanks for the quick fix! We'll keep an eye out for the next release.

**Comment by efekarakus** [comment]
Thanks @codekitchen ! we're in the process right now of making the changes and we will post here once we have the patch release done!

**Comment by efekarakus** [comment]
Hi folks! @codekitchen @TillaTheHun0 @coledcrawford 
We just released the fix: https://github.com/aws/copilot-cli/releases/tag/v1.18.1 🎉 
Apologies for all the inconvenience 🙇 

Please let us know if you run into any issues, thank you!

**Comment by alxvallejo** [comment]
I'm facing this exact same error when initializing a new app with a profile that I set up with the following permission policies:

```
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/IAMFullAccess
        - arn:aws:iam::aws:policy/AWSCloudMapFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonECS_FullAccess
        - arn:aws:iam::aws:policy/AWSLambdaFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
```

The error is:

```
✘ upload manual/templates/hhldash-prod/5dc867b499a4b92fac2ba06a24ad776c98cc183eaa05b8352de0210813573ddf.yml to bucket stackset-hhldash-infrast-pipelinebuiltartifactbuc-kqsuxj0v820k: AccessDenied: Access Denied
	status code: 403, request id: 4NX1JTG3S0G6TS99, host id: j0xsU0d4rjjq7vcFFv/WAiIAfWAABn+NDRhdwYu9e0iHv9qL5uXIuRCSYk2sI1eCTNPNqSQNMQU=
```

The first comment on this thread refers to `EnvironmentManagerRole`. What is that? I see nothing in the documentation on how to properly configure the profile in the first place. I'm assuming this requires some type of s3 permissions but for what bucket?
