### ISSUE TITLE
Copilot Default Resources

### ISSUE THREAD

**Issue by vredcloud** [aws/copilot-cli#3593]
https://aws.github.io/copilot-cli/docs/developing/custom-environment-resources/

In the section "Modifying Copilot's default resources" under the above URL it says "When you select the default configuration, Copilot follows [AWS best practices](https://aws.amazon.com/blogs/containers/amazon-ecs-availability-best-practices/) and creates a VPC with two public and two private subnets, with one of each type in one of two Availability Zones."

Following the link to the AWS ECS best practices, it does not list anywhere that having two public and two private subnets is a best practise. 

Also, if I am using copilot to deploy only an internet facing web tier what benefit would the two private subnets provide?

**Comment by efekarakus** [comment]
Hi @vredcloud !

We unfortunately cannot default to three availability zones because not all regions have at least 3 availability zones. For instance: https://aws.amazon.com/about-aws/global-infrastructure/regions_az/
> *New customers can access two Availability Zones in US West (Northern California).

Instead, we default to 2 availability zones and allow clients when running `copilot env init` to specify they'd like to use 3 AZs instead if their region supports it. Hope that makes sense!

> Also, if I am using copilot to deploy only an internet facing web tier what benefit would the two private subnets provide?

You can specify an internet-facing service using the [`network.vpc.placement` field](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-vpc-placement):
```yaml
network:
  vpc:
    placement: 'private'
```
The main benefits of launching tasks in private subnets are:
1. Not hitting public IP address limitations (you're deploying a service with large number of tasks) - if all your ECS tasks are launched with public IP addresses it's possible that there are no more public IP addresses available and the task launch fails. By placing your tasks in private subnets behind a NAT gateway, this limitation won't occur.
2. Compliance reasons - perhaps you have some external security requirements that require your tasks to be launched in private subnets or all egress traffic to come up from a set of static IP addresses: https://github.com/aws/copilot-cli/discussions/1914

**Comment by vredcloud** [comment]
@efekarakus 

Thanks so much for the reply.
