### ISSUE TITLE
Failed to create ecr repository despite success message

### ISSUE THREAD

**Issue by AndrchiamusI** [aws/copilot-cli#3600]
# Description

When running the init service command there is an error message

    ❯ copilot svc init                           
    Note: It's best to run this command in the root of your workspace.
    Service type: Backend Service
    Dockerfile: ./Dockerfile
    ✔ Wrote the manifest for service xxx at ../../copilot/xxx/manifest.yml
    Your manifest contains configurations like your container size and port.
    
    ✘ Failed to create ECR repositories for service xxx.
    
    ✘ add service xxx to application services: adding service xxx resources to application services: operation 40 for stack set xxx-infrastructure failed

If I run it again then I get a success message but still no repo

    Note: It's best to run this command in the root of your workspace.
    Manifest file for service xxx already exists. Skipping configuration.
    ✔ Manifest file for service xxx already exists at ../../copilot/xxx/manifest.yml, skipping writing it.
    Your manifest contains configurations like your container size and port.
    
    ✔ Created ECR repositories for service xxx.
    
    Recommended follow-up actions:
      - Update your manifest ../../copilot/xxx/manifest.yml to change the defaults.
      - Run `copilot svc deploy --name xxx --env test` to deploy your service to a test environment.

The subsequent svc deploy command fails as there is no repository to push too.

I then created an ECR repository manually adding the tags `copilot-service` and `copilot-application` allong with AllowPushPull permissions but the svc deploy command fails with the following issue

    - An ECS task definition to group your containers and run them on ECS              [delete complete]    [2.2s]
        Resource handler returned message: "Invalid request provided: Create T                                
        askDefinition: Container.image repository should not be null or empty.                                
         (Service: AmazonECS; Status Code: 400; Error Code: ClientException; R                                
        equest ID: f84cb6bd-585e-429f-8235-1fafe4460e51; Proxy: null)" (Reques                                
        tToken: 12a32146-ff72-a6ec-2c71-f43a70c1d1f4, HandlerErrorCode: Invali                                
        dRequest) 

I tried to delete the service and start again without success, 

    Service name: xxx
    Sure? Yes
    ✔ Deleted service xxx from environment stage.
    ✘ Failed to delete resources of service xxx from application services.
    ✘ removing xxx service resources from application: operation 41 for stack set xxx-infrastructure failed

I have also tried  remove traces of services that I have found with no luck:

- Deleting the `/copilot/<app>/<service>` Parameter Store secret
- Deleting template for service stored in s3 

When there is a commit id available the container.image property is not empty but it is `':<git commit id>' `so further confirms that repository is not being forwarded to the cloud formation despite successful docker build and push.

# Additional Context
One complexity that is worth mentioning is that when copilot was first setup it was setup using two environments (prod and stage) with different AWS accounts. This seemed to work initially but then I realised that a copilot app does not work switching between accounts (very clear when using pipelines) so then I created a separate app for the production AWS Account. But it means that original app contains two copilot env: stage and a production env which is not easily deleted. As such I have to often specify environment flag for copilot commands which ordinarily do not need them else I get a permission error.  This is not so much an issue as most cli commands now support --env argument. 

I have also tried disabling the secondary env with no luck - to disable I removed the parameter store secret for that environment.

# Version
Copilot 1.18.1

**Comment by dannyrandall** [comment]
Hey @Andrchiamus! Thanks for all the details here. Couple of questions for you to help narrow down the issue:
- Are you using (when running `copilot svc init`) credentials for the account the application was created in?
- If so, can you log in to the application account CloudFormation console, go to the Stack Set instance for your app you're trying to `svc init` in (it should be named something like `StackSet-<App Name>-infrastructure`, and look at the Events tab and see if you can see any errors there and share them here?

**Comment by AndrchiamusI** [comment]
Thank you kindly for the response.

> Hey @Andrchiamus! Thanks for all the details here. Couple of questions for you to help narrow down the issue:
> 
> * Are you using (when running `copilot svc init`) credentials for the account the application was created in?

I have AWS_PROFILE env variable setup for the correct account. 

I also tried to make a new service to the same app after deleting the param store secret which copilot uses to detect environments (copied it for backup). Copilot then defaults to the only remaining environment but still errors. 

> * If so, can you log in to the application account CloudFormation console, go to the Stack Set instance for your app you're trying to `svc init` in (it should be named something like `StackSet-<App Name>-infrastructure`, and look at the Events tab and see if you can see any errors there and share them here?

There are no events for the Month of May at all. The last event present is from early April which was concerned with deleting a service. For completeness the errors were ECR related and to do with the repo still containing images:

    The following resource(s) failed to delete: [ECRRepomigrateDASHtimelineDASHdataDASHdynamodb, ECRRepotimelineDASHdata, ECRRepocomrade, ECRRepomigratingDASHaccounts, ECRRepotrials, PipelineBuiltArtifactBucket, ECRRepoauth, ECRRepotimeline, ECRRepostudies].

and

    Resource handler returned message: "The repository with name `<app>/<service>'`in registry with id 'xxx' cannot be deleted because it still contains images (Service: Ecr, Status Code: 400, Request ID: xxx, Extended Request ID: null)" (RequestToken: xxx, HandlerErrorCode: GeneralServiceException)

**Comment by dannyrandall** [comment]
Interesting🤔 - this looks similar to https://github.com/aws/copilot-cli/issues/3455.

> it was setup using two environments (prod and stage) with different AWS accounts.

Could you try checking which apps are in each of the two AWS accounts? So for each AWS Account you have, run the following:
```
$ AWS_PROFILE=<profile for account> copilot app ls
$ AWS_PROFILE=<profile for account> copilot app show
```
And share the output of those commands here?

**Comment by AndrchiamusI** [comment]
> Interestingthinking - this looks similar to #3455.

It does look similar. I too was about to delete the app as it is only the development account that is broken and our production services has only ever had a single environment but have held off a couple of days to help with this issue.



> $ AWS_PROFILE=production copilot app ls

This returns two applications which are also present when running with AWS_PROFILE=dev . The dev account also has two other applications which are now more artifacts.



> $ AWS_PROFILE=production copilot app show

The command was executed within the mono repo so the cli did not return interactive mode rather it returned the app in question.


    About
    
      Name     xxx
      Version  v1.0.1 (latest available: v1.0.2)
      URI      
    
    Environments
    
      Name        AccountID     Region
      ----        ---------     ------
      production  xxx  eu-west-2
    
    Workloads
    
      Name                           Type                       Environments
      ----                           ----                       ------------
      xxx                           Load Balanced Web Service  production
      xxx  Worker Service             production
      xxx                            Backend Service            production
      xxx                       Load Balanced Web Service  production
      xxx                   Backend Service            production
      xxx                  Backend Service            production
      xxx                       Load Balanced Web Service  production
      xxx                  Backend Service            production
      xxx            Scheduled Job              production
      xxx              Scheduled Job              production
      xxx             Scheduled Job              production
    
    Pipelines
    
      Name
      ----

(I liked pipelines but stopped using it early on due to multi account conflicts)


> $ AWS_PROFILE=production copilot app show

This returns much the same but has a different version

    About
    
      Name     xxx
      Version  v1.0.0 (latest available: v1.0.2)
      URI      

What are the versions and how do I update them?

**Comment by dannyrandall** [comment]
Hey! Sorry for the delayed response.

I'm think that there is probably some permissions issue going on attempting to create an ECR repo in the wrong account.🤔

So you've got app `a` and app `b`, both of which have a version deployed to account `dev` (`AWS_PROFILE=dev`) and `production` (`AWS_PROFILE=production`). The `dev` account app `a` has a `production` environment in the `production` account and a `dev` environment in the `dev` account. There is another version of app `a` deployed in the `production` account, with a single `production` environment. Is all of that correct?

Which application/environment/account are you trying to deploy to on `svc init`? Which credentials are you using? Also, if you go to the repo and run `cat copilot/.workspace`, which application is specified?

**Comment by AndrchiamusI** [comment]
Good afternoon, cat copilot/.workspace is the same for `a` and `b`

> So you've got app `a` and app `b`, both of which have a version deployed to account `dev` (`AWS_PROFILE=dev`) and `production` (`AWS_PROFILE=production`). The `dev` account app `a` has a `production` environment in the `production` account and a `dev` environment in the `dev` account. There is another version of app `a` deployed in the `production` account, with a single `production` environment. Is all of that correct?

Yes exactly, because of the shared app name the production service in `a` was essentially inaccessible once `b` was created some time a go.

The thing was that for some time this setup worked and services could be created and managed in app `a`.

I have since re-created app `a` without the production environment.

**Comment by Lou1415926** [comment]
Hello @Andrchiamus! Thanks for the information and I'm sorry for the churn 🙇🏼‍♀️ !

From the discussion thread, my first guess is that the credential used for the operations might be mixed up a little. 

You've confirmed @dannyrandall 's recap - these would be the results of running the commands:
```console
AWS_PROFILE=production copilot app ls
a
b

AWS_PROFILE=development copilot app ls
a
b

```
This means that you have four applications in total. From Copilot's stand point, these four applications would be considered independent to each other, and do not share any resources. Does this sound like what you want?

---

Going back to the "ECR repository" issue that you opened the issue for. My first guess is something similar to ⬇️  happened:
1. `copilot svc init --app a` was executed against *`AccountProduction`*. This creates an ECR repository to _the application `a` that is deployed in `AccountProduction`_. 
2. Then `copilot svc deploy --app a --env production` was executed against __`AccountDevelopment`__. What happens at this point is that Copilot assumes the `EnvManagerRole` of the environment `production` of __the application `a` that is deployed in `AccountDevelopment`__. This `EnvManagerRole` has access to resources of __the application `a` that is deployed in `AccountDevelopment`__, but not any resources of _the application `a` that is deployed in `AccountProduction`_. Hence, it cannot pull the repository information because that's part of _the application `a` that is deployed in `AccountProduction`_.

I apologize for my use of *italic* and __bold__ font 🙇🏼‍♀️  - they are used only to create visual difference between __`AccountDevelopment`__ and _`AccountProduction`_ so that it may be easier to read.

Does this ⬆️  sound possible to you?

**Comment by AndrchiamusI** [comment]
Okay, sorry for any confusion. I will try and get my setup as I remember it but it was long time ago.

When I first used copilot I created one app and two environments. At the time I thought I could use Copilot across AWS accounts and it seemed to work initially as I could choose an AWS_PROFILE when running `copilot env init`. So I created one for my dev and one for my production. However, I quickly learned that copilot did not work across accounts by friction.

So I then created a new app `AWS_PROFILE=production copilot app init` followed by an env of name production. Of course I named the app the same as that created in dev aws account so .workspace was consistent.

So if I were to run `AWS_PROFILE=production copilot app ls` I would get my service name that is common to both.

If I were to run `AWS_PROFILE=production copilot env ls` I would get 
- `production`

If I were to run `AWS_PROFILE=development copilot env ls` I would get 
- `production`
- `development` 

But of course `production` environment from this application is now completely inaccessible as it would default to the production app if AWS_PROFILE=production is set.

For a long time this setup was not an issue as I could get around some quirks in the CLI and permissions when trying to run stuff on development by ensuring `--env development` flag. Some cli commands did not have this an errors would occur due to permissions. But on the the whole we were able to deploy new and update existing services in the AWS_PROFILE=development application until the ECR error appeared.

Does that make sense?

**Comment by Lou1415926** [comment]
Thank you for the detailed information! 

> But of course production environment from this application is now completely inaccessible as it would default to the production app if AWS_PROFILE=production is set.

You could access this `production` environment by setting the profile to `development`:
```
AWS_PROFILE=development copilot env show
```
This should show you this particular `production` environment instead of the other one. 

That is, say you deployed an application in account `X`,  and under this application an environment in account `Y`. To access this environment, you will need to use the profile that points to account `X`, not `Y`. When Copilot sets up the environment for you, it grants  `X` permissions to access the environment resources. 

If you used account `X` to set up your application (i.e. `AWS_PROFILE=profile-X copilot app init`), you can use this profile to run every single command in Copilot without needing to switch profile, even if you select another profile when creating the environment:

```shell
AWS_PROFILE=profileX copilot app init --name my-app# Create application in account X
AWS_PROFILE=profileX copilot env init --name test --profile profileY # Deploy environment test in account Y
AWS_PROFILE=profileX copilot env show --name test # This works because X has permissions to view environment in account Y
AWS_PROFILE=profileX copilot svc init --name api # This adds service "api" to application :my-app"
AWS_PROFILE=profileX copilot svc deploy --name api --env test # This deploys the service in environment "test". Note that even though "test" is in account Y, you should still assume your profile X to run the command, instead of profile Y.
```

Does this help with clarifying the credential set up?

**Comment by AndrchiamusI** [comment]
That does help. I never thought to look for a --profile flag as I was set on using AWS_PROFILE=.

I love the tool and would have loved for the CLI to have worked more seamless across accounts when I initially got started. As it did work but realised later when trying to use pipelines that there was friction and ended up opting for alternative CI/CD.

Would profile work for the below? As this command tries to create ECR repositories?
```copilot svc init --name api```

**Comment by Lou1415926** [comment]
`copilot svc init` does not have a `--profile` flag. Only `copilot env init` does - if you don't specify the `--profile` flag, it will prompt you for "what profile/credential you'd like to use for this environment".

I would suggest first deleting the service via `copilot svc delete` first!

In the original description, you mentioned that you ran `svc init` twice: the first attempt failed but the second went through although without the actual repository. I think it's likely a false positive - because of how CFN stackset is used - that the second execution appeared to go through. This is an improvement that we should make on our end to prevent this kind of false positive.

Therefore, to start from a cleaner state, I suggest running `copilot svc delete` against that service first. If you see an error like `"✘ removing xxx service resources from application: operation 41 for stack set xxx-infrastructure failed"`, we can go to the CloudFormation console, look for the stack named `stackset-xxx-infrastructure-randomstring` to see what specific error is causing this failure. Sometimes it fails to update the stackset because the ECR repo still has image in it, in which case you can manually delete those images and then try `svc delete` again.

Please let me know how it goes!

**Comment by AndrchiamusI** [comment]
Thanks again for the response, that makes sense.

I opted a couple of weeks ago to simply re-create the copilot stack as the conflict was not in production - so I cannot help by running that command sorry.

I am happy to close and am pleased to here the false positive will be picked up and maybe the user exp of multiple accounts in one workspace e.g. profiles, code pipelines etc.

**Comment by AndrchiamusI** [comment]
I am happy if you wish to close.

Thanks again - I love the product!
