### ISSUE TITLE
`app deploy` ChangeSetName validation error

### ISSUE THREAD

**Issue by sonofachamp** [aws/copilot-cli#362]
Currently the ChangeSetName being referenced for `app deploy` includes the input `tag`. If that input tag includes `.`'s a `ValidationError` is returned by the call to `CreateChangeSet`.

```
$ ./archer app deploy --tag v1.0.1
```
```
Error: deploy application: create change set: ValidationError: 1 validation error detected: Value 'myapp-test-v1.0.1' at 'changeSetName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*
```

NOTE: The ChangeSet update flow only happens when an application has been deployed once before and the stack was created. Subsequent deployments will go through ChangeSets to apply updates.

I think there are a couple potential options to fix this:
* Change the `ChangeSetName` value to not use input tags
* Replace invalid characters to valid characters in the existing `ChangeSetName`
* Use the `StackName` value for both `StackName` and `ChangeSetName`
  * Might not be an option as it seems `ChangeSetName`s should be unique so if a ChangeSet failed to apply we would have clashing names

**Comment by git823** [comment]
It seems that this issue is outdated. If we specify "v1.0.1" as a value of --tag for `copilot svc deploy`, the error does not occur. I tested with v0.2.0.

Currently, ChangeSetName does not include the value of tag.
https://github.com/aws/copilot-cli/blob/191e9e7721e20d8ef212be389d905c8d1107347e/internal/pkg/aws/cloudformation/changeset.go#L16-L18

We might be able to close this issue.

BTW, current prefix for ChangeSetName is "ecscli-". ECS CLI v2 was former name, so I think "copilot-" is more cool.

**Comment by efekarakus** [comment]
This issue is outdated as mentioned above! Closing :)
