### ISSUE TITLE
Fetching a docker image from a private jfrog artifactory, upload on ecr and deploy on ecs

### ISSUE THREAD

**Issue by yasinkayade** [aws/copilot-cli#3787]
Hi,
I create a small project fetching docker image of a spring boot project from a private jfrog artifactory, uploading on AWS ECR and deploying it on AWS ECS via copilot in a cicd pipeline. 
I need credentials and certificate to fetch the docker image. AFAIK from https://github.com/aws/copilot-cli/issues/2101, there is a parameter with the name credentials (under image) to store in secretsmanager and use them. So the image part of manifest.yml:

```
image:
  credentials: arn:aws:secretsmanager:…….  /* username and password*/
  location: location_of_docker_image_in_jfrog_artifactory
  port: 8080
```

But I still get 403 Forbidden. Because I need a certificate in order to be able to fetch the image from private artifactory because of security issues. I would ask how to put the certificate into manifest.yml file (or to put to secretsmanager and refer in manifest.yml file)?
And generally, has copilot a capability to fetch the docker image from a private artifactory with username, password and certificate, and then upload it to ECR? 

BR,

**Comment by uttarasridhar** [comment]
Yes, the reason for `403 forbidden` is because as of today, ECS doesn't support pulling images from privately signed registries for Fargate tasks. [See issue](https://github.com/aws/containers-roadmap/issues/1301). I suspect that is why you are considering pushing to ECR as a workaround. 

Unfortunately, the `image.location` [field](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-location) in the manifest is passed directly to Amazon ECS as-is. And, we don't have a built-in capability to fetch the docker image from a private artifactory, upload to ECR, and reset `image.location` as ECR repository. 

You could solve this with two options:

1. Right before the copilot deploy workflow, you could pull from artifactory and push to the ECR repository provisioned as part of `copilot svc init`. 
The repository follows the format `<app_account>.dkr.ecr.<aws_region>.amazonaws.com/<app_name>/<svc_name>`

OR

2. Create a new Dockerfile with `FROM <artifactory_url>` and update the manifest `image.build.dockerfile` [field](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build) to point to that. I think this should work if your local docker daemon is configured correctly with the certificate trust store.

Let us know if either option works for you. Thank you.

**Comment by yasinkayade** [comment]
Hi @uttarasridhar 
thanks for the answer. I will try them. 
I have another issue. I created a spring cloud config server deployed on AWS ECS (fargate). Config client is a service also deployed on ECS (same VPC). How can we inject config server uri as spring.cloud.config.uri and spring.config.import in client service? I tried possible options like dns name but when deploying client service we still get "No spring.config.import property has been defined". What should I take into consideration in this structure?

**Comment by uttarasridhar** [comment]
Would you be able to elaborate more on your setup? 

1. Are you setting these URIs through [environment variables](https://aws.github.io/copilot-cli/docs/developing/environment-variables/) in the manifest? 
Some articles [here](https://spring.io/guides/topicals/spring-boot-docker/) and [here](https://stackoverflow.com/questions/46715072/passing-env-variables-to-docker-spring-boot) could be possible leads on ensuring env vars are passed correctly to the spring container.

2. Do you use `copilot pipeline` to deploy the server and client? We recently introduced [a way to configure](https://aws.github.io/copilot-cli/docs/manifest/pipeline/#stages-deployments) the ordering of deployments. Maybe that will help ensure server uri is available before client is deployed.

Hope these pointers are helpful.

**Comment by efekarakus** [comment]
Hi @yasinkayade ! To add onto @uttarasridhar 's recommendation, each ECS service in an environment gets a deterministic [service discovery endpoint](https://aws.github.io/copilot-cli/docs/developing/service-discovery/).

Therefore, for option 1 using the [environment variables](https://aws.github.io/copilot-cli/docs/developing/environment-variables/) you should be able to define the endpoint as:
```yaml
# Replace <name for your service> with the name of your config client service.
variables:
  SPRING_CONFIG_URI: 'http://<name for your service>.${COPILOT_ENVIRONMENT_NAME}.${COPILOT_APPLICATION_NAME}.local'
```

And then it [looks like in spring boot](https://stackoverflow.com/a/35535138/1201381) you can use the env variable in the config:
```yaml
spring.cloud.config.uri = ${SPRING_CONFIG_URI}
```
