### ISSUE TITLE
`svc deploy` stack update fails after update to `v1.20.0`

### ISSUE THREAD

**Issue by raethlo** [aws/copilot-cli#3799]
Hey all 👋🏻 

we have a github actions workflow that deploys our services. After upgrading the workflow's `copilot` version to latest we've started seeing errors where the deploy failed on `EnvControllerAction` stack upgrade failure with message `No updates are to be performed.` 

example log output below:

```
 - Updating the infrastructure for stack whatever-staging-api                 [update rollback in progress]  [29.8s]
  The following resource(s) failed to update: [ExecutionRole, EnvControllerAction].                                                                                                
  - Update your environment's shared resources                                [update failed]                [3.6s]
    Received response status [FAILED] from custom resource. Message return                                   
    ed: No updates are to be performed. (Log: log path) (RequestId: 56c93a92-c69e-4b78-ac93-09996717939f)                                                                                                     
  - An IAM Role for the Fargate agent to make AWS API calls on your behalf    [update failed]                [18.9s]
    Resource update cancelled  
```

logs from the envcontroller update lambda look like so:
```
START RequestId: 15c600b2-68e7-441f-8eee-d784a1aa6cf0 Version: $LATEST
--
2022-07-20T15:14:55.255Z	15c600b2-68e7-441f-8eee-d784a1aa6cf0	INFO	Caught error ValidationError: No updates are to be performed..
2022-07-20T15:14:55.255Z	15c600b2-68e7-441f-8eee-d784a1aa6cf0	INFO	Responding FAILED for physical resource id: envcontoller/whatever-staging/api
END RequestId: 15c600b2-68e7-441f-8eee-d784a1aa6cf0
REPORT RequestId: 15c600b2-68e7-441f-8eee-d784a1aa6cf0	Duration: 648.94 ms	Billed Duration: 649 ms	Memory Size: 512 MB	Max Memory Used: 78 MB	Init Duration: 465.03 ms
```

I looked over the [release blog post](https://aws.github.io/copilot-cli/blogs/release-v120/#continuous-delivery) and it doesn't look like there is a related breaking change. My hunch is it could be sth to do with the env manifest changes as it is the only thing that seems somehow related, will try to debug more and post an update if I find sth.

Any idea what could be the issue?

**Comment by efekarakus** [comment]
Hi @raethlo !

Thank you for creating the issue 🙇 , do you know what fields changed in the service manifest that triggered the github action? so that we can try reproducing the issue from our side.

edit1: Do you use the `http.alias` field in the manifest today?

**Comment by raethlo** [comment]
Hey @efekarakus thanks for such a quick reply ⚡. So - the manifest actually didin't change - only the image has and that could be the source of the problem - which made me realize we might be using `copilot svc deploy` incorrectly. 

I think that the error I reported is just a different messaging or perhaps missing graceful handling of when the stackset actually doesn't have a change. When I dowgraded to `v1.19.0` I'm seeing a message (that I og attributed also to when just the image didn't change):
```
Environment staging is already on the latest version v1.10.1, skip upgrade.
Note: Set --force to force an update for the service.
✘ execute svc deploy: deploy service api to environment staging: deploy service: change set with name copilot-6faa9516-4f53-4a66-b609-688090247086 for stack whatever-staging-api has no changes: Resource creation cancelled
```

So I poked through `copilot` cli's code and realized we are running
```
copilot deploy --name $COPILOT_SVC --env $COPILOT_ENV --tag $RELEASE_VERSION
```
with the image `location` set, but the `tag` option does not have an effect when `location` is set in the manifest. (which is sort of related [to this gitter thread](https://gitter.im/aws/copilot-cli?at=628fe295deea5616bbc90a57)). Hence the stack really does not have a change (as location always points to the same `latest` image). To fix that we should not use the `--tag` opt but rather have  `location: image_arn:$RELEASE_VERSION` specified in the manifest (as per [the docs](https://aws.github.io/copilot-cli/docs/developing/manifest-env-var/)). Will check what the fix will do and report back.

> edit1: Do you use the http.alias field in the manifest today?

yes, we're using `http.alias` & acm certs mounted on `env init` that validate domains managed outside of route 53.

**Comment by Lou1415926** [comment]
Hello @raethlo - Thank you for the detailed information! 

Just to double check before I write down my suggestions! Could you check your environment template version, by going to the CloudFormation console, and look for `Metadata.Version` in your environment template? Is it less than v1.12.0?

<img width="746" alt="Screen Shot 2022-07-20 at 11 26 21 AM" src="https://user-images.githubusercontent.com/79273084/180055599-2d3c1c34-2874-4321-87ef-7055dfe7d6ac.png">


Also, what is your environment stack status? Is it in `UPDATE_FAILED_ROLLBACK_COMPLETE`?

**Comment by raethlo** [comment]
Hey @Lou1415926 looks like the env template is on `1.10.1` and the lb service's stack ended in `UPDATE_FAILED_ROLLBACK_COMPLETE` the environment stack status was ✅ (not triggered/modified by the build)

<img width="818" alt="image" src="https://user-images.githubusercontent.com/4778650/180063240-0c5f60bb-363d-495a-b98d-23665c8ae471.png">

I've fixed our usage of `svc deploy` and the deploy went through as expected on `v1.19` and I'm trying `v1.20` at the moment - will let you know when I have additional details.

**Comment by Lou1415926** [comment]
@raethlo Thank you!! My suggestion is to upgrade the environment template version to `v1.12.0`! 

Since `Copilot v1.20.0` involves [a change in the environment creation workflow](https://aws.github.io/copilot-cli/blogs/release-v120/#environment-manifest), you will first need to first [generate an environment manifest](https://aws.github.io/copilot-cli/blogs/release-v120/#migrating-existing-environments):
```bash
# 1. Navigate to your git repository.
$ cd my-sample-repo/

# 2. Create the directory for the "staging" environment.
$ mkdir -p copilot/environments/staging

# 3. Generate an environment manifest for my staging environment.
$ copilot env show -n staging --manifest > copilot/environments/staging/manifest.yml
```
The generated manifest should contain all the configurations that you've specified with `env init` back in the day. For example, it'll contain information about the certificates that you imported.
 
Then, you can upgrade your environment by
```bash
# 4. Deploy the environment.
$ copilot env deploy -n staging
```
In the future, whenever you need to upgrade your environment, you can just run `copilot env deploy` without needing to repeat step 1-3.

After your environment finished upgrading, you can deploy the service again by `copilot svc deploy`. This hopefully should fix the issue for you!

---
Here are some explanations on what happened.

Previously, services do not report their aliases to the environment if the certificates are imported. After `Copilot v1.20.0`, they start to do so regardless whether the certificates are imported or not. This is why the `EnvControllerAction` is triggered - the service is trying to pass on its alias information to the environment.

`EnvControllerAction` tries to update the environment stack's `Parameters` with the newly-reported aliases. However, changes in `Parameters` does not necessarily trigger resource updates in the environment stack. If it doesn't, CloudFormation will complain with "no updates are to be performed error".

Environment version `v.12.0` overcomes this limitation by adding `Aliases` into its `Outputs`. This makes the environment template to take in the new `Parameters`, even when there is no actual resource changes. Versions less than `v1.12.0` does not handle this for changes in `Aliases`. This is why I suggested an environment upgrade, which can be performed by `env deploy` which needs environment manifest as a  prerequisite.

Hope this makes sense and please let me know how it goes 🤞🏼 !

**Comment by megane42** [comment]
I have same circumstance as @raethlo, and @Lou1415926's suggestion works perfectly 🎉 

Note that `copilot env deploy` uploads "CertificateValidationFunction" function to S3, so we need to add a policy that allows `s3:PutObject` to the IAM role used in github actions ([like this](https://github.com/aws/copilot-cli/issues/2615#issuecomment-881034132)).

Thank you for your quick issue reporting and quick debugging!

**Comment by raethlo** [comment]
Hey @Lou1415926, thanks for the suggestions and the write-up. As @megane42 mentioned, deploying the envs indeed did fix the issue 🎉 

Once again thanks all for such a quick reaction and all your help 🖤
