### ISSUE TITLE
CodePipeline Access Denied Amazon S3

### ISSUE THREAD

**Issue by dexternunag** [aws/copilot-cli#4115]
I'm trying to create a pipeline for my containerized apps. But I'm having this issue where I don't have access to my s3 bucket. Did I miss something? Would really appreciate some help. Thank you!

I'm using AWS Copilot CLI v1.22.1

![image](https://user-images.githubusercontent.com/18132231/198251577-0852ca10-e247-435d-a0e4-2190cc94c7a3.png)

**Comment by iamhopaul123** [comment]
Hello @dexternunag I think this is related to https://github.com/aws/copilot-cli/issues/4040#issuecomment-1260104205. Let me know if it doesn't work.

**Comment by dexternunag** [comment]
Hi @iamhopaul123 sorry for the late reply and thank you for your comment. I've done this procedure mentioned in [#4040](https://github.com/aws/copilot-cli/issues/4040#issuecomment-1260104205) but still having the same issue.

**Comment by huanjani** [comment]
Hi @dexternunag! 
I'm sorry you're still facing this issue. Are you able to deploy that service to the `test` environment manually (by running `copilot svc deploy`, outside of the pipeline? 
I see that you're using Copilot v1.22.1, but was your app created with that version? If not, maybe try `copilot app upgrade` and make sure your environments are all up to date with `copilot env deploy`?

**Comment by dexternunag** [comment]
Hello @huanjani, yes I'm able to deploy it manually by running `copilot svc deploy`.
My app wasn't created with v1.22.1. I was using v1.14.0 at first before trying to create a pipeline. 
Tried running `copilot app upgrade` and it says `Application is already on the latest version v1.1.0`

**Comment by huanjani** [comment]
Hmm. Let's dig!

Would you mind going to the CloudFormation console, finding the stack of your service, then go to Parameters tab?
What is the value of ServiceDiscoveryEndpoint parameter?

Still in the CloudFormation console, go to the stack that looks like `StackSet-[appName]-infrastructure-[something similar to 669d438f-1509-4440-a4c0-786d4ab74cd2]`. For the `PipelineBuiltArtifactBucket`, do you see:
```
    OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
```
?

**Comment by dexternunag** [comment]
Here's my `PipelineBuiltArtifactBucket`
![image](https://user-images.githubusercontent.com/18132231/199687070-19086182-06c6-450c-9ed4-a35708b9ec4d.png)

For the ServiceDiscoveryEndpoint parameter I don't have any in parameters tab.

**Comment by huanjani** [comment]
Sorry-- please look in your environment CFN stack under Parameters for the ServiceDiscoveryEndpoint. Thank you!

**Comment by dexternunag** [comment]
Is this correct?
![image](https://user-images.githubusercontent.com/18132231/199852374-3f7fe55c-92e6-44c1-86b4-ad319311d957.png)

**Comment by huanjani** [comment]
It should be the stack called `[appName]-[envName]`

**Comment by dexternunag** [comment]
![image](https://user-images.githubusercontent.com/18132231/199877862-2b344ff6-dc38-49a4-bdac-8933c8d15eb5.png)

**Comment by huanjani** [comment]
Hm.... Everything looks as it should! So strange.
Are you doing anything extra-- cross-account, permissions boundaries, etc?

**Comment by dexternunag** [comment]
I'm not sure. I'm currently under a company. The account I use for this is only an IAM user with a power user policy attached to it.

**Comment by dannyrandall** [comment]
Hey @dexternunag! Could you try upgrading your test environment before triggering your pipeline again? If you run `copilot env deploy --name test`, that should do it.

Next, could you ensure your pipeline is using the latest version of Copilot? To do that, check your `buildspec.yml` for lines like this:
```
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.23.0
      - mv ./copilot-linux-v1.23.0 ./copilot-linux
```

If it isn't, update the buildspec to the latest version and run `copilot pipeline deploy` to update the pipeline.

Let me know that resolves the issue or if that doesn't work!

**Comment by dexternunag** [comment]
@dannyrandall I followed your instructions and still having the same issue. 😕

**Comment by dannyrandall** [comment]
Dang!😔 Hmm, ok - I'm curious about two things:
1. Could you share what version your Environment template is? You can find it by opening the CloudFormation Console, looking at your environment stack (named `appName-envName`) template, and it's the `Metadata.Version` field you see at the top
2. Was your pipeline created in a different account than your app? Or just in general - are there multiple accounts or regions used in your application? I'm curious about the setup of the app - which account/region for each env.

**Comment by dexternunag** [comment]
@dannyrandall my `Metadata.Version` is at v1.13.0 😨
![image](https://user-images.githubusercontent.com/18132231/201513044-c58d5c18-d2d8-4710-95b6-55c553c2f45d.png)

**Comment by dannyrandall** [comment]
No worries - that is the latest version!😊 Could you share details of how the app is structured? Also, it might be helpful if you could share the bucket policy for the bucket the pipeline is pushing the templates to. You can find it by:
1. Open the app stack set instance in the CloudFormation console (It should be called `StackSet-appName-infrastructure-randomString`)
2. Go to the Resources tab and click on the link to the S3 bucket with the LogicalID of `PipelineBuiltArtifactBucket`
3. In the S3 console, go to the permissions tab
4. Bucket policy JSON is on that page!

**Comment by dexternunag** [comment]
I'm currently working on a microservice architecture app.

| ...
|- api-service 
|- web1-service 
|- web2-service 
|- web3-service 


![image](https://user-images.githubusercontent.com/18132231/201718756-d9293417-e974-4a4f-a3db-b3ac2bc2ebda.png)

**Comment by huanjani** [comment]
Hi @dexternunag!
Your bucket policy looks fine to me. This is so puzzling! Can you find out from your company if there are IAM permissions boundaries?

**Comment by huanjani** [comment]
Another thought: would you mind deleting your `copilot/pipelines/[pipelineName]/buildspec.yml` file then running `copilot pipeline init` again, now that you've updated your Copilot versions? 

Since the Copilot version you were on when you created your pipeline buildspec, we have made some fairly significant changes to the buildspec template. So now, even though you have upgraded, the buildspec file is still the one outdated one generated previously.

Hopefully that'll do it! 🤞🏼

**Comment by huanjani** [comment]
Hi, @dexternunag! 
Just wanted to check in to see if recreating the buildspec helped you get unstuck! Knowing if that was the solution will help us troubleshoot more efficiently in the future.
Thank you!

**Comment by dexternunag** [comment]
@huanjani still having the same issue after deleting my buildspec.yml and running `copilot pipeline init` again
I haven't asked about the IAM permissions boundaries yet, will get back to you guys about this one. Thank you!
![image](https://user-images.githubusercontent.com/18132231/202855707-d31b1526-2f4f-4a89-a67a-309bd78669cb.png)

**Comment by paragbhingre** [comment]
@dexternunag I could see that you are using the latest version in buildspec.yml. Did you make sure to commit this to the repository?

**Comment by dexternunag** [comment]
Hi @paragbhingre, I'm now having this issue
![image](https://user-images.githubusercontent.com/18132231/203520446-4ee93296-71a4-4be9-8255-9dc7771fea0e.png)

**Comment by huanjani** [comment]
Hi @dexternunag! 
This is just a guess, because I'd need to see the logs of the build to know for sure, but is there something about having reached the docker pull rate limit in the logs? If so, please try this workaround: https://github.com/aws/copilot-cli/issues/1869#issuecomment-765643674
Thanks!

**Comment by dexternunag** [comment]
Hello @huanjani I'm encountering this issue after I tried this  workaround 
https://github.com/aws/copilot-cli/issues/1869#issuecomment-765643674

![image](https://user-images.githubusercontent.com/18132231/203892376-54ad1ca7-d555-411e-93a6-b4e25ce6836a.png)

**Comment by Lou1415926** [comment]
Hello @dexternunag  👋🏼 ! I am sorry for the churn :( 

I see there are so far three issues:
1. `POST_BUILD` phase failed. (build stage)
2. The "Cannot perform an interactive login from a non TTY device" issue. (build stage)
3. Resolve the "Access Denied" problem that this issue was initially created for. (deploy stage)

Let's first work on issue 1&2! After they are resolved, let's then dive into 3 if it is still there during deploy stage 🤞🏼 .

---
#### 1. `POST_BUILD` failed

To help me understand why `POST_BUILD` failed, could you
1. Go to the exact build that you mentioned [here](https://github.com/aws/copilot-cli/issues/4115#issuecomment-1324816307). You should see a page that looks like:
<img width="2176" alt="Screen Shot 2022-11-30 at 3 14 46 PM" src="https://user-images.githubusercontent.com/79273084/204929398-d69839f5-717d-47be-b67b-acdef04d205c.png">

2. Scroll through "Build logs" and look specifically for this block
```console
[Container] 2022/11/30 21:53:15 Running command for env in $pl_envs; do
    tag=$(sed 's/:/-/g' <<<"${CODEBUILD_BUILD_ID##*:}-${env}" | rev | cut -c 1-128 | rev)
    for svc in $svcs; do
    ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
    if [ $? -ne 0 ]; then
      echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
      exit 1;
    fi
    done;
    for job in $jobs; do
    ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
    if [ $? -ne 0 ]; then
      echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
      exit 1;
    fi
    done;
  done;

< a bunch of logs...........> # <------[!]


[Container] 2022/11/30 21:53:24 Running command ls -lah ./infrastructure
```

The bunch of logs generated in `[!]` should contain the actual error that caused your `POST_BUILD` to fail. **Would you please let me know what are the errors that you saw there?**


----

#### 2. Cannot perform an interactive login

In `[!]`, if you did not find an error that looks like:
> toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading

You do *not* need https://github.com/aws/copilot-cli/issues/1869#issuecomment-765643674. In this case, feel free to revert the changes that you made following https://github.com/aws/copilot-cli/issues/1869#issuecomment-765643674 -  issue 2 solved 🎉 .


However, if you do see the "toomanyrequests" error, then can you take a look at [this SO discussion](https://stackoverflow.com/questions/60583847/aws-ecr-saying-cannot-perform-an-interactive-login-from-a-non-tty-device-after) and see if it helps?


Thank you! And sorry for the churn :(
