### ISSUE TITLE
Pipeline fails if service cloudformation stack in non updatable state: UPDATE_ROLLBACK_COMPLETE.

### ISSUE THREAD

**Issue by CorinWilkins** [aws/copilot-cli#4167]
If a service fails it's circuitbreaker on startup the stack is rolled back. With a state UPDATE_ROLLBACK_COMPLETE.
The pipeline is unable to redeploy this stack and manual intervention is required with `copilot svc deploy`. 

Not all of our team is on the same arch so not everyone can do this.
We don't really want engineers doing manual deploys in prod.

Can the pipeline be made to fix non updateable stacks?

**Comment by dannyrandall** [comment]
Hey @CorinWilkins! Thanks for reporting this issue. Am I getting this timeline right?
1. Push a commit
2. Pipeline builds service
3. Pipeline deploys with Cloudformation
4. Service fails a few times and ECS circuitbreaker triggered, making the stack start rollback
5. Stack ends in `UPDATE_ROLLBACK_COMPLETE` state

Once the pipeline and stack are in this state, you try pushing a commit again to trigger the pipeline, and step 3 is blocked this time because the stack is in state `UPDATE_ROLLBACK_COMPLETE`? But if you run `copilot svc deploy`, the stack updates just fine?

**Comment by CorinWilkins** [comment]
Yes, exactly right.

**Comment by huanjani** [comment]
Hi, @CorinWilkins! 

I just tried to reproduce your situation. 
I created and deployed a working pipeline, then pushed a breaking change to get one service's CFN stack in `UPDATE_ROLLBACK_COMPLETE` state. I _was_ able to push more changes to trigger the pipeline again and get it back into a successfully deployed state, without any manual intervention. 🤔

**Comment by CorinWilkins** [comment]
When I first reported this issue we were running copilot v1.21. I thought that might explain the discrepancy between your experience and my own. However we've since upgraded to v1.23 and still see this issue.

Our pipelines run in a different account to our environments and apps. Could this be the reason why?

**Comment by iamhopaul123** [comment]
> Our pipelines run in a different account to our environments and apps. Could this be the reason why?

Hello @CorinWilkins. Could you put more details on this? Theoretically the pipelines should always be in the same account as the app (could be different from the env accounts). Unless the pipelines are not created and managed by Copilot?

**Comment by CorinWilkins** [comment]
I mispoke, I mean our pipelines run in different accounts to our envs and
services. The pipelines are provisioned by copilot.

**Comment by iamhopaul123** [comment]
Gotcha. Have two quick questions:

1. "The pipeline is unable to redeploy this stack" happens when circuit breaker is triggered and the stack ends up being in "UPDATE_ROLLBACK_COMPLETE" status. Is that correct?
2. What error msg did you observe from the pipeline if the pipeline is unable to redeploy the stack?

**Comment by huanjani** [comment]
@CorinWilkins, I received your email re: this issue happening again. Would you mind adding more details about what you're seeing? Thanks!

**Comment by CorinWilkins** [comment]
I've not seen this in a while. The last occurrence was caused by something non copilot related. I'm satisfied that this is no longer an issue.

**Comment by huanjani** [comment]
That's great to hear! Thanks!
