### ISSUE TITLE
copilot manifests written outside application directory

### ISSUE THREAD

**Issue by miketheman** [aws/copilot-cli#4195]
When starting a fresh app with the latest release of copilot, the manifests are written outside 
```shellsession
$ pwd
/Users/miketheman/workspace/miketheman/exampleapp

$ copilot version
version: v1.23.0, built for darwin

$ copilot init
...
Workload type: Request-Driven Web Service
Service name: app
Dockerfile: ./Dockerfile
...
✔ The directory copilot will hold service manifests for application exampleapp.

✔ Wrote the manifest for service app at ../../../copilot/app/manifest.yml
```

The generated manifest files are not part of the working directory. Note the `../../../` prefix, which translates to my home directory.

I noticed it after I also ran `copilot env init`:
```shellsession
$ ls -lR ~/copilot
drwxr-xr-x - miketheman 19 Nov 17:36 app
drwxr-xr-x - miketheman 19 Nov 17:37 environments

/Users/miketheman/copilot/app:
.rw-r--r-- 1.5k miketheman 19 Nov 17:36 manifest.yml

/Users/miketheman/copilot/environments:
drwxr-xr-x - miketheman 19 Nov 17:37 prod

/Users/miketheman/copilot/environments/prod:
.rw-r--r-- 592 miketheman 19 Nov 17:37 manifest.yml
```

Is it possible I have something misconfigured which is leading to this behavior? The [docs tell me](https://aws.github.io/copilot-cli/docs/manifest/overview/#:~:text=Manifest%20files%20are%20stored%20under%20copilot/%3Cyour%20service%20or%20job%20name%3E/manifest.yml.) that the files should be stored within the working directory.

**Comment by miketheman** [comment]
Related: #3294

**Comment by miketheman** [comment]
I've dug further into this, and it looks like this behavior manifests (pun! 😆 ) when the `copilot init` is invoked in a directory that is not explicitly a git-enabled directory (aka doesn't have a .git/` directory) (I found [some logic here](https://github.com/aws/copilot-cli/blob/6a50bcb45f4aafb723df31b9cf6f56954174dd24/internal/pkg/workspace/workspace.go#L476-L480))

It's entirely probably I overlooked the warning emitted when running `copilot init` before I had run `git init`:
```shellsession
Note: It's best to run this command in the root of your Git repository.
```
so that's my fault, not yours. 😉 

I'm **guessing** that there's some logic that tries to walk the directory tree upwards? I dug around and couldn't find it.

If nothing else, the `delete` step should be able to find the workspace files the same way it creates them, so that errors like https://github.com/aws/copilot-cli/issues/2253#issuecomment-831552864 don't happen.

**Comment by miketheman** [comment]
Also, the docs should reflect "if it's not in a git repo, manifests will end up in your homedir" if that's the desired outcome.

**Comment by paragbhingre** [comment]
@miketheman Sorry for the inconvenience, we are trying to give flexibility to the customer to run commands from different places in the filesystem. Also, if Copilot finds a `/copilot` directory anywhere in the current directory or five directories up from the current directory, then it uses that directory to store all the manifests and `.workspace` file. We have already opened an issue, which you mentioned in your comment, to make improvements in this behavior. 

>Also, the docs should reflect "if it's not in a git repo, manifests will end up in your homedir" if that's the desired outcome.

I don't think that's the case; we show the following note in order to make sure the Copilot directory gets created in the same directory as your git repository. And if it is available anywhere up to five levels in the directory, then Copilot uses that one instead of creating a new one.

```shellsession
Note: It's best to run this command in the root of your Git repository.
```

> If nothing else, the delete step should be able to find the workspace files the same way it creates them

We will be taking care of this one as a part of the issue that is open. 

Thank you for reporting this one though, it helps us prioritize the issues.

**Comment by miketheman** [comment]
Thanks for the follow up! I'll close this one in favor of the other open issue.
