### ISSUE TITLE
Native image building and uploading for sidecar container

### ISSUE THREAD

**Issue by iamhopaul123** [aws/copilot-cli#4254]
As a Copilot user, I have a Rails/React app which is currently using Puma as the app server and Nginx as the web server. Nginx is currently installed in the app Dockerfile and launched in the Docker entrypoint. I'd like the run Nginx as a sidecar instead. However, since I need to also have the React and Active Admin assets compiled and included in the Nginx image, it means that I would be updating that image somewhat frequently, and it's somewhat of a pain to do that as Copilot doesn't handle updating sidecar images automatically.

**Comment by carlosaherrera** [comment]
Similarly, I have a Django app that has two sidecars configured: one for a Celery worker and another for a Celery beat. It appears Copilot only allows you to configure a sidecar by pointing to an image URL. But I would like to have the option to point to a Dockerfile instead so that Copilot can build, upload, and deploy it for me automatically, like it currently does for the main Django app.

**Comment by efekarakus** [comment]
Hi folks!!

I'm really excited to say that AWS Copilot v1.27 is out and you can now build and push sidecar container images! 🚀 

* Guide: https://aws.github.io/copilot-cli/docs/developing/sidecars/#image-build
* Blog post: https://aws.github.io/copilot-cli/blogs/release-v127/#build-and-push-container-images-for-sidecar-containers
* Release notes: https://github.com/aws/copilot-cli/releases/tag/v1.27.0

I'll close the issue now! If you have any questions, feedback, or suggestions please feel free to open new GitHub issues 🥳
