### ISSUE TITLE
How to manage multiple pipeline for multiple accounts

### ISSUE THREAD

**Issue by thesabbir** [aws/copilot-cli#4274]
I have two accounts and two pipelines.

1. Prod  (deploys to prod env)
2. Test (deploys to test env)

And two accounts:
1. A (For prod env)
2. B (For test env)

I intend to deploy the Test pipeline to account 2 and the Prod pipeline to account 1. 
Both pipelines seem to be deployed to account 1.

**Comment by efekarakus** [comment]
Hi @thesabbir !

I wonder if this guide would help: https://aws.github.io/copilot-cli/blogs/release-v116/#create-multiple-pipelines-per-branch

* Are you planning to have two different git branches? so that when changes are merged to `mainline` they get deployed to the test environment, and if they get merged to `prod` then they go to prod.

If so hopefully the guide linked above should help you guide through the setup. Let me know if I misunderstood anything :)
