### ISSUE TITLE
Image reuse across different services and pipeline

### ISSUE THREAD

**Issue by sorinrinse** [aws/copilot-cli#4385]
Is there a way to force deployment from a pipeline? Or anybody has any ideas how to fix this?

I have multiple services (X, Y, Z) and I only build the image for service X and then I reuse that image on Y and Z. 

Service X:
```
image:
  build:
    dockerfile: Dockerfile
```

Service Y and Z:
```
<id>.dkr.ecr.us-east-1.amazonaws.com/<app>/<service>:${COPILOT_ENVIRONMENT_NAME}
```

Pipeline (how I set the tag):
```tag=$(echo $env | sed 's/:/-/g' | rev | cut -c 1-128 | rev)```

The image will get the environment tag and it will leave the previous release untagged, now the problem is that when the pipeline runs it will not update all the services.

A quick solution would be to use a hardcoded version + environment name but I would like to keep it as simple as possible and I would also like to keep the behavior of untagged images so the lifecycle policy in ECR removes them.

**Comment by iamhopaul123** [comment]
Hello @sorinrinse. Can you use `export tag=$(sed 's/:/-/g' <<<"${CODEBUILD_BUILD_ID##*:}-${env}" | rev | cut -c 1-128 | rev)` so that the tag changes every time to make sure service Y and Z gets a different tag? In terms of manifest changes, Service X stays the same, and Service Y/Z will have

```yaml
<id>.dkr.ecr.us-east-1.amazonaws.com/<app>/<serviceX>:${tag}
```

where `${tag}` is the env var we now export.

**Comment by sorinrinse** [comment]
Hello @iamhopaul123! Thank you very much for the suggestion, it seems to be working now.
