### ISSUE TITLE
Prefix job's log groups with `aws/vendedlogs/`

### ISSUE THREAD

**Issue by Lou1415926** [aws/copilot-cli#4389]
According to [the step functions doc](https://docs.aws.amazon.com/step-functions/latest/dg/bp-cwl.html) and [the CloudWatch doc](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html), it is recommended to prefix state machine's log groups with `/aws/vendedlogs` to get around the resource policy limit issue.

Several complexities that we have to consider:
1. What to do with existing jobs that have been logging to the log groups without the prefix? 
2. Which log group to fetch logs from during `copilot job logs`?

Related issue: #4338 

Related readings/discussions:
[Bug with LoggingConfiguration](https://repost.aws/questions/QURc2glxBETSe3Q6Y0UwcpQg/bug-with-logging-configuration)
[【AWS】SAMでStep Functionsを利用してCloudWatch Logsにログ出力する際、sam deploy時にエラーが発生するケースがある](https://qiita.com/tmiki/items/1ad26ca38f8b68e00df1)

**Comment by zaf187** [comment]
Hi @Lou1415926,

I faced this issue today in my org. When i tried to deploy a job, i got the message: "The CloudWatch Logs Resource Policy size was exceeded." and the job failed to create.

I followed your guidance to check the actual document using the command:
`aws logs describe-resource-policies --region us-east-1`. In the output i noticed there are some residual entries in there left by a previous copilot application that were not cleaned up after the application was deleted.

I would suggest that all log groups used by copilot to be prefixed with `/aws/vendedlogs/` to avoid this problem.

Thank you

**Comment by iamhopaul123** [comment]
## Proposal

> What to do with existing jobs that have been logging to the log groups without the prefix?

We need to respect the current job log group lifecycle (can only be deleted when users run `job delete`). More specifically, we'll create a new prefixed log group and keep the old log group but start shifting new logs to the new log group. 

> Which log group to fetch logs from during copilot job logs?

We can fetch logs from the new prefixed log group if it exists. Otherwise we fallback to the old log group.

Overall I think this is a reasonable solution because we still make it possible for users to see logs from the old log group (through cloudwatch console or aws cli). At the same time, `copilot job logs` serves logs from relatively recent job task (which is its primary use case).

**Comment by huanjani** [comment]
This fix has been released in v1.29.0: https://github.com/aws/copilot-cli/releases/tag/v1.29.0!
