### ISSUE TITLE
Listener rule priority already exists

### ISSUE THREAD

**Issue by anne-montoya** [aws/copilot-cli#4532]
Specifically, the error is in HTTPSListenerRule

`Resource handler returned message: "Resource of type 'AWS::ElasticLoadBalancingV2::ListenerRule' with identifier 'One or more priorities not found (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: 4d85f81b-1fd1-4ec0-97e2-47ef4dc741dc, Extended Request ID: null)' already exists." (RequestToken: 318bcb60-c823-a2ba-6b21-6180adaed7d6, HandlerErrorCode: AlreadyExists)`

We're updating our services' ports. Some are successfully updated and some of them failed with this error.

- Our copilot app was initialized with --domain flag so all of our services' base path is '/'
- We made sure that the port are not in conflict with each other

**Comment by Lou1415926** [comment]
Hello @anne-montoya 👋🏼  Thank you for the extra bit of information - very helpful for me to rule out #1455! Were the deployments in parallel? For any one of the services that failed with this error before, are you able to deploy it now, if deployed individually?

**Comment by anne-montoya** [comment]
Hello @Lou1415926, thanks for the response. Yes, were deploying through pipeline. I tried deploying via `copilot svc deploy` just now without other deployments. Still getting the same error.

**Comment by Lou1415926** [comment]
Strange! I wonder what is your Copilot's version?  You can run `copilot version` to check.

Also, you mentioned that the failure occurred after changing port - can I understand this as "previously, the services were successfully deployed and running"?

Finally, i wonder which `port` field did you change? Is it `image.port`?

Let me show you what I've tried - perhaps you can find something different than your set up.
1. I created an app with domain `copilot app init --domain my.domain.com`
2. I then create the environment just by running `copilot env init` and `copilot env deploy` without changing any config in the env manifest
3. I created to LBWS: `copilot svc init --name web-a` and `copilot svc init --name web-b`. The default manifest produced for `web-b` has `http.path: 'web-b'`, I changed it to `http.path: '/'` 
4. Deployed both services. Now they are accessible via `web-a.test.app.my.domain.com` and `web-b.test.app.my.domain.com` respectively.

**Comment by xinye2005** [comment]
We're trying to update the host and container port numbers in our Fargate services, which were deployed using copilot. For some services, we noticed the port number of the alb target were not updated. But some were updated successfully. We checked the priorities of the HTTPS:443 listener rules, there're no conflicts/duplicates. But in the CloudFormation stack events, we found HTTPSListenerRule update failed due to the reason above mentioned by Anne. What we couldn't figure out was why some services were updated successfully and some failed? Do we need to update the service one by one according to their listener rule priority?

**Comment by anne-montoya** [comment]
To answer your questions @Lou1415926 ,
- Copilot version: v1.21.1
- Yes, services were successfully deployed and running before the change. Also when I reverted back the services that had failed to their original ports, they also successfully deployed
- Yes, changed the port in image.port and on Dockerfile too
- Yes, that's what our set up looks like.

**Comment by Lou1415926** [comment]
Thank you @anne-montoya  for the information!

To answer your question @xinye2005:

> Do we need to update the service one by one according to their listener rule priority?

This *could have been* an issue. When Copilot deploys a service, the priority of a new listener rule is assigned by:
1. Making HTTP requests to fetch the existing ruled' priorities
2. Assign to the new listener rule a priority that does not clash with any of the existing ones. Usually this is done by -1 from the min of the priorities, or +1 from the max of the priorities, depending on the rule's path (which in your case, are all '/')

The operation ⬆️  is not atomic. Therefore, when deployments are made in parallel, it is indeed sometimes possible that two rules end up getting the same priority, causing the error that you saw. 



---


Back to the original issue @anne-montoya!  I wonder what is the copilot version that you used in your pipeline❓ You can look at the buildspec and find this somewhere towards the top of the `buildspec.yml`:
```
version: 0.2
phases:
  install:
    runtime-versions:
      docker: 19
      ruby: 2.6
    commands:
      - echo "cd into $CODEBUILD_SRC_DIR"
      - cd $CODEBUILD_SRC_DIR
      # Download the copilot linux binary.
      - wget -q https://ecs-cli-v2-release.s3.amazonaws.com/copilot-linux-v1.21.1 # ⬅️  Look at this
```

---


>  Also when I reverted back the services that had failed to their original ports, they also successfully deployed

Would you please try the following ❓ 
1. Choose one of the services that have failed before whose port was reverted to the original port
2. Update its manifest, Dockerfile, and perhaps the application code, so that it uses the new port that you initially wanted
3. Run `copilot svc deploy`, individually, again, for this service

##### Why I asked

My guess now is that your pipeline was using an older version than `v1.21.1` when we still had a known bug for assigning priorities when multiple services have `http.path: '/'`. 

This ⬆️ (using older version in pipeline) could be why your manual `copilot svc deploy` failed again.


Sorry for the churn! Hope this is not shooting in the dark 🤞🏼 The above actions are not prescription, but steps that can help me understand what the underlying issues are. Once we figure that out, I can provide a recommendation of path forward.

**Comment by anne-montoya** [comment]
Our pipelines are using copilot-linux-v1.21.0

I deploy a single service (that failed before) via `copilot svc deploy` using the latest version `v1.26.0` and `v1.21.1`. Still getting the same error

 ```
    Resource handler returned message: "Resource of type 'AWS::ElasticLoad                                       
    BalancingV2::ListenerRule' with identifier 'One or more priorities not                                       
     found (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID:                                       
     bdb2fb28-6077-4eee-8462-8d5fb375b71e, Extended Request ID: null)' alr                                       
    eady exists." (RequestToken: 81ef3f1d-5405-1fb6-1845-2d2196d57511, Han                                       
    dlerErrorCode: AlreadyExists)
```

**Comment by Lou1415926** [comment]
> I deploy a single service (that failed before) via copilot svc deploy using the latest version v1.26.0 and v1.21.1. Still getting the same error

Can you move to CloudFormation console, look at that ⬆️ service's stack, go to "Event" tab.

Look for an event whose status reason is "User Initiated" around the time you made the deployment in the ⬆️  reply.

Is there any `HTTPSRulePriorityAction` or `XXXRulePriorityAction`  above the event? Similar to ⬇️ 


![Screenshot 2023-02-24 at 10 22 17 AM](https://user-images.githubusercontent.com/79273084/221231624-0411faa0-45a4-435b-a0b4-5fe05b56709f.png)

If you are comfortable sharing a screenshot that'd help as well 👍🏼

**Comment by anne-montoya** [comment]
![Screenshot 2023-02-25 at 1 05 17 AM](https://user-images.githubusercontent.com/83938994/221242315-aa86b6bc-aec2-4309-9ad5-e4f9e45d583c.png)

There is no HTTPSRulePriorityAction.
Is this because our copilot version is outdated? We're planning to update our environment (pipeline etc..) to the latest version to rule out the possibility that this error is caused by old version of copilot.

**Comment by Lou1415926** [comment]
I think we should try to trigger the rule priority action, so that the listener rule is assigned a new priority that does not clash with any existing ones.

You can update the value of `http.path`, and then run `copilot svc deploy`. This will trigger the `HTTPSRulePriorityAction`. And then, you can change `http.path` back to `'/'` (suppose root path is what you want), and then `copilot svc deploy` again. This will trigger `HTTPSRulePriorityAction` again, but the resulting priority should still be valid.

If this still didn't help, could you send me a screenshot of your current rule priories? It'd be in the console EC2 > load balancers > select the load balancer in question > Listeners (near the bottom of the screen) > select the 443 listener > go to "Rules"

<img width="1457" alt="Screenshot 2023-02-24 at 11 37 44 AM" src="https://user-images.githubusercontent.com/79273084/221250149-7a2af33e-2622-4c04-98bc-157d7b761875.png">
<img width="1449" alt="Screenshot 2023-02-24 at 11 38 39 AM" src="https://user-images.githubusercontent.com/79273084/221250154-f8bdac22-3505-4e22-a03b-37a524bd7ffc.png">


#### Why
Based on the screenshot you provided, my next guess is that the priority assigned for your listener rule clashed with other services' rules. Somehow the rollback did not help it getting an valid priority (I am not sure why. I would have expected it to get a valid priority during rollback). 


The rule priority action is only triggered under these scenarios:
1. When you run `copilot svc deploy` for the first time
2. When you have a change to `http.path`
3. When Copilot updates the code for the rule priority action, and you upgraded to that version 

I guess subsequent deployments did not trigger the rule priority action, so the priority remained invalid.

---

> Is this because our copilot version is outdated? 

You were on v1.21.1 (local) and v1.21.0 (pipeline). There didn't seem to be any relevant work that would affect your listener rule priorities after that version. So I think your Copilot version probably was't the issue. However, it is indeed encouraged to keep your Copilot version somewhat up-to-date to keep up with features and bug fixes. I'd recommend tackle the upgrade after we fix the current deployment issues!

**Comment by anne-montoya** [comment]
![Screenshot 2023-02-25 at 2 02 36 AM](https://user-images.githubusercontent.com/83938994/221255448-48d1fad5-74fe-439e-b737-d880a82a8072.png)
It works. I can see the rule priority action event and the service successfully deployed. So does this mean that on the failed services we need to change the http.path to a "dummy path" and change it back after to avoid this error?

Also, when I checked the services that deployed successfully, they don't have the rule priority action too.

**Comment by Lou1415926** [comment]
> does this mean that on the failed services we need to change the http.path to a "dummy path" and change it back after to avoid this error?

Yeah please do so for the other failed services as well!

> Also, when I checked the services that deployed successfully, they don't have the rule priority action too.

This is interesting. Suppose all services were running successfully before the initial failure, each of them should have valid rule priorities. If the CI/CD update didn't trigger  `XXPriorityAction` for any of the services, then the priority should have remained valid. If the CI/CD update did trigger the `XXPriorityAction` on some service, the action should have been able to find a valid priority that did not clash with any existing rules, during update or during rollback. I don't have a good theory of why some of them initially failed, yet. Was there any manual operations that were performed before, on the listener rules?

**Comment by anne-montoya** [comment]
> Was there any manual operations that were performed before, on the listener rules?

Yes, we added a service on ecs that is not deployed through copilot. We need this to be internet facing so we manually edited the listener rules of the load balancer that our copilot env is using as well as add record in Route 53.

**Comment by anne-montoya** [comment]
> You can update the value of http.path, and then run copilot svc deploy. And then, you can change http.path back to '/' then copilot svc deploy again

Anyway, this solves our problem. Thank you @Lou1415926 :raised_hands:

**Comment by Lou1415926** [comment]
> We need this to be internet facing so we manually edited the listener rules of the load balancer

That is probably why. For example, perhaps a service has a rule of priority "49999", but during the manual operation it was changed to "49998", and some other rule took "49999". During the update, the service keeps trying to use "49999" because the `PriorityAction` wasn't triggered, clashing with the other rule.

I will close this issue for now! Feel free to add a comment or reopen if you still see relevant errors!
