### ISSUE TITLE
healthchecks clogging logs

### ISSUE THREAD

**Issue by cworkschris** [aws/copilot-cli#4564]
Hi all,

I'm assuming that these log entries are the healthchecks - but they are not that useful to me, they don't even include timestamps.  And it seems like we are limited to 10000 log entries (or does that only apply when the --limit option is used) so it is forcing useful log entries to be lost.  Is there a way to configure or filter this out?

```
copilot/api/01bea95b7a104 INFO:     127.0.0.1:59608 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:59620 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:42608 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:42616 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:50206 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:50220 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:36448 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:36452 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:45480 - "GET / HTTP/1.1" 200 OK
copilot/api/01bea95b7a104 INFO:     127.0.0.1:45488 - "GET / HTTP/1.1" 200 OK
```

**Comment by iamhopaul123** [comment]
Hello @cworkschris `copilot logs` by default only shows the last 10 logs. However, you can always increase the limit by setting `--limit`. And logs won't be lost and they'll be accessible in CloudWatch. It seems like the logs are there because of the ELB health check which is necessary. Sorry for now we don't have a nicer way to filter logs using the cli.

Also, if you are thinking about filtering logs to keep only useful logs, you could use [firelens our sidecar pattern](https://aws.github.io/copilot-cli/docs/developing/sidecars/#sidecar-patterns) which under the hood uses [fluentbit](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file). It'll allow you to have more control over the logs of your app (filtering, sending to multiple destinations etc.)

**Comment by cworkschris** [comment]
Thanks for the great tips @iamhopaul123 !  Understood
