### ISSUE TITLE
Best practice for accessing existing RDS database

### ISSUE THREAD

**Issue by qnm** [aws/copilot-cli#4598]
I'm enjoying working with Copilot. It does soooo much of what I need it to do!

However, I have an existing RDS database (Postgres) which is managed outside of Copilot.

What is considered best practice when I wish to connect a Copilot service to it? My solution for now is to store the database URL in secrets - but this doesn't allow for secret rotation or service discovery.

How are other folks doing this? I don't particularly want Copilot to manage my databases, but will consider it.

**Comment by efekarakus** [comment]
Hi @qnm !

Thank you so much for the kind words ❤️ 

> What is considered best practice when I wish to connect a Copilot service to it? My solution for now is to store the database URL in secrets - but this doesn't allow for secret rotation or service discovery.

Your solution I think is the most common route for folks! 
1. For secret rotation, as far as I know most folks use the `--force` flag with `copilot svc deploy` to force the ECS agent that's retrieving the secret to pull the latest content.
2. The alternative is to fetch the secret from within the container instead of relying on the `secrets` field in the manifest, but that's a lot of undifferentiated code. As far as I know, AWS SecretsManager provides libraries to connect to databases and handle rotation.

If you go with the second approach, I believe you'll have to write an [addon](https://aws.github.io/copilot-cli/docs/developing/addons/workload/) for an IAM ManagedPolicy to give permissions to the secret.
I'm happy to help writing it if you prefer to go with this option!

> but this doesn't allow for secret rotation **or service discovery.**

Can you elaborate what you mean by service discovery for the database? As far as I know the database host gets a stable DNS name (e.g. `mydbcluster.cluster-123456789012.us-east-1.rds.amazonaws.com`) that's always stable even if the writer instance changes over time.

Hope this helps!

**Comment by qnm** [comment]
Thanks for you prompt response!

> If you go with the second approach, I believe you'll have to write an [addon](https://aws.github.io/copilot-cli/docs/developing/addons/workload/) for an IAM ManagedPolicy to give permissions to the secret.
> I'm happy to help writing it if you prefer to go with this option!

Thanks - I might take you up on that! The current system is sufficient, but will address this in the coming weeks.

> Can you elaborate what you mean by service discovery for the database? As far as I know the database host gets a stable DNS name 

Yes - you are right. I assume I can just CNAME these to gain a more pleasant hostname.
