### ISSUE TITLE
Domain in Route 53 not recognised as part of the account

### ISSUE THREAD

**Issue by qnm** [aws/copilot-cli#4607]
I've recently set up a new `tooling` account in order to separate control and workloads when deploying Copilot as our new deployment tool.

I wish to use an app with an existing subdomain, which was previously zoned in the 'production' account, but now has a zone in the 'tooling' account.

When I set up the app in tooling, I see the following

```
Note: The account does not seem to own the domain that you entered.
Please make sure that aws.mycorp.com is registered with Route53 in your account, or that your hosted zone has the appropriate NS records.
To transfer domain registration in Route53, see:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/domain-transfer-to-route-53.html
To update the NS records in your hosted zone, see:
https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/SOA-NSrecords.html#NSrecords
```

What mechanism is used to determine this? I have verified using `dig` that the nameservers match the zone in `tooling` not the former `production` account, and they resolve.

```
qnm> aws route53 list-hosted-zones
{
    "HostedZones": [
        {
            "Id": "/hostedzone/Z066719526ZM52MA9BSHH",
            "Name": "aws.mycorp.com.",
            "CallerReference": "a58c9weff55b6e376e",
            "Config": {
                "Comment": "",
                "PrivateZone": false
            },
            "ResourceRecordSetCount": 4
        }
    ]
}
```

Secondly, what (if any) is the impact of this? Possible certificate problems later?

**Comment by efekarakus** [comment]
Hi @qnm !

> What mechanism is used to determine this? I have verified using dig that the nameservers match the zone in tooling not the former production account, and they resolve.

If it resolves to the tooling account then it should be all good. That's exactly what Copilot does so it's strange that the log statement got printed. Here is what Copilot does:
https://github.com/aws/copilot-cli/blob/499bb1ca37b11a9955377594ac8c8826bb7d7ce8/internal/pkg/aws/route53/route53.go#L83-L86

1. We get the NS records of the R53 hosted zone.
2. We get the NS records for the domain itself.
3. We make sure the domain's NS records match R53's.

If it looks good to you feel free to ignore the warning.

> what (if any) is the impact of this? Possible certificate problems later?

That's exactly right, when Copilot generates an ACM certificate for your [Load Balanced Web Services](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-alias) if the domain is not owned by you then the certificate validation with ACM will fail. So in order to try to prevent confusion down the line, we try to catch as many issues early on.

However, it sounds like your DNS delegation is all good so it should be OK to move forward.

In the worst case in case the ACM certificate validation fails with Copilot, we also provide an "escape hatch" in environment manifests: https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public-certificates. 
```yaml
http:
  public: 
    certificates:
      - arn:aws:acm:${AWS_REGION}:${AWS_ACCOUNT_ID}:certificate/13245665-cv8f-adf3-j7gd-adf876af95
```
If you bring your own certificates, then you can skip initializing `copilot app init --domain` and Copilot won't try to generate an ACM certificate for you.

Hope that answers your questions!

**Comment by qnm** [comment]
Hi @efekarakus 

I pushed ahead and it all worked fine! :+1: 

Very smooth setup, love it!
