### ISSUE TITLE
Can you have multiple services under the same Load Balanced Web Service?

### ISSUE THREAD

**Issue by guyschlider** [aws/copilot-cli#4613]
Hi,

First, let me mention that we are **very** happy users of copilot and you guys are doing a fantastic job.

I have a quick question, we are looking for a solution where we can deploy the same image to different containers and configure the load balancer to route requests based on the URL path to those containers - is that something copilot supports or might be supported?

I do know that it's [possible with ELB](arn:aws:elasticloadbalancing:us-east-1:074022272136:loadbalancer/app/plyba-Publi-617USN50B1KX/bc74ddbcc397ae2c)

**Comment by KollaAdithya** [comment]
Hi @guyschlider !

Thank you for your kind words! We are so glad to hear that you are finding Copilot to be a valuable tool 

In order to route requests based on URL path what you can do is to set the path of Application Load balancer in the workload manifest. [link](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#http-path) You need to have unique path for each Load balanced service.

Let me know if this works for you.
