### ISSUE TITLE
Move Copilot App To Another Region

### ISSUE THREAD

**Issue by zmad5306** [aws/copilot-cli#4636]
We need to move our Copilot app o another AWS region. Moving the workloads was accomplished easily by creating new environments and deploying to them. But how do I move the Copilot Resources (AWS Systems Manager >> Parameter Store, Code Pipelines, etc.)?

**Comment by KollaAdithya** [comment]
Hey @zmad5306 !
If I am understanding correctly did you create a new app in another region and trying to move the existing environments and workloads to that new Copilot app?

**Comment by zmad5306** [comment]
@KollaAdithya  No I created the Copilot App in region x and it had environments in region x and y. We are eliminating region x but all the Copilot resources (Parameter Store for Copilot, Pipelines, etc) are still in region x. We have deleted the Copilot environments in region x. We'd like to eliminate all resources in region x and only have resources in region y. Basically its the Copilot metadata and Pipelines we'd like to move to region y.

**Comment by KollaAdithya** [comment]
Hi @zmad5306 👋  
SSM parameters are not moved. I'm happy to provide some additional information and help you understand how Copilot stores these parameters!

1. Firstly, suppose you create an application by running `copilot app init --demo` in the `us-west-2` region.
2. Next, you create a new environment called `envX ` in the `us-east-1 ` region. A new parameter is then added to Parameter Store in the `us-west-2` region because the Copilot app is in that region.
3. Later, you create another environment called `envY`  in the `us-east-2` region, and Copilot also adds a new parameter to Parameter Store in the `us-west-2` region because the Copilot app is located there.
4. Finally, if you want to delete the `envX` environment, simply run `copilot env delete --name envX`. This will automatically delete the parameter for `envX` from the parameter store in the `us-west-2` region and also all the other resources.

Coming to the pipeline scenario:
First you need to update the pipeline `manifest.yml` such that you delete the `envX` from `stages` and add the new environment `envY` and then run `copilot pipeline deploy`. Pipeline will still be in `us-west-2` i.e where the application is created.

let me know if this helps.

**Comment by zmad5306** [comment]
@KollaAdithya 

> Pipeline will still be in us-west-2 i.e where the application is created.

That's what I'm wanting to change, I want the application to be in us-east-1.

**Comment by iamhopaul123** [comment]
Hello @zmad5306. Sorry but for now I don't think there's a safe way for Copilot to migrate your existing app to another region :(
