### ISSUE TITLE
Can not upgrade template to latest after it rolled back successfully

### ISSUE THREAD

**Issue by arjanelolong2022** [aws/copilot-cli#4755]
I ran `copilot app upgrade`, and it failed due to missing ECR that was deleted manually. It successfully rolled back.

The issue is that when I run `copilot app upgrade` again, it says `Application is already on the latest version v1.1.0, skip upgrade.`. This is despite the `StackSet-<application>-infrastructure` showing still on `TemplateVersion v1.0.2`.

**Comment by dannyrandall** [comment]
Hey @arjanelolong2022! What version does copilot return when you run `copilot version`? Also, there should be two app stacks for your app - can you tell me what both of their versions is when you look at the stack in the CFN console? The first is the `StackSet-<application>-infrastructure` that you shared, the second is named `<application>-infrastructure-roles`.

**Comment by arjanelolong2022** [comment]
Hi @dannyrandall 

```
❯ copilot version
version: v1.27.0, built for darwin
```

For `<application>-infrastructure-roles` the TemplateVersion  version is v1.1.0. Any recommendation on how I can reconcile those templates?

**Comment by dannyrandall** [comment]
Ok, I was able to recreate your situation! I think I understand the issue. If you go to the CloudFormation console -> StackSets (in the sidebar) -> `<app>-infrastructure`, is the version `v1.1.0`?

If that's the case, then what I think happened is that when you ran `copilot app upgrade`, the CloudFormation _stack set_ template updated, but your _stack set **instance**_ failed to update because of the missing ECR repo. Subsequently, your _stack set **instance**_ rolled back to the previous template version (`v1.0.2`), while the _stack set_ template has the updated version, because it doesn't roll back when its instances fail to deploy. Copilot gets the current version from the _stack set_ template, which is why Copilot thinks you're on version `v1.1.0`.

---
So, to resolve this we'll have to deploy a successful version of the stack set so that it's in sync with the stack set instances.

**Option 1**: If you're ok deleting the service, run `copilot svc delete --name <service name>`. That should delete the ECR repo from the app stack, and _should_ make the stack set and stack set instance in sync.

**Option 2**: If you don't want to delete the service, you can do the following:
1. Recreate the ECR repo in the region that the stack set instance failed to deploy in. If you look at the stack set template, search for the `AWS::ECR::Repository` resource with `RepositoryName` equal to the name of the ECR repo you deleted. That should be the _exact_ name of the ECR repo you create in the ECR console (you can paste it into "Repository name", it should be `<app name>/<service name>`)
2. Add the tags to the ECR repo you just created. They are:
```
copilot-application: <app name>
copilot-service: <service name>
```
3. Create a temporary, fake service (we won't deploy it, so this won't cost anything!): `copilot svc init --name deleteme --svc-type "Load Balanced Web Service" --image "nginx" --port 80`. After this step, your stack set should look like it's all good!
4. Delete the temporary service: `copilot svc delete --name deleteme`. You can delete the generated service folder from your git repo as well (`copilot/deleteme`).

After doing one of the above options, all of your stack set instances (even if you only have 1!) should say "Succeeded" under the "Detailed Status" column in the StackSet section of the CloudFormation console. Let me know how it goes!

**Comment by arjanelolong2022** [comment]
That worked. Thank you @dannyrandall
