### ISSUE TITLE
facing error "Runtime parameter of nodejs12.x is no longer supported" while deploying a copilot scheduled job

### ISSUE THREAD

**Issue by hardeepjethwani** [aws/copilot-cli#4940]
Hello folks, Hope you are doing well !! 

While deploying a copilot Scheduled job or a task, I have started facing below error. Production deployment is stucked. Can anyone suggest -- 

**_Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions._**

**Comment by Sangarshanan** [comment]
I think this needs to be bumped to 18.x similar to a PR that was raised earlier to bump to Lambda nodejs runtimes to 12.x https://github.com/aws/copilot-cli/pull/2237

**Comment by dannyrandall** [comment]
Hey @hardeepjethwani! Thanks for opening this issue. Can you share what version of copilot you are using, and the logical ID of the resource that is returning the error?

**Comment by Aarbel** [comment]
Got same error while running CDK, running on node 18.x is a big upgrade, is there any alternatives ?

<img width="1335" alt="image" src="https://github.com/aws/copilot-cli/assets/25119847/6e5243c0-ce5b-42d4-8e80-00137b861cf9">

**Comment by hardeepjethwani** [comment]
Hi @dannyrandall 

I was using 1.19.0 version. 
But now I have upgraded to v1.28.0 and trying to run copilot app upgrade, and then I am running copilot env deploy --force,  but I am facing an error in Cloudformation update--> export app-PrivateSubnets cannot be updated as it is in use by app-Service-A

**Comment by Aarbel** [comment]
With CDK i fixed it using everywhere i use "@aws-cdk/aws-lambda-nodejs" 

```
{
    runtime: lambda.Runtime.NODEJS_14_X,
    ....
}
```

**Comment by dannyrandall** [comment]
@hardeepjethwani Environment Manifests were released in v1.20.0 - did you run [these steps](https://aws.github.io/copilot-cli/blogs/release-v120/#environment-manifest) as you upgraded the environment? Could you share your environment manifest file? Additionally, could you share the manifest file that gets spit out when you run `copilot env show --manifest`?

`Service-A` imports the value from the Environment Stack to place tasks in the Environment's VPC. What I'm trying to figure out is _why_ the value of the `app-env-PrivateSubnets` output is changing, because it _should not_ change when running `copilot env deploy` unless the environment manifest has changed.

**Comment by hardeepjethwani** [comment]
Hi @dannyrandall, Thanks for pointing that copilot env show command. 

That solved my problem. Actually I added an extra subnet which caused the issue. We can consider this as resolved. 

One one question - copilot v1.28.0 deploys env control lambda functions with Nodejs 16.x runtime. 

Are there any upgrades coming to get these functions deployed to Nodejs 18.x ?

**Comment by dannyrandall** [comment]
Sweet, glad that resolved the issue! We will definitely upgrade to Nodejs 18.x as needed - we are also looking into migrating our custom resources to an image or a non-runtime language (like Go) as a long term solution to this issue.

**Comment by vibhoragarwal** [comment]
You must be using serverless 2.72.2
The support was removed by AWS completely recently (May-June 2023 seemingly)

serverless provides a patch for this, but you need to upgrade to 2.72.4, and in case you can - upgrade to version 3 (3.330+)

See
https://github.com/serverless/serverless/releases

[2.72.4 (2023-07-10)](https://github.com/serverless/serverless/releases/tag/v2.72.4) Pre-release
Bug Fixes
custom resource runtime upgrade ([#12055](https://github.com/serverless/serverless/issues/12055)) ([fb1d29c](https://github.com/serverless/serverless/commit/fb1d29ca243b88bf3206e1b05f5a69eccae29052))

https://github.com/serverless/serverless/pull/12055


AWS deprecated the node js v12 lambda runtime. This PR upgrades to node 16

Closes: [#12054](https://github.com/serverless/serverless/issues/12054)

https://github.com/serverless/serverless/issues/12054

[@aryakrishn](https://github.com/aryakrishn) it is important to note this has been addressed in the most recent version of framework v3.330 but we have also applied the fix to v2.72.4 incase there is a reason you are unable to upgrade to v3.

**Comment by BEmah** [comment]
npm install -g serverless@^2.72.4 works

**Comment by wstewarttennes** [comment]
I've gotten this error a few times recently. Somehow I fixed it before but can't figure out what to do to fix it now! Is this swallowing up another error that is different?

**Comment by Lou1415926** [comment]
@wstewarttennes Copilot should be using nodejs16.x runtime for all custom resources. After a brief search, I didn't find any place where we used nodejs12.x 🤔  What Copilot version are you on?

**Comment by SoundsSerious** [comment]
Having this issue as well, I believe upgrade the CLI tools will fix it for manual deployment, at least in my case

**Comment by vijay-ashok** [comment]
Hi, I'm using a old version of serverless framework (1.67.0) and I don't wanna upgrade right now to get the fix (because of migration efforts). Could anyone help me how to fix this issue in my case?

Here is the error log from serverless
`ServerlessError: An error occurred: CustomDashresourceDashapigwDashcwDashroleLambdaFunction - Resource handler returned message: "The runtime parameter of nodejs12.x is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs18.x) while creating or updating functions. (Service: Lambda, Status Code: 400, Request ID: 2b959d10-63f7-46f4-9970-478ae23f02da)" (RequestToken: 3304965f-8771-b869-a8c6-2d2751fa3deb, HandlerErrorCode: InvalidRequest).`

**Comment by Kylir** [comment]
Hello!

I'm hitting this issue with an old pipeline. The version of copilot used in the `buildspec.yml` is `copilot-linux-v1.11.0`.
I tried to set (in that same file) the version of `nodejs` and the version of copilot without success.

I guess I have to update my pipeline - but I don't know how.
Is there a Pipeline Migration guide somewhere please?

Thank you!
