### ISSUE TITLE
Prevent scheduling KMS key for deletion when deleting environment

### ISSUE THREAD

**Issue by WillGibson** [aws/copilot-cli#4972]
Is it possible to prevent the KMS Key provisioned by the infrastructure StackSet being scheduled for deletion when you tear down an environment?

We have bumped up against this when we want to completely tear down an environment then recreate it. E.g. non production environments which we would expect to be able to do this with regularly.

When the environment is provisioned a new KMS key is created. When the environment is deleted, the key is marked for deletion, but the secrets that were encrypted by the key are left in place and when we try to redeploy it blows up.

**Comment by bvtujo** [comment]
Hmm, this is an interesting use case and I'm sorry you had to find this issue the hard way. I'm also sorry that I don't have a better solution for you right now than to delete the secrets with API calls via the CLI and try redeploying. 

I can see the logic to retaining a KMS key so you can redeploy an environment, or at least providing an easy way to set up or tear down a batch of secrets on env creation/deletion, so that the churn isn't quite so onerous. There are some security implications to work through, though, with reusing KMS keys between environments, and those are nontrivial. Thanks again for the request! Feel free to thumb this issue to help us prioritize our backlog.

**Comment by WillGibson** [comment]
The work around @lgarvey used to get round it was to unschedule the key for deletion, re-enable it, then redeploy the environment we deleted.

It's just a bit of tedious manual stuff that...

- is likely to catch engineers out
- might require intervention from someone with more AWS privileges

...which we would like to avoid.

An option to not schedule it for deletion would be really helpful here, and we could perhaps contribute some effort to the work under the auspices of the ticket I am working on.

Are you able to explain the security implications?

**Comment by bvtujo** [comment]
Mostly we don't want it to be trivially easy (ie, possible through accidental misconfiguration) to be able to decrypt secrets in a production environment with a KMS key designated for test or dev environments. This would really be a matter of interface design to make it highly unlikely to accidentally opt in to sharing a KMS key between environments, or to bring a single KMS key from outside Copilot into multiple environments. 

This is an enhancement which might be best incorporated as part of a "BYOKMS" feature. Does that make sense?

**Comment by WillGibson** [comment]
We are just using the KMS key "as it comes from the Copilot machinery", we are not doing anything with it that would enable it to be used for anything else than it's own environment, so I'm not sure how the security risk would be introduced by having the option to not schedule it for deletion.

**Comment by iamhopaul123** [comment]
Hello @WillGibson.

> When the environment is deleted, the key is marked for deletion, but the secrets that were encrypted by the key are left in place and when we try to redeploy it blows up.

Just doublechecked our codebase and it seems like the KMS key, which is within the stackset instance, won't get deleted until you delete the whole application. I'm curious why the env deleting caused the deletion of the key. Could you help me doublecheck as well if the app was deleted instead of the env.

Also the secrets created by `copilot secret init` are encrypted by default AWS secret in that account instead of the KMS key Copilot creates. Can you tell us how these secrets were created and encrypted by the KMS key created by Copilot?

**Comment by WillGibson** [comment]
Hi @iamhopaul123 I was trying to check this out for you and hit a problem and have now joined this thread...

https://github.com/aws/copilot-cli/issues/4730#issuecomment-1590907222

**Comment by WillGibson** [comment]
@iamhopaul123 I can now confirm that the KMS key does not get scheduled for deletion when we delete an environment. I got mixed up there. Thanks for your help.

Are you able to flag this as an erroneous report and close it?

**Comment by KollaAdithya** [comment]
Thanks for the confirmation. I will close this issue for now
