### ISSUE TITLE
How to change domain for Load Balanced Web Service?

### ISSUE THREAD

**Issue by lominming** [aws/copilot-cli#4994]
Can I change the domain alias for my Load Balanced Web Service from `old_domain.com` to `new_domain.com` simply by changing `manifest.yml`?

Steps done so far:
1. `copilot app init --old_domain.com`
2. Inside `manifest.yml` I have:
```
http:
  path: '/'
  alias: ['old_domain.com', 'www.old_domain.com']
```
3. I want to change `old_domain` to `new_domain`. 

- **Do I need to delete the whole app just to do `init --new_domain.com`?**
- **How can I have 2 domains pointing at it to ensure some sort of failover transition?**

These were the open issues that were confusing:
- https://github.com/aws/copilot-cli/issues/2071
- https://github.com/aws/copilot-cli/issues/3045

**Comment by huanjani** [comment]
Hello, @lominming.

Unfortunately, yes -- you'll need to recreate the app in order to use a new domain with `copilot app init --domain new_domain.com`, and no -- you can't have two domains for the same app. Please see [this page](https://aws.github.io/copilot-cli/docs/developing/domain/) for more info.

**Comment by dannyrandall** [comment]
Closing in favor of #2071, #3045, and #3162.

**Comment by jetaggart** [comment]
@huanjani How are we supposed to do this if we have storage attached such as S3 or RDS? Wouldn't deleting the app delete all the environments and storage?
