### ISSUE TITLE
Why does svc show use --manifest instead of --env?

### ISSUE THREAD

**Issue by WillGibson** [aws/copilot-cli#5115]
@yusufsheiqh and I just noticed that the `copilot svc show` command uses `--manifest` instead of `--env`.

We were expecting the latter, which we feel is more intuitive.

Is there a reason for the `--manifest` or is it just a legacy thing that hasn't caught up with the naming convention we are seeing else where?

**Comment by bvtujo** [comment]
It's for parity with `env show --manifest`, and in fact was added afterward. 

The default view of `copilot svc show` is designed to gives you high-level information about all the different environments your service is deployed to, and what the configuration, URLs, and environment variables are for all of them. You can scope this down by environment by doing some json munging with `jq`; for example `copilot svc show --json | jq '.configurations[] | select(.environment == "test")', but it's not necessarily designed that way. 

When we added `copilot env show --manifest` we thought it would be a good idea to also let customers do this for service manifests. However, `--env` has a defined use in lots of other `svc` commands (like `svc status --env prod` to view the CPU, memory, and alarms of a service in the `prod` environment). `--manifest` also has the advantage of signifying that `svc show` will return different output (a manifest, instead of a high level description), rather than narrowing the focus to a specific environment.

So for those reasons we used the same flag as we did for `env show`, but let it take a value to specify the environment. Does that make sense?

**Comment by WillGibson** [comment]
Apologies for the enourmous time lag in my reply @bvtujo.

Your reply makes sense, in that I understand what you are saying, and can imagine the thought process that got you there, but I think that `--env` and `--manifest` could have different purposes/effects in this context and that specifying the environment via the `--env` flag is more intuitive.

My suggestion would be that...

`copilot svc show --env <some-environment>` - show a high level summary of the service in the specified environment

`copilot svc show --env <some-environment> --manifest` - show the manifest for the service in the specified environment
