### ISSUE TITLE
docs: Service Connect default value

### ISSUE THREAD

**Issue by hkford** [aws/copilot-cli#5133]
[The documentation for Backend Service](https://aws.github.io/copilot-cli/docs/manifest/backend-service/#network-connect) says  `network.connect` dafaults to false, but actually it is defined as true in [the manifest template](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/workloads/services/backend/manifest.yml#L47).

[The documentation for Load Balanced Web Service](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#network-connect) says  `network.connect` dafaults to false, but actually it is defined as true in [the manifest template](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/workloads/services/lb-web/manifest.yml#L41).

[The documentation for Worker Service](https://aws.github.io/copilot-cli/docs/manifest/worker-service/#network-connect) says  `network.connect` dafaults to false, and [the manifest template](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/workloads/services/worker/manifest.yml) has no default value. Maybe the default value is defined somewhere.

Is Service Connect default value different between service types?

**Comment by iamhopaul123** [comment]
Hello @hkford. This is a very good call. <strike> I think we want them to be consistent. Right now we don't add for worker service which seems to be something we should do. </strike> Actually, our doc is wrong right now because service connect is not available for worker service since it cannot expose any port.

> but actually it is defined as true in [the manifest template](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/workloads/services/lb-web/manifest.yml#L41).

I think the document is still correct because if you don't explicitly specify `network.connect`, the default value is `false` which makes sure we don't break existing customers. However, when you create new manifest file, we do want to enable that for new customers because that's a more preferable way than the default Service Discovery.

Just sent out a fix for this issue, which includes japanese doc changes as well. Please let me know your feedback 🙏

**Comment by hkford** [comment]
> I think the document is still correct because if you don't explicitly specify network.connect, the default value is false which makes sure we don't break existing customers. However, when you create new manifest file, we do want to enable that for new customers because that's a more preferable way than the default Service Discovery.

Let me clarify my understanding as follows:

When you generate a manifest file running `copilot svc init`, `network.connect` is set to `true` as it is defined as `true` in [the manifest template](https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/template/templates/workloads/services/lb-web/manifest.yml#L41). If you comment out `network.connect` property like the following and run `copilot svc deploy`, the default value of `network.comment` is false so an ECS task is launched with Service Connect disabled.  Is my understanding correct?

```yaml
name: 'frontend'
type: 'Load Balanced Web Service'

image:
  build: './frontend/Dockerfile'
  port: 8080
http:
  path: '/'
  healthcheck: '/_healthcheck'

cpu: 256
memory: 512
count: 3
exec: true
# comment out network property
# network:
#   connect: true # Enable Service Connect for intra-environment traffic between services.
```

**Comment by Lou1415926** [comment]
>  Is my understanding correct?

@hkford Yes that's accurate!

**Comment by hkford** [comment]
I understood you explanation. Thank you.
