### ISSUE TITLE
If I want to update services and environments in my copilot pipeline, do I need to create two pipelines?

### ISSUE THREAD

**Issue by icruwrks** [aws/copilot-cli#5170]
Hello.

Currently when I run the copilot pipeline init command,

Workloads or Environments?

```
  A pipeline can be set up to deploy either your workloads or your environments
  What type of continuous delivery pipeline is this?  [Use arrows to move, type to filter]
  > Workloads           (Deploy the services or jobs in your workspace)
    Environments        (Deploy the environments in your workspace)
```

If I want to update both services and environments when they are pushed to the develop branch of test-app, do I need to have two pipelines? For example, test-app-service-develop-pipeline and test-app-environment-develop-pipeline.

Also, do I need to worry about the order of execution when I create these two pipelines?

**Comment by huanjani** [comment]
Hello, @icruwrks!

Yes, you should have two separate pipelines, as env deployments and workload (services and jobs) deployments are different. 

If there are dependencies, like if your service needs an env resource to exist before whatever code changes are deployed, you may want to manually deploy the env then the service; otherwise, no.

Hope that helps!
