### ISSUE TITLE
NLB and ALB on the same environment

### ISSUE THREAD

**Issue by Drakula2k** [aws/copilot-cli#5196]
Hi!

I have an existing application deployed with copilot using a Load Balanced Web Service via ALB and imported SSL certificate (so I also specified http -> public -> certificates on the environment config).

Now I'm trying to create a new service with an NLB config (so I set `http: false` and added the `nlb:` section for it), but getting this error on deploy:

`✘ deploy service test-nlb-service to environment production: validate ALB runtime configuration for "http": cannot deploy service test-nlb-service without "alias" to environment production with certificate imported`

**Comment by KollaAdithya** [comment]
Hello @Drakula2k !

Currently Copilot does not support importing certificates in the environment manifest for NLB. It is only supported for ALB.
I have created a new issue #5199 to keep track of importing certificates for NLB.

**Fix**
But the error msg should be different if the alb is disabled and nlb is set with an environment having imported certificates. I have a [fix](https://github.com/aws/copilot-cli/pull/5198) for this scenario. Error msg looks like below ⬇️ 

`✘ deploy service frontend1 to environment test: cannot specify nlb.alias when env test imports one or more certificates`

**Workaround**
1. You can initialize an app with `copilot app init --domain`
2. Remove `http.public.certificates` config from the environment manifest and run `copilot env deploy`.
3. In service manifest you can specify `nlb.alias` so that Copilot creates and validate the certificate and also adds an A-record to the HostedZone in Route53 to route traffic to NLB.

This will help you serve https traffic to NLB.

Let me know if this fix your issue.

**Comment by Drakula2k** [comment]
@KollaAdithya Thanks for the quick reply and fix!

Unfortunately in my setup the domain is managed outside of AWS/Route53 so I can only use imported certs.
For now I ended up just deploying the NLB service as a separate app.

**Comment by KollaAdithya** [comment]
Glad you are able to deploy your service using NLB! I will close this issue for now.
Let us know if you have any further issues.

**Comment by KollaAdithya** [comment]
@Drakula2k 

> For now I ended up just deploying the NLB service as a separate app.

Do you mean are you managing this app outside of Copilot?

**Comment by Drakula2k** [comment]
@KollaAdithya I mean I deployed it as a separate copilot app. My domain DNS is on Cloudflare and I don't even need an alias for the NLB service, so this fix may be enough to support my use case.

**Comment by KollaAdithya** [comment]
Thank you so much for the clarification ❤️

**Comment by dannyrandall** [comment]
Hey @Drakula2k! We just released this fix [v1.30.0](https://github.com/aws/copilot-cli/releases/tag/v1.30.0)!🚀🎉 Thanks for reporting the issue!

**Comment by Drakula2k** [comment]
@dannyrandall thanks! I'll check it out
