### ISSUE TITLE
UX - "You can access your service at - over the internet" output when deploying "Backend Service" type

### ISSUE THREAD

**Issue by acodeninja** [aws/copilot-cli#5371]
When deploying a service with the type "Backend Service" with `copilot svc deploy --env <env> --name <svc>` the command finishes with the following lines:

```
Recommended follow-up action:
  - You can access your service at - over the internet.
```

I suggest that when a service configuration sets `network.connect` to `false` that this message not display at all, and when `network.connect` is `true` an alternative message display:

```
Recommended follow-up action:
  - Services in the same application can access your service at http://<svc>.<env>.<app>.internal 
```

**Comment by CaptainCarpensir** [comment]
Thanks for the feedback @acodeninja!

**Comment by CaptainCarpensir** [comment]
It looks to me like this happened because you have no ports exposed in your backend service, rather than it being an issue with the Service Connect configuration. I wrote a fix for this, and then I'm proposing the change to the wording you gave to more accurately represent when a service is publicly accessible or not in [this PR here](#5374)! 👍
