### ISSUE TITLE
support of internal NLB in a backend service

### ISSUE THREAD

**Issue by alissaVrk** [aws/copilot-cli#5440]
I want to create a gateway web socket API for a backend service.

NLB provides support for a PrivateLink whereas ALB doesn't.

as far as I understand there are two options to achieve this currently:
1. to create a Load Balanced Web Service with a public NLB and add an override converting the NLB to internal.
2. to create a Backend Service without a load balancer and add the internal NLB as an add-on.

I think that both options (specifically the first) will be hard to understand for a person reading my code.
And I don't know what other differences exist between a Backend Service and a Load Balanced Web Service created by copilot.

**Comment by CaptainCarpensir** [comment]
I agree with your conclusion on the options you have. As far as differences, there aren't that many. The LBWS and BS abstractions mainly differ in that the load balancer created by the LBWS is external and BS internal. I'd actually recommend the first option however because I think it'd be simpler to implement, though I haven't looked in depth on creating an internal NLB as an addon. Here's a [link](https://github.com/aws/copilot-cli/issues/5131) to an implementation of the first option.

I also see you've +1ed the [existing issue](https://github.com/aws/copilot-cli/issues/3840) we have for adding support to an internal NLB. Thanks for letting us know what features you'd like to see 👍
