### ISSUE TITLE
Missing EnvManagerRole role - can't execute any commands

### ISSUE THREAD

**Issue by keithslater** [aws/copilot-cli#5469]
I am currently testing copilot and am running into an issue. I was trying to delete an environment and it failed halfway through. Now any time I do anything with cli, I get an error like this:

```
describe environment staging: list deployed services in env staging: get resources by Copilot tags: 
get resource: AccessDenied: User: arn:aws:iam::xxx:user/user is not authorized to perform: sts:AssumeRole on 
resource: arn:aws:iam::xxx:role/project-staging-EnvManagerRole
	status code: 403
```
I checked and no `EnvManagerRole` role exists. I assume it was deleted at some point by copilot. The issue is I can't do any commands now - init, env show, nothing. 

How would I go about fixing this issue?

**Comment by Lou1415926** [comment]
@keithslater Is the stack for the "staging" environment still there? You can look for a stack named "<app name>-staging". If the stack exists, is there any `Delete` activity in the `Events` tab?

**Comment by keithslater** [comment]
There's not any that are active. They were all deleted successfully.

**Comment by Lou1415926** [comment]
Gotcha! I think at this point we will need to delete the rest of the resources manually. 

>  it failed halfway through

Do you happen to remember the failure message? This will give me an idea of a) what are still to be deleted b) why it failed (not that you asked, but I'd love to understand)

**Comment by keithslater** [comment]
Yeah that's kind of what I was thinking. Can you give direction on how to find these resources? In CloudFormation, all of the stacks show the resources as DELETE_COMPLETE.

The cli last errored on this:
```
copilot env delete --name staging                                                                                                                                                                                                                                                                                                     
✔ Retained IAM roles for the "staging" environment
✔ Delete environment stack project-staging
✘ Failed to remove environment resources from app "project"
✘ remove environment staging from application project: operation xxx for stack set project-infrastructure failed
```

For some reason I don't see anything in the stacks that caused it to fail. It seems like the stack isn't there anymore. Everything that is there looks successful.

**Comment by Lou1415926** [comment]
> ✘ Failed to remove environment resources from app "project"

This error tells me that you might have a failing stack named `StackSet-<app name>-infrastructure-<random string>`. I have 3 questions now 🥺:   
1. Can you take a look at the console, in the region where "staging" lived, and see if you can find it? If so, can you take a look at why it failed? 
2. Can you also take a look at another account or region that you are using, and see if a stack named similarly (except for the random string part) is in failure state or success state?
3. Is "staging" the last environment in that specific account, and that specific region?

A bit of explanation here for my questions:

This  `StackSet-<app name>-infrastructure-<random string>` stack is an instance of the stack set (basically, a bunch of stacks that have exactly the same template) called `<app name>-infrastructure` that is used to create app-level account-regional resources. For example, say you have 0 environment in us-east-1 account A, then there won't be such a stack in us-east-1 account B. Say you have 1 (or 2, or 3...) environments in us-east-1 account B, then there will be exactly one such stack in us-east-1 account B. 

A stack set update updates _all_ stack set instances, and fail when at least one of the instance fails to update. 

By asking the first question, I wanted to understand the reason why that instance fails to update. By asking the second question, I wanted to know if the failure is specific to that particular account / region. By asking the thrid, I wanted to know if it's safe for me to suggest deleting the specific stackset instance.

-----

More generally you can run ⬇️  to find the lingering resources. However in our case, because it's stack set that's failing, the solution is a bit more complicated because we want to delete the resources _while_ keeping the stack set in sync.
```
 aws resourcegroupstaggingapi get-resources \
  --tag-filters Key=copilot-application,Values=<your app name> \
  --tag-filters Key=coplot-environment,Values=staging
```

**Comment by keithslater** [comment]
1. Yes I found it. This was the last error (and this is what I remember from looking earlier today.)
```
Resource handler returned message: "The repository with name 'project/web' in registry with id 'xxx' cannot be deleted because it still contains images
The following resource(s) failed to delete: [ECRRepoweb].
```
I did remove this ecr registry manually earlier today. After that I deleted the stack and it deleted successfully. 

2. I don't have any other StackSet name in another account
3. Yes

**Comment by Lou1415926** [comment]
>  After that I deleted the stack and it deleted successfully.

That should be it then, since `staging` is the last environment in that region!

To double check you can run `copilot env ls` to see if "staging" is still listed. If so that probably means that you still have a SSM parameter named `/copilot/applications/<appname>/environments/staging`.

**Comment by keithslater** [comment]
Thank you, this has been really helpful. I'm running into one issue when trying to re-init. 

```
If you want to create a new workspace reusing the existing application project, please switch to the region where you created the application, and run `copilot app init`.
If you'd like to recreate the application and all of its resources, please switch to the region where you created the application, and run `copilot app delete`.
✘ ask app init: application named "project" already exists in another region
```

Is there a way to find where it thinks this lives? I've looked in both accounts and I see nothing in CloudFormation. I assume it's referencing it somewhere else.

**Comment by Lou1415926** [comment]
@keithslater ahh, that's actually trickier than expected 😓 Copilot is able to tell that there is a "project" somewhere because there is a "project-admin" IAM role, which is a global, instead of regional, resource. Because it's global, Copilot is not able to tell which region is comes from, hence the ambiguous error message "...in another region" 😞 

The solution, however, is _not_ to delete the IAM role, because that is not the only resource of "project". You are correct that you should locate the region, and run `copilot app delete --name` from that region.

One way to have _a best guess_ of the region, instead of brute force, is to look at the S3 console. Look for buckets named "stackset-web-and-backend-pipelinebuiltartifactbuc...". There might, or might not be multiple. Look at the regions of each of them, and see if the "project" stack is there.

**Comment by keithslater** [comment]
Is it possible the IAM role is the only resource left? I don't have any bucket with stackset in the name in either account. I also tried to delete the app in both accounts and they both say "couldn't find."

**Comment by Lou1415926** [comment]
>Is it possible the IAM role is the only resource left?

It is quite unlikely. The IAM role is managed by a CloudFormation stack called "project-infrastructure-roles". If the role is still there, it is very likely that the stack is still there.

Have you tried switching regions in each of the accounts? A majority of the AWS services are regional, meaning that when you check in "us-east-1", you will not see the resources that live in "us-west-1".
<img width="360" alt="Screenshot 2023-11-14 at 10 08 44 AM" src="https://github.com/aws/copilot-cli/assets/79273084/7c4e8623-d473-4acb-a167-f4fe6a3e22fd">


Here is a little script that might be helpful for you!

```sh
regions=$(aws account list-regions --output json| jq -r ".Regions[].RegionName")
for region in ${regions}
do
    echo "checking in ${region}"
    export AWS_REGION=$region
    aws cloudformation describe-stacks --stack-name project-infrastructure-roles 2>/dev/null 
    exit_code=$?
    if [ $exit_code -eq 0 ]; then
        echo "found in ${region}"
        break
    fi
done
    
```

**Comment by keithslater** [comment]
Yes I do have the `project-infrastructure-roles` cloudformation stack. Should I delete this?

**Comment by Lou1415926** [comment]
I recommend first trying this:
```
export AWS_DEFAULT_REGION=${region} # The region that the script found the stack in.
copilot app delete --name project
```

Copilot will clean up all resources automatically!

**Comment by keithslater** [comment]
So the script gets this:
`found in us-east-1`

But trying to do the delete, it says:
`couldn't find an application named project in account xxx and region us-east-1`

**Comment by Lou1415926** [comment]
Oh `couldn't find an application named project in account xxx and region us-east-1` indicates that Copilot isn't able to find `"copilot/applications/project"` in SSM parameter store. Perhaps you've deleted it earlier 🤔 

No worries, in this case, you can:
1. Go to us-east-1, go to CloudFormation console
2. Go to the StackSet tab, look for a stackset named "project-infrastructure", select "delete stackset". On the next page, put your own account ID, select "All region".
3. If 2 failed because some stackset instance is "INOPERABLE", do 2 again but this time check "Retain Stacks". Then you can go to the individual stack set instance and delete them one by one.
4. Next go to the Stack tab, delete "project-infrastructure-roles" stack.
5. Run ⬇️ to make sure everything is cleaned up
```
aws resourcegroupstaggingapi get-resources \
  --tag-filters Key=copilot-application,Values=<your app name> \
```

**Comment by keithslater** [comment]
I think it's working now. Thanks again for all of your help! I've learned a lot from this.
