### ISSUE TITLE
Could not resolve the variable even though it is defined in service manifest.yml file

### ISSUE THREAD

**Issue by MonuAnu** [aws/copilot-cli#5480]
Hello,

We are getting below error while deploying our service. It was working before.

Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'ALIAS' in value "${ALIAS}"

Service manifest.yml:
variables:                   
  ALIAS: https://url

application.yml:

general:
  cors: ${ALIAS}

we are getting this issue when we change manifest.yml file(for example we have changed healthcheck path).

**Comment by Lou1415926** [comment]
Hi @MonuAnu 👋🏼  Thanks for the question, though I am not sure I understand :(. The error message doesn't seem like it comes from Copilot. Do you by any chance use sprint boot?

**Comment by MonuAnu** [comment]
Hello @Lou1415926 ,

yes, we use spring boot.

**Comment by Lou1415926** [comment]
@MonuAnu Gotcha. Does the error "Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'ALIAS' in value "${ALIAS}" happen during build time or run time?

**Comment by MonuAnu** [comment]
During the build(maven clean install)

**Comment by Lou1415926** [comment]
I see! The `variables` field specifies environment variables that are needed during runtime. They are injected into your container running on ECS.

If you need a build time variable, [`docker.build.args`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#image-build) is probably what you are looking for; also see https://docs.docker.com/build/guide/build-args/ to see what changes you might need to make to your Dockerfile.

**Comment by MonuAnu** [comment]
Now i get the issue with another variable which is a secret and defined as below in manifest.yml.
secrets:
  MY_SECRET:
    from_cfn: ${COPILOT_APPLICATION_NAME}-${COPILOT_ENVIRONMENT_NAME}-MySecret

Is this also a runtime variable? how can i pass it as build time variable? 

We did not get this issue before, we changed the application code but not the variables behaviour. Why are we getting the issue now and not before(when we introduced these variables for the first time).

**Comment by Lou1415926** [comment]
> Is this also a runtime variable? how can i pass it as build time variable?

The `secrets` field is also for runtime env vars. Under the hood, when starting your containers, ECS pulls the secrets from secretsmanager or SSM, and then inject the secrets into the container.

Basically, if you need to pass a secret (stored on the cloud) during build (happens on your local machine, when running `svc deploy`), I'm afraid there only three non-optimal way.

#### 1. Pull the secrets yourself, pass to `image.build.args`

You can pull the secrets, store the secrets _as plain text_ in a shell environment variable and then pass them into the manifest via. `image.build.args`. 
1. `my_secret_value=$(aws secretsmanager get-secret-value ... | jq .'SecretString')`
2. Refer to the shell env var from manifest.
```yaml
image:
  build:
    args:
      MY_SECRET: ${my_secret_value} # Read the environment variable in your shell that stores the secret value
```

This workaround is also mentioned in #4224.

__A CAVEAT__ of this approach is that, docker args are passed in plain string. That is, the "secret values" are visible if someone goes to your local machine and run `docker history`. It would have been secure if we can pass it as a docker secret, but this [feature request](https://github.com/aws/copilot-cli/issues/4230) is yet to be supported. 

#### 2. Pull the secrets yourself, run `docker build --secret` and pass the image url to `image.location`
Alternatively, referring to what @bvtujo said [here](https://github.com/aws/copilot-cli/issues/1599#issuecomment-719824837) - you can build the image yourself, and pass the image url into `image.location`. This way, although you still need to pull the secret values yourself (step 1), you can now securely pass the secret value to docker build via `--secret` flag.

#### 3. CodeBuild in CI/CD
Finally, if you are using CodeBuild as a part of your CI/CD, then solution 1 may not be that bad after all. You can use the `env.secrets_manager/parameter_store` section, so that CodeBuild pulls the secret to the build env. This is basically the step 1 of solution 1. What makes it not bad is that CodeBuild projects do not have a public IP, therefore it is very difficult for an attacker to hack into your ephemeral CodeBuild project, and get the secret by running `docker history`

This is discussed in https://github.com/aws/copilot-cli/issues/4230#issuecomment-1734260371.


----
The ideal solution would be for Copilot to have supported https://github.com/aws/copilot-cli/issues/4230, that lets you:
1.  Ask Copilot to pull secrets from SSM/secretsmanager _at build time_.
2. Pass those secrets to `docker build --secret`.
---
**Edit**: forgot to address your second question!

> Why are we getting the issue now and not before(when we introduced these variables for the first time).

This, I unfortunately don't have a conclusive explanation. Copilot's behaviors on how it treats `variables`, `secrets`, `image.build.args` and `${shell _variable}` has not changed at all, for a very long time. If I have to guess, I think the change of outcomes is not likely coming from Copilot, but I stand corrected!
