### ISSUE TITLE
multi account pipeline times out 1 service without errors

### ISSUE THREAD

**Issue by sebastianovide** [aws/copilot-cli#5560]
Hi,

I have a pipeline on a different account that the account hosting the app. The pipeline seems to be working for what I've observed in cloud formation but it times out. I cannot see any error. Any ideas? (after a while, it times out and it becomes a failure)

<img width="907" alt="Screenshot 2023-12-13 at 23 02 49" src="https://github.com/aws/copilot-cli/assets/1496395/582a3620-460a-4acd-b016-83637e192cc3">

This is the service that is timing out 
<img width="769" alt="Screenshot 2023-12-13 at 23 02 16" src="https://github.com/aws/copilot-cli/assets/1496395/ca532228-cfa9-4ebc-968a-e1c3fc46d88f">

**Comment by iamhopaul123** [comment]
Hello @sebastianovide. Can you manually run `copilot svc deploy` to deploy the problematic service to the environment? The progress tracker should be able to tell you why it failed (my guess is the ECS service failed to spin up any healthy tasks).

Also the reason why you don't see any error from the screenshot of the CFN console, I think, is because of you are either looking at the wrong account or region. If you switch to the correct account/region as the `web-dev` environment (you should've selected the profile when creating the environment or use `env show` to see what acct./region), you would be able to see the failure from the CFN console.

**Comment by sebastianovide** [comment]
Hello @iamhopaul123 
`copilot svc deploy` works without problems... it only fails while running via the pipeline

> Also the reason why you don't see any error from the screenshot of the CFN console, I think, is because of you are either looking at the wrong account or region. If you switch to the correct account/region as the web-dev environment (you should've selected the profile when creating the environment or use env show to see what acct./region), you would be able to see the failure from the CFN console.

you are right. From that account, I see an error. As the service has a slow start (it has a `grace_period: 3m`), is it possible that it times out in some how ?


    

![Screenshot 2023-12-14 at 13 55 20](https://github.com/aws/copilot-cli/assets/1496395/1c601911-5b13-420b-bc48-c62b83a4e283)

**Comment by iamhopaul123** [comment]
Hello @sebastianovide. I think it would be nice to find out the root reason why these tasks failed to start: you can run `copilot svc status` to see the last stopped tasks and reasons why they failed. Or go to the ECS console and find your service and the stopped tasks there.

**Comment by sebastianovide** [comment]
thanks @iamhopaul123 , just to confirm that it was a problem with the app itself. Nothing wrong the copilot. Thanks for the tips on how to debug it.
