### ISSUE TITLE
While doing initial deployment copilot geting StackName validation error

### ISSUE THREAD

**Issue by ujwal-sai** [aws/copilot-cli#5563]
Hi Team,

I have started the initial setup of ecs using copilot and following the getting started document in the copilot github repo and  receiving the below error

"""get app resources: describing application resources: getting outputs for stack in region ap-south-1: describe stack : ValidationError: 2 validation errors detected: Value '' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*; Value '' at 'stackName' failed to satisfy constraint: Member must have length greater than or equal to 1 status code: 400, request id: a070b097-209a-43d2-a6ab-af2a46d488bd"""

can you please have a look and let me know.

**Comment by iamhopaul123** [comment]
Hello @ujwal-sai. Can you give us more context about this issue? For example, what command did you run before seeing this error msg?

**Comment by ujwal-sai** [comment]
Hi @iamhopaul123 
I am getting this error at the initial step while follow through the getting started guide from aws : https://docs.aws.amazon.com/AmazonECS/latest/developerguide/getting-started-aws-copilot-cli.html

i.e while executing this command:  

git clone https://github.com/aws-samples/amazon-ecs-cli-sample-app.git demo-app && \ 
cd demo-app &&                               \
copilot init --app demo                      \
  --name api                                 \
  --type 'Load Balanced Web Service'         \
  --dockerfile './Dockerfile'                \
  --port 80                                  \
  --deploy
  
  After giving the environment details, it is failing.

**Comment by iamhopaul123** [comment]
Hello @ujwal-sai. My guess is there's some permission issue with your stackset causing it failed to create any stackset instance. Could you go to the CFN console at `ap-south-1` region and get a screenshot or give us a list of what Copilot stacks you have over there? Thank you!

**Comment by ujwal-sai** [comment]
yaa @iamhopaul123 , Actually the role I am using is having the admin privileges 
And in CFN I can see one stack that was created by copilot has its name ends with *roles suffix.

**Comment by Lou1415926** [comment]
@ujwal-sai Hello 👋🏼 Can you take a look and see if there is a stack named `StackSet-<app-name>-infrastructure-<random string>`? If not, you can filter the stacks by "Deleted", "Failed", or "Complete" (the default filter is "Active" which doesn't show you all the stacks you've owned).
<img width="236" alt="Screenshot 2023-12-18 at 11 14 17 AM" src="https://github.com/aws/copilot-cli/assets/79273084/34f737b6-6c81-4fc4-86cb-badc62f09027">

If the stack is there and is _not_ in a successful state, it'd help if you let me know which resources were causing the stack to fail. If you are comfortable with sharing screenshots, that'd help too.

**Comment by ujwal-sai** [comment]
Hi @Lou1415926 , I have checked all the combinations (i.e active, failed..etc ) you mentioned, Didn't find the stack which is of the above mentioned format, there are no recent failed or in progress stacks, can you suggest a way to connect with one-on-one, to share the screen.

**Comment by Lou1415926** [comment]
It seems like your stack set instance in the said region has failed to be created for some reason. You _probably_ would be able to see the reason why by going to the CloudFormation console -> Stack sets -> find the one with the <app>-infrastructure name > Operations. 

My intuition is that this is related to #4126 - that the stack set instance has failed silently. This is because the CloudFormation API does not return an error when one of the instance of a stack set fails to update, so Copilot hasn't been able to detect the instance deployment error.

Alternatively, since it seems like you were early in the app creation, you could delete the app, and retry it. In addition to running `copilot init`, you can try running `copilot app init`, `copilot env init` and then `copilot env deploy`, which is a less streamlined alternative to `copilot init`. 

During `copilot env init`, try to see if the progress tracker logs any error message. Though Copilot isn't able to return an error due to the reason above yet, it will try to log instance deployment progress on the screen, which may contain helpful information.

> can you suggest a way to connect with one-on-one, to share the screen.

You can email aws-copilot-feedback@amazon.com to kick off a discussion and set up a time. I'd recommend trying the steps that I discussed above before jumping on a call though, as we typically don't debug / resolve guidance issue with users through video calls ❤️

**Comment by acasmp** [comment]
Just to add my 2 cents here. Had the exact same issue as the one from the original question and it was solved by adding missing IAM permissions to the user. Make sure you have these at least:

				"iam:GetRole",
				"iam:PassRole",
				"iam:DeleteRolePolicy",
				"iam:TagRole",
				"kms:GenerateDataKey",
				"iam:CreateRole",
				"iam:DeleteRole",
				"iam:PutRolePolicy",
				"iam:GetRolePolicy"
