### ISSUE TITLE
Does copilot will create listener for imported alb automatically?

### ISSUE THREAD

**Issue by Folyd** [aws/copilot-cli#5618]
I read this from the [v1.32.0 release notes](https://github.com/aws/copilot-cli/releases/tag/v1.32.0):
> Bring your own application load balancer if you don't like the default shared application load balancer of your environment! Just specify the name or the ARN of the application load balancer in the `http.alb` field, and **Copilot will figure out whether it has an HTTP listener, an HTTPS listener, or both. Copilot will then create listener rules on the listeners it finds**, and optionally upserts A records for your alias to the respective hosted zones if any are specified!

However, It didn't create listener for my imported alb. After deployed, I run `copilot svc show`, it gives the following error:

```log
$ copilot svc show
Service name: api-backend
✘ describe service api-backend: retrieve service URI: get host headers for listener rules : 
    get listener rule for : ValidationError: Rule or listener must be specified
        status code: 400, request id: 4930eb1d-4f8c-4926-9a9d-0710cf9824f5
```

**Comment by Lou1415926** [comment]
Hello @Folyd 👋🏼  Copilot doesn't create the listeners for the imported ALB; it creates the listener rules (that you'd need to route based on path, alias, etc.) on the correct HTTP listener and HTTPS listener so that the routing and redirecting would just work. You do need to bring your own listeners with the alb to benefit from these listener rules!
