### ISSUE TITLE
Copilot adds "latest" tag to builds, need per branch tags

### ISSUE THREAD

**Issue by chrisschaub** [aws/copilot-cli#5636]
I've been trying to wrap my head around the issues to having a single ECR repository with images tagged by branch, or separate ECR repos per branch. I need the "qa" branch build and deploy to always just use the qa built code. It seems the "latest" tag is geting added to the latest build, I worry that is being deployed by default. What is the best approach to ensure that "qa" builds a qa image and that is what gets deployed, vs production etc. Is it simplest to just have copilot make ECR repos per branch and that way the "latest" will always get deployed? I don't want to do anything manually, just want this to all work with pipelines on github push. Thanks!

**Comment by CaptainCarpensir** [comment]
This is a great question yeah! Basically, running `svc deploy` or `svc package --upload-assets` you can add the `--tag` flag to tag the image uploaded. This is actually what we do in the `buildspec.yml` file for pipelines, so in order to get the functionality you're looking for you need to modify this buildspec file. This should let you tag the uploaded builds with the branch name all under one ECR repository.

There's an old discussion of others trying to do similar things [here](https://github.com/aws/copilot-cli/issues/1943#issuecomment-1216939399). Let me know if you have any other questions on how to get this working.
