### ISSUE TITLE
deploy a Postgres DB on RDS

### ISSUE THREAD

**Issue by akenarsari** [aws/copilot-cli#5643]
I was looking at the `storage init` command but looks like it only support Aurora Serverless. Any guidelines on how to add a storage backed by AWS RDS instead of Aurora Serverless?

**Comment by KollaAdithya** [comment]
Hello @akenarsari 👋 
For creating a AWS RDS instead of Aurora serverless with Postgres DB engine, can you look at this [comment](https://github.com/aws/copilot-cli/issues/1178#issuecomment-963408231)

```
.
└── addons/
    ├── template.yml
```

1. You can store the custom templates in your workspace under `copilot/<workload>/addons` directory.
2. When running copilot [svc/job] deploy, the custom addons template will be deployed along with your workload stack.

**Comment by KollaAdithya** [comment]
Closing this for now. Feel free to open in case of any other question.

**Comment by morganney** [comment]
Why was this closed? Is the implication that `copilot storage init` has no plans to support a basic RDS cluster but only serverless?

**Comment by KollaAdithya** [comment]
Hey @morganney 

I opened a new [issue](https://github.com/aws/copilot-cli/issues/5649) as feature request/enhancement to generate traditional RDS Postgres DB.

Can you please upvote to help us prioritize and and sharing your idea there?
