### ISSUE TITLE
CPUUtilization Service metrics

### ISSUE THREAD

**Issue by musenaw** [aws/copilot-cli#5653]
Hi!

We are using AWS Copilot in our producction environments to some percentage of users, and in order to sent more traffic to this new architecture we want to be sure to have the right shape of minimin tasks running.   

We have some spikes of 127% of maximum CPUUtilization and average is on 35%, reading ECS documentation about it [link to doc](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html#service_utilization) and example says the following  
```
In this example, the CPU utilization will only go above 100% when the CPU units are defined at the container level.  
If you define CPU units at the task level, the utilization will not go above the defined task-level limit.
```

As per my understanding cpu its defined at task level and not at cluster level, we have 8 tasks with 1 vcpu defined in our manifest and should never go up more than 100%. How we should interpret those max CPUUtilization spikes more than 100%?

Thanks!

**Comment by iamhopaul123** [comment]
Hello @musenaw. I would be surprised to see the spike could be as high as 127% as well for cpu usage...since you are absolutely right we set the cpu at task level and it seems to be a hard limit. Most likely there is some nuance between what it is described in the doc vs how ECS actually calculates the metrics. However, it def. means the task is unhealthy and ECS scheduler will spin up more tasks if it gets more datapoint like this.
