### ISSUE TITLE
Why alias is feature of Service but not Environment? 

### ISSUE THREAD

**Issue by vponoikoait** [aws/copilot-cli#5677]
In my case, I have service which must be deployed to multiple environment. 
Currently, I only have 1 environment and I have imported certificate within the environment manifest. 
I do still need to specify alias & hosted zone on service level. Why so? Doesn't that mean that I can have only 1 alias in this case? 
It wouldn't be possible for me to build 

dev.example.com 
stg.example.com

Please, clarify if possible. Alias functionality for now feels like only for 1 environment at a time.

**Comment by vponoikoait** [comment]
Seems to be duplicate of https://github.com/aws/copilot-cli/issues/3293
@Lou1415926 
Can you elaborate, please?

**Comment by Lou1415926** [comment]
Hi @vponoikoait.

Let me know if I didn't understand your request correctly - I think you are looking for per-[`environments`](https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#environments) configuration for services.

For example, you can have `dev` env and `stg` env. You can specify service manifest like this:
```yaml
environments:
  dev:
    http:
      alias: dev.example.com
  stg:
    http:
      alias: stg.example.com
```

When you run `copilot svc deploy --env stg`, the service deployed in the "stg" environment will get an alias of stg.example.com (of course, assuming your "stg" environment has imported a certificate that covers this alias). Same for "dev".


> I do still need to specify alias & hosted zone on service level. Why so? 

You _could_ have multiple services in one environment, and each of these services might want different aliases. For example, you might have imported a certificate into the "dev" env, that covers "dev.example.com", "*.dev.example.com". Then within the "dev" env, you could use "dev.example.com" for service A, and "b.dev.example.com" for service B. 

Hope this clarifies things!

**Comment by vponoikoait** [comment]
@Lou1415926 that's exactly what I was looking for. 
Thanks a lot! 
Having this be highlighted within the documentation would've be very nice.
I had a long road searching through github issues. Lucky I was able to find you! I will test it and close the issue if everything works as expected for my use case.

**Comment by vponoikoait** [comment]
I have actually one questions which does relate to my use case 
I am 'importing' domain from Route53 with the usage of [http.public](https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public) for my service 
I need to actually apply it for environment. In my case, I have no domain on my app already - my actual goal is to assign one without app deletion (https://aws.github.io/copilot-cli/docs/developing/domain/)  
If I have certificate specific for my service like - example: messaging service & alias is present only for messaging service - why my certificate is scoped environment level then? 

Alias in this case is human friendly domain of mine, certificate is actually **scoped only for specific service** (messaging) 

Shouldn't it be working option to put [http.public](https://aws.github.io/copilot-cli/docs/manifest/environment/#http-public) to the service level?  I wasn't able to specify alias without certificate being actually 'deployed' on env, despite the fact that I actually have route53 hosted zone & domain specified on my service level. May it be applicable to request this working with only alias & route53 hosted zone ID specified, so that certificate is created on its own as a part of the flow? 

Maybe there're better strategies which you may be aware of, or some useful links covering 'importing' use case for alias? 
@Lou1415926 

Thanks you a lot in advance for your answer.

**Comment by Lou1415926** [comment]
@vponoikoait All good questions!! I think decision to put `certificate` in the environment manifest was mostly because the ALB - to which the certificate is attached-  is an environment-level resource that's shared across the services within the same env; the certificate can be shared across the services too. This indeed doesn't work super nicely for your use case :(.

> May it be applicable to request this working with only alias & route53 hosted zone ID specified, so that certificate is created on its own as a part of the flow?

This sounds reasonable to me. The alias and the hosted zone ID should be enough information for Copilot to request for a certificate and validate it!

> Maybe there're better strategies which you may be aware of, or some useful links covering 'importing' use case for alias?

[This](https://aws.github.io/copilot-cli/docs/developing/domain/#use-domain-in-your-existing-validated-certificates) is the doc that covers steps to import alias, which I think you probably have already seen 😞 ! Your workflow right now (deploying env, and then deploy the service with the alias) is indeed the standard strategy right now. Technically, there might be crazy workaround using [yaml patch](https://aws.github.io/copilot-cli/docs/developing/overrides/yamlpatch/) - you can set up on the environment stack a custom resource backed by a lambda that creates & validates the certificate, and trigger the custom resource via. `EnvController`, which is triggered from the service stack... This is super hacky and involves a ton of work, so I wouldn't recommend it :( !

**Comment by vponoikoait** [comment]
@Lou1415926 should I in this case create separate issue for the feature request for copilot to automatically provision certificate for SVC based on Hosted Zone & alias?
Thanks a lot, I have confirmed everything I actually needed to, so I will close this issue.

**Comment by Lou1415926** [comment]
@vponoikoait you can either edit the description and the title of this issue or create a separate one, either works!
