### ISSUE TITLE
[Question] SecurityHub: CodeBuild project environments should not have privileged mode enabled.

### ISSUE THREAD

**Issue by h5aaimtron** [aws/copilot-cli#5699]
All our CI/CD pipelines provisioned through copilot are flagged under security hub with a "High Severity" rating for the CodeBuild project environments having privileged mode. I didn't see anything specific to this in the documentation, although its possible I missed it. I'm wondering how I can tackle this concern and move forward within my environment. Any information is absolutely appreciated.

**Comment by Lou1415926** [comment]
Seems like [CodeBuild.5](https://docs.aws.amazon.com/securityhub/latest/userguide/codebuild-controls.html#codebuild-5) is the rule in question.

The privileged mode is enabled so that Copilot can build images during the Build stage (which is backed by a CodeBuild project), which in a way agrees with the rule:
> This parameter should only be set to true if the build project is used to build Docker images.

You could build images separately and start using `image.location` for all services. Copilot will not need to build any images during the Build stage; this way, you should be able to disable the privileged mode using YAML patch.

I'd suggest not changing anything for now, because Security Hub will remove this control on March 16, 2024 (see the banner under [CodeBuild.5](https://docs.aws.amazon.com/securityhub/latest/userguide/codebuild-controls.html#codebuild-5))

**Comment by h5aaimtron** [comment]
@Lou1415926 thanks for the info, much appreciated!
