### ISSUE TITLE
Help Needed: Unable to init app

### ISSUE THREAD

**Issue by shain-digix** [aws/copilot-cli#5726]
I tried to run `copilot app init` but got this error.

_If you want to create a new workspace reusing the existing application cd-paas-ngpayments, please switch to the region where you created the application, and run `copilot app init`.
If you'd like to recreate the application and all of its resources, please switch to the region where you created the application, and run `copilot app delete`.
✘ application named "cd-paas-ngpayments" already exists in another region_

Tried to run this command, but showed no existing application:
`copilot app ls      `        

Initially i tried to create the app, but it failed due to unavailable permissions

**Comment by huanjani** [comment]
Hello, @shain-digix! 

My guess is that Copilot thinks there is an app with that name in your workspace because there is an `.workspace` file that was created the last time you attempted to create this app. It got far enough to create that hidden file, but not far enough to create a parameter in Systems Manager Parameter Store, which is where the `copilot app ls` command looks for applications. 

Please `rm` your `.workspace` file, then try running `copilot app init` again!

**Comment by shain-digix** [comment]
Thanks
